require.pause();
require.def("preview/pageList",["domplate/domplate","core/lib","core/trace","preview/requestList"],function(n,b,h,m){with(n){n=function(j){this.input=j};n.prototype=domplate({tableTag:TABLE({"class":"pageTable",cellpadding:0,cellspacing:0,onclick:"$onClick",_repObject:"$input"},TBODY(TAG("$rowTag",{groups:"$input.log.pages"}))),rowTag:FOR("group","$groups",TR({"class":"pageRow",_repObject:"$group"},TD({"class":"groupName pageCol"},SPAN({"class":"pageName"},"$group|getPageTitle")))),bodyTag:TR({"class":"pageInfoRow",
style:"height:auto;"},TD({"class":"pageInfoCol"})),getPageTitle:function(j){return b.cropString(j.title,100)},getPageID:function(j){return"["+j.id+"]"},onClick:function(j){var a=$.event.fix(j||window.event);if(b.isLeftClick(j))if(a=b.getAncestorByClass(a.target,"pageRow")){this.toggleRow(a);b.cancelEvent(j)}},toggleRow:function(j,a){if(!(b.hasClass(j,"opened")&&a)){b.toggleClass(j,"opened");if(b.hasClass(j,"opened")){a=this.bodyTag.insertRows({},j)[0];(new m(this.input)).render(a.firstChild,j.repObject)}else{a=
j.nextSibling;j.parentNode.removeChild(a)}}},expandAll:function(j){for(j=j.firstChild.firstChild;j;){hasClass(j,"pageRow")&&this.toggleRow(j,true);j=j.nextSibling}},getPageRow:function(j){for(var a=b.getElementsByClass(this.element.parentNode,"pageRow"),c=0;c<a.length;c++){var e=a[c];if(e.repObject==j)return e}},togglePage:function(j){this.toggleRow(this.getPageRow(j))},expandPage:function(j){this.toggleRow(this.getPageRow(j),true)},collapsePage:function(j){j=this.getPageRow(j);b.hasClass(j,"opened")&&
this.toggleRow(j)},append:function(j){(new m(this.input)).render(j,null);var a=this.input.log.pages;if(a&&a.length){j=this.tableTag.append({input:this.input},j,this);j.firstChild.childNodes.length==1&&j.parentNode.childNodes.length==1&&this.toggleRow(j.firstChild.firstChild)}},render:function(j){this.append(j)}});return n}});require.def("harPreview",["preview/pageList","preview/harModel"],function(n,b){b.Loader.run(function(h){h=b.parse(h,true);(new n(h)).render(document.getElementById("content"))})});
require.def("core/lib",["core/trace"],function(n){var b={},h=navigator.userAgent.toLowerCase();b.isFirefox=/firefox/.test(h);b.isOpera=/opera/.test(h);b.isSafari=/webkit/.test(h);b.isIE=/msie/.test(h)&&!/opera/.test(h);b.isIE6=/msie 6/i.test(navigator.appVersion);b.browserVersion=(h.match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/)||[0,"0"])[1];b.isIElt8=b.isIE&&b.browserVersion-0<8;b.extend=function(a,c){var e={};b.append(e,a);b.append(e,c);return e};b.append=function(a,c){for(var e in c)a[e]=c[e];return a};
b.bind=function(){var a=b.cloneArray(arguments),c=a.shift(),e=a.shift();return function(){return c.apply(e,b.arrayInsert(b.cloneArray(a),0,arguments))}};b.bindFixed=function(){var a=b.cloneArray(arguments),c=a.shift(),e=a.shift();return function(){return c.apply(e,a)}};b.dispatch=function(a,c,e){for(var f=0;a&&f<a.length;f++){var l=a[f];if(l[c])try{l[c].apply(l,e)}catch(k){n.exception(k)}}};b.dispatch2=function(a,c,e){for(var f=0;f<a.length;f++){var l=a[f];if(l[c])try{var k=l[c].apply(l,e);if(k)return k}catch(d){n.exception(d)}}};
var m=Object.prototype.toString,j=/^\s*function(\s+[\w_$][\w\d_$]*)?\s*\(/;b.isArray=function(a){return m.call(a)==="[object Array]"};b.isFunction=function(a){if(!a)return false;return m.call(a)==="[object Function]"||b.isIE&&typeof a!="string"&&j.test(""+a)};b.isAncestor=function(a,c){for(a=a;a;a=a.parentNode)if(a==c)return true;return false};b.fixEvent=function(a){return $.event.fix(a||window.event)};b.fireEvent=function(a,c){if(document.createEvent){var e=document.createEvent("Events");e.initEvent(c,
true,false);return!a.dispatchEvent(e)}};b.cancelEvent=function(a){a=b.fixEvent(a);a.stopPropagation();a.preventDefault()};b.addEventListener=function(a,c,e,f){f=f||false;a.addEventListener?a.addEventListener(c,e,f):a.attachEvent("on"+c,e)};b.removeEventListener=function(a,c,e,f){f=f||false;a.removeEventListener?a.removeEventListener(c,e,f):a.detachEvent("on"+c,e)};b.isLeftClick=function(a){return a.button==0&&b.noKeyModifiers(a)};b.noKeyModifiers=function(a){return!a.ctrlKey&&!a.shiftKey&&!a.altKey&&
!a.metaKey};b.isControlClick=function(a){return a.button==0&&b.isControl(a)};b.isShiftClick=function(a){return a.button==0&&b.isShift(a)};b.isControl=function(a){return(a.metaKey||a.ctrlKey)&&!a.shiftKey&&!a.altKey};b.isAlt=function(a){return a.altKey&&!a.ctrlKey&&!a.shiftKey&&!a.metaKey};b.isAltClick=function(a){return a.button==0&&b.isAlt(a)};b.isControlShift=function(a){return(a.metaKey||a.ctrlKey)&&a.shiftKey&&!a.altKey};b.isShift=function(a){return a.shiftKey&&!a.metaKey&&!a.ctrlKey&&!a.altKey};
b.inflateRect=function(a,c,e){return{top:a.top-e,left:a.left-c,height:a.height+2*e,width:a.width+2*c}};b.pointInRect=function(a,c,e){return e>=a.top&&e<=a.top+a.height&&c>=a.left&&c<=a.left+a.width};b.cloneArray=function(a,c){var e=[];if(c)for(var f=0;f<a.length;++f)e.push(c(a[f]));else for(f=0;f<a.length;++f)e.push(a[f]);return e};b.arrayInsert=function(a,c,e){for(var f=0;f<e.length;++f)a.splice(f+c,0,e[f]);return a};b.remove=function(a,c){for(var e=0;e<a.length;++e)if(a[e]==c){a.splice(e,1);break}};
b.formatSize=function(a){var c=1;c=c>2?2:c;c=c<-1?-1:c;if(c==-1)return a+" B";c=Math.pow(10,c);return a==-1||a==undefined?"?":a==0?"0":a<1024?a+" B":a<1048576?Math.round(a/1024*c)/c+" KB":Math.round(a/1048576*c)/c+" MB"};b.formatTime=function(a){return a==-1?"-":a<1E3?a+"ms":a<6E4?Math.ceil(a/10)/100+"s":Math.ceil(a/6E4*100)/100+"m"};b.formatNumber=function(a){a+="";var c=a.split(".");a=c[0];c=c.length>1?"."+c[1]:"";for(var e=/(\d+)(\d{3})/;e.test(a);)a=a.replace(e,"$1,$2");return a+c};b.formatString=
function(a){var c=b.cloneArray(arguments);a=c.shift();for(var e=0;e<c.length;e++){var f=c[e].toString();a=a.replace("%S",f)}return a};b.parseISO8601=function(a){return(a=b.fromISOString(a))?a.getTime():null};b.fromISOString=function(a){if(!a)return null;a=a.toString().match(new RegExp(/(\d\d\d\d)(-)?(\d\d)(-)?(\d\d)(T)?(\d\d)(:)?(\d\d)(:)?(\d\d)(\.\d+)?(Z|([+-])(\d\d)(:)?(\d\d))/));if(!a)return null;var c=new Date;c.setUTCDate(1);c.setUTCFullYear(parseInt(a[1],10));c.setUTCMonth(parseInt(a[3],10)-
1);c.setUTCDate(parseInt(a[5],10));c.setUTCHours(parseInt(a[7],10));c.setUTCMinutes(parseInt(a[9],10));c.setUTCSeconds(parseInt(a[11],10));a[12]?c.setUTCMilliseconds(parseFloat(a[12])*1E3):c.setUTCMilliseconds(0);if(a[13]!="Z"){var e=a[15]*60+parseInt(a[17],10);e*=a[14]=="-"?-1:1;c.setTime(c.getTime()-e*60*1E3)}return c};b.getFileName=function(a){return b.splitURLBase(a).name};b.getFileExtension=function(a){if(!a)return null;var c=a.indexOf("?");if(c!=-1)a=a.substr(0,c);c=a.lastIndexOf(".");return a.substr(c+
1)};b.splitURLBase=function(a){if(b.isDataURL(a))return b.splitDataURL(a);return b.splitURLTrue(a)};b.isDataURL=function(a){return a&&a.substr(0,5)=="data:"};b.splitDataURL=function(a){var c=a.indexOf(":",3);if(c!=4)return false;var e=a.indexOf(",",c+1);if(e<c)return false;var f={encodedContent:a.substr(e+1)};a=a.substr(c+1,e).split(";");for(c=0;c<a.length;c++){e=a[c].split("=");if(e.length==2)f[e[0]]=e[1]}if(f.hasOwnProperty("fileName")){a=decodeURIComponent(f.fileName);a=b.splitURLTrue(a);if(f.hasOwnProperty("baseLineNumber")){f.path=
a.path;f.line=f.baseLineNumber;a=decodeURIComponent(f.encodedContent.substr(0,200)).replace(/\s*$/,"");f.name="eval->"+a}else{f.name=a.name;f.path=a.path}}else{f.hasOwnProperty("path")||(f.path="data:");f.hasOwnProperty("name")||(f.name=decodeURIComponent(f.encodedContent.substr(0,200)).replace(/\s*$/,""))}return f};b.splitURLTrue=function(a){var c=/:\/{1,3}(.*?)\/([^\/]*?)\/?($|\?.*)/.exec(a);return c?c[2]?{path:c[1],name:c[2]+c[3]}:{path:c[1],name:c[1]}:{name:a,path:a}};b.getURLParameter=function(a){for(var c=
window.location.search.substring(1).split("&"),e=0;e<c.length;e++){var f=c[e].split("=");if(f[0]==a)return unescape(f[1])}return null};b.getURLParameters=function(a){for(var c=[],e=window.location.search.substring(1).split("&"),f=0;f<e.length;f++){var l=e[f].split("=");l[0]==a&&c.push(unescape(l[1]))}return c};b.parseURLParams=function(a){var c=a?a.indexOf("?"):-1;if(c==-1)return[];a=a.substr(c+1);c=a.lastIndexOf("#");if(c!=-1)a=a.substr(0,c);if(!a)return[];return b.parseURLEncodedText(a)};b.parseURLEncodedText=
function(a,c){function e(p){try{return decodeURIComponent(p)}catch(q){return decodeURIComponent(unescape(p))}}var f=[];if(a=="")return f;a=a.replace(/\+/g," ");a=a.split("&");for(var l=0;l<a.length;++l)try{var k=a[l].indexOf("=");if(k!=-1){var d=a[l].substring(0,k),g=a[l].substring(k+1);if(g.length>25E3&&!c)g=b.$STR("LargeData");f.push({name:e(d),value:e(g)})}else{d=a[l];f.push({name:e(d),value:""})}}catch(o){}f.sort(function(p,q){return p.name<=q.name?-1:1});return f};b.getBody=function(a){if(a.body)return a.body;
if(a=a.getElementsByTagName("body")[0])return a;return null};b.getHead=function(a){return a.getElementsByTagName("head")[0]};b.getAncestorByClass=function(a,c){for(a=a;a;a=a.parentNode)if(b.hasClass(a,c))return a;return null};b.$=function(){return b.getElementByClass.apply(this,arguments)};b.getElementByClass=function(a){if(!a)return null;var c=b.cloneArray(arguments);c.splice(0,1);for(var e=a.firstChild;e;e=e.nextSibling){var f=b.cloneArray(c);f.unshift(e);if(b.hasClass.apply(this,f))return e;else if(f=
b.getElementByClass.apply(this,f))return f}return null};b.getElementsByClass=function(a){function c(l,k,d){for(l=l.firstChild;l;l=l.nextSibling){var g=b.cloneArray(k);g.unshift(l);b.hasClass.apply(null,g)&&d.push(l);c(l,k,d)}}var e=[],f=b.cloneArray(arguments);f.shift();c(a,f,e);return e};b.getChildByClass=function(a){for(var c=1;c<arguments.length;++c){var e=arguments[c],f=a.firstChild;for(a=null;f;f=f.nextSibling)if(b.hasClass(f,e)){a=f;break}}return a};b.eraseNode=function(a){for(;a.lastChild;)a.removeChild(a.lastChild)};
b.clearNode=function(a){a.innerHTML=""};b.hasClass=function(a,c){if(!a||a.nodeType!=1)return false;else{for(var e=1;e<arguments.length;++e){c=arguments[e];var f=a.className;if(!f||f.indexOf(c+" ")==-1)return false}return true}};b.setClass=function(a,c){if(a&&!b.hasClass(a,c))a.className+=" "+c+" "};b.removeClass=function(a,c){if(a&&a.className){var e=a.className.indexOf(c);if(e>=0){c=c.length;a.className=a.className.substr(0,e-1)+a.className.substr(e+c)}}};b.toggleClass=function(a,c){if(b.hasClass(a,
c)){b.removeClass(a,c);return false}else{b.setClass(a,c);return true}};b.trim=function(a){return a.replace(/^\s*|\s*$/g,"")};b.wrapText=function(a,c){var e=/[^A-Za-z_$0-9'"-]/,f=[];a=b.splitLines(a);for(var l=0;l<a.length;++l){for(var k=a[l];k.length>100;){var d=e.exec(k.substr(100,100));d=100+(d?d.index:0);var g=k.substr(0,d);k=k.substr(d);c||f.push("<pre>");f.push(c?g:b.escapeHTML(g));c||f.push("</pre>")}c||f.push("<pre>");f.push(c?k:b.escapeHTML(k));c||f.push("</pre>")}return f.join(c?"\n":"")};
b.insertWrappedText=function(a,c,e){c.innerHTML="<pre>"+b.wrapText(a,e)+"</pre>"};b.splitLines=function(a){var c=/\r\n|\r|\n/;if(a){if(a.split)return a.split(c)}else return[];return(a+"").split(c)};b.getPrettyDomain=function(a){return(a=/[^:]+:\/{1,3}(www\.)?([^\/]+)/.exec(a))?a[2]:""};b.escapeHTML=function(a){function c(e){switch(e){case "<":return"&lt;";case ">":return"&gt;";case "&":return"&amp;";case "'":return"&#39;";case '"':return"&quot;"}return"?"}return String(a).replace(/[<>&"']/g,c)};b.cropString=
function(a,c){a+="";var e=c?c/2:50;return a.length>c?b.escapeNewLines(a.substr(0,e)+"..."+a.substr(a.length-e)):b.escapeNewLines(a)};b.escapeNewLines=function(a){return a.replace(/\r/g,"\\r").replace(/\n/g,"\\n")};b.cloneJSON=function(a){if(a==null||typeof a!="object")return a;try{var c=a.constructor();for(var e in a)c[e]=cloneJSON(a[e]);return c}catch(f){n.exception(a)}return null};b.getOverflowParent=function(a){for(a=a.parentNode;a;a=a.offsetParent)if(a.scrollHeight>a.offsetHeight)return a};b.getElementBox=
function(a){var c={};if(a.getBoundingClientRect){a=a.getBoundingClientRect();var e=b.isIE?document.body.clientTop||document.documentElement.clientTop:0,f=b.getWindowScrollPosition();c.top=Math.round(a.top-e+f.top);c.left=Math.round(a.left-e+f.left);c.height=Math.round(a.bottom-a.top);c.width=Math.round(a.right-a.left)}else{e=b.getElementPosition(a);c.top=e.top;c.left=e.left;c.height=a.offsetHeight;c.width=a.offsetWidth}return c};b.getElementPosition=function(a){var c=0,e=0;do{c+=a.offsetLeft;e+=a.offsetTop}while(a=
a.offsetParent);return{left:c,top:e}};b.getWindowSize=function(){var a=0,c=0,e;if(typeof window.innerWidth=="number"){a=window.innerWidth;c=window.innerHeight}else if((e=document.documentElement)&&(e.clientHeight||e.clientWidth)){a=e.clientWidth;c=e.clientHeight}else if((e=document.body)&&(e.clientHeight||e.clientWidth)){a=e.clientWidth;c=e.clientHeight}return{width:a,height:c}};b.getWindowScrollSize=function(){var a=0,c=0,e;if(!b.isIEQuiksMode&&(e=document.documentElement)&&(e.scrollHeight||e.scrollWidth)){a=
e.scrollWidth;c=e.scrollHeight}if((e=document.body)&&(e.scrollHeight||e.scrollWidth)&&(e.scrollWidth>a||e.scrollHeight>c)){a=e.scrollWidth;c=e.scrollHeight}return{width:a,height:c}};b.getWindowScrollPosition=function(){var a=0,c=0,e;if(typeof window.pageYOffset=="number"){a=window.pageYOffset;c=window.pageXOffset}else if((e=document.body)&&(e.scrollTop||e.scrollLeft)){a=e.scrollTop;c=e.scrollLeft}else if((e=document.documentElement)&&(e.scrollTop||e.scrollLeft)){a=e.scrollTop;c=e.scrollLeft}return{top:a,
left:c}};b.addStyleSheet=function(a,c){if(!a.getElementById(c)){var e=a.createElement("link");e.type="text/css";e.rel="stylesheet";e.href=c;e.setAttribute("id",c);b.getHead(a).appendChild(e)}};return b});
require.def("i18n!nls/requestList",{root:{fromCache:"From Cache",menuBreakLayout:"Break Timeline Layout",menuOpenRequestInWindow:"Open Request in New Window",menuOpenResponseInWindow:"Open Response in New Window",request:"Request",requests:"Requests",tooltipSize:"%S (%S bytes)",tooltipZippedSize:"%S (%S bytes) - compressed",tooltipUnzippedSize:"%S (%S bytes) - uncompressed","request.Started":"Started","request.phase.Resolving":"DNS Lookup","request.phase.Connecting":"Connecting","request.phase.Blocking":"Blocking",
"request.phase.Sending":"Sending","request.phase.Waiting":"Waiting","request.phase.Receiving":"Receiving",ContentLoad:"DOM Loaded",WindowLoad:"Page Loaded","page.event.Load":"Page Loaded",menuBreakTimeline:"Break Timeline Layout",menuOpenRequest:"Open Request in New Window",menuOpenResponse:"Open Response in New Window"}});
require.def("preview/requestList",["domplate/domplate","core/lib","i18n!nls/requestList","preview/harModel","core/cookies","preview/requestBody","domplate/infoTip","domplate/popupMenu"],function(n,b,h,m,j,a,c,e){with(n){n=function(d){this.input=d;c.addListener(this)};n.prototype=domplate({tableTag:TABLE({"class":"netTable",cellpadding:0,cellspacing:0,onclick:"$onClick"},TBODY(TR(TD({width:"20%"}),TD({width:"10%"}),TD({width:"10%"}),TD({width:"10%"}),TD({width:"50%"}),TD({width:"15px"})))),fileTag:FOR("file",
"$files",TR({"class":"netRow loaded",$hasHeaders:"$file|hasResponseHeaders",$responseError:"$file|isError",$fromCache:"$file|isFromCache"},TD({"class":"netHrefCol netCol"},DIV({"class":"netHrefLabel netLabel",style:"margin-left: $file|getIndent\\px"},"$file|getHref"),DIV({"class":"netFullHrefLabel netHrefLabel netLabel",style:"margin-left: $file|getIndent\\px"},"$file|getFullHref")),TD({"class":"netStatusCol netCol"},DIV({"class":"netStatusLabel netLabel"},"$file|getStatus")),TD({"class":"netDomainCol netCol"},
DIV({"class":"netDomainLabel netLabel"},"$file|getDomain")),TD({"class":"netSizeCol netCol"},DIV({"class":"netSizeLabel netLabel"},"$file|getSize")),TD({"class":"netTimeCol netCol"},DIV({"class":"netTimelineBar"},"&nbsp;",DIV({"class":"netResolvingBar netBar",style:"left: $file.offset"}),DIV({"class":"netConnectingBar netBar",style:"left: $file.offset"}),DIV({"class":"netBlockingBar netBar",style:"left: $file.offset"}),DIV({"class":"netSendingBar netBar",style:"left: $file.offset"}),DIV({"class":"netWaitingBar netBar",
style:"left: $file.offset"}),DIV({"class":"netContentLoadBar netBar",style:"left: $file.offset"}),DIV({"class":"netWindowLoadBar netBar",style:"left: $file.offset"}),DIV({"class":"netReceivingBar netBar",style:"left: $file.offset; width: $file.width"},SPAN({"class":"netTimeLabel"},"$file|getElapsedTime")))),TD({"class":"netOptionsCol netCol"},DIV({"class":"netOptionsLabel netLabel",onclick:"$onOpenOptions"})))),headTag:TR({"class":"netHeadRow"},TD({"class":"netHeadCol",colspan:6},DIV({"class":"netHeadLabel"},
"$doc.rootFile.href"))),netInfoTag:TR({"class":"netInfoRow"},TD({"class":"netInfoCol",colspan:6})),summaryTag:TR({"class":"netRow netSummaryRow"},TD({"class":"netCol",colspan:3},DIV({"class":"netCountLabel netSummaryLabel"},"-")),TD({"class":"netTotalSizeCol netCol"},DIV({"class":"netTotalSizeLabel netSummaryLabel"},"0KB")),TD({"class":"netTotalTimeCol netCol"},DIV({"class":"",style:"width: 100%"},DIV({"class":"netCacheSizeLabel netSummaryLabel"},"(",SPAN("0KB"),SPAN(" "+h.fromCache),")"),DIV({"class":"netTimeBar"},
SPAN({"class":"netTotalTimeLabel netSummaryLabel"},"0ms")))),TD({"class":"netCol"})),getIndent:function(){return 0},isError:function(d){d=Math.floor(d.response.status/100);return d==4||d==5},isFromCache:function(d){return d.cache&&d.cache.afterRequest},getHref:function(d){return d.request.method+" "+b.getFileName(this.getFullHref(d))},getFullHref:function(d){return d.request.url},getStatus:function(d){return(d.response.status>0?d.response.status+" ":"")+d.response.statusText},getDomain:function(d){return b.getPrettyDomain(d.request.url)},
getSize:function(d){var g=d.response.bodySize;return this.formatSize(g&&g!=-1?g:d.response.content.size)},hasResponseHeaders:function(){return true},formatSize:function(d){return b.formatSize(d)},getElapsedTime:function(d){return b.formatTime(d.time)},onClick:function(d){var g=$.event.fix(d||window.event);if(b.isLeftClick(d))if(g=b.getAncestorByClass(g.target,"netRow")){this.toggleHeadersRow(g);b.cancelEvent(d)}},toggleHeadersRow:function(d){if(b.hasClass(d,"hasHeaders")){var g=d.repObject;b.toggleClass(d,
"opened");if(b.hasClass(d,"opened")){var o=this.netInfoTag.insertRows({},d)[0];o.repObject=g;(new a).render(o.firstChild,g)}else{o=d.nextSibling;b.getElementByClass(o,"netInfoBody");d.parentNode.removeChild(o)}}},onOpenOptions:function(d){var g=$.event.fix(d||window.event);b.cancelEvent(d);if(b.isLeftClick(d)){d=g.target;g=this.getOptionsMenuItems(b.getAncestorByClass(d,"netRow"));(new e({id:"requestContextMenu",items:g})).showPopup(d)}},getOptionsMenuItems:function(d){var g=d.repObject;return[{label:h.menuBreakTimeline,
type:"checkbox",disabled:false,checked:d.phase.files[0]==g,command:b.bind(this.breakLayout,this,d)},"-",{label:h.menuOpenRequest,command:b.bind(this.openRequest,this,g)},{label:h.menuOpenResponse,disabled:!g.response.content.text,command:b.bind(this.openResponse,this,g)}]},openRequest:function(d,g){window.open(g.request.url)},openResponse:function(d,g){d=g.response.content.mimeType;var o=g.response.content.encoding;window.open("data:"+(d?d:"")+";"+(o?o:"")+","+g.response.content.text)},breakLayout:function(d,
g){d=g.repObject;g.breakLayout=g.phase.files[0]!=d;g=b.getAncestorByClass(g,"netTable");d=m.getParentPage(this.input,d);this.updateLayout(g,d)},updateLayout:function(d,g){var o=m.getPageEntries(this.input,g);this.table=d;d=this.firstRow=this.table.firstChild.firstChild.nextSibling;this.phases=[];var p=j.getCookie("phaseInterval");p||(p=1E3);var q=null,t=g?b.parseISO8601(g.startedDateTime):null,s=0,r=0;if(g&&g.pageTimings){r=g.pageTimings;s=r.onLoad>0?r.onLoad:0;r=r.onContentLoad>0?r.onContentLoad:
0}for(var v=0;v<o.length;v++){var u=o[v];if(b.hasClass(d,"netInfoRow"))d=d.nextSibling;d.repObject=u;t||(t=b.parseISO8601(u.startedDateTime));var x=b.parseISO8601(u.startedDateTime),w=q?b.parseISO8601(q.getLastStartTime()):0;w=x-w>=p&&x>t+s;if(typeof d.breakLayout=="boolean")if(!q||d.breakLayout)q=this.startPhase(u);else q.addFile(u);else if(!q||w)q=this.startPhase(u);else q.addFile(u);if(q.startTime==undefined||q.startTime>x)q.startTime=x;if(q.endTime==undefined||q.endTime<x+u.time)q.endTime=x+u.time;
if(u.phase==this.phases[0]&&q.endTime<t+s)q.endTime=t+s;if(u.phase==this.phases[0]&&q.endTime<t+r)q.endTime=t+r;d=d.nextSibling}this.updateTimeline(g);this.updateSummaries(g)},startPhase:function(d){d=new f(d);this.phases.push(d);return d},calculateFileTimes:function(d,g,o){if(o!=g.phase){o=g.phase;this.phaseStartTime=o.startTime;this.phaseEndTime=o.endTime;this.phaseElapsed=this.phaseEndTime-o.startTime}var p=g.timings.dns<0?0:g.timings.dns,q=p+(g.timings.connect<0?0:g.timings.connect),t=q+(g.timings.blocked<
0?0:g.timings.blocked),s=t+(g.timings.send<0?0:g.timings.send),r=s+(g.timings.wait<0?0:g.timings.wait),v=r+(g.timings.receive<0?0:g.timings.receive);this.barOffset=((b.parseISO8601(g.startedDateTime)-this.phaseStartTime)/this.phaseElapsed*100).toFixed(3);this.barResolvingWidth=(p/this.phaseElapsed*100).toFixed(3);this.barConnectingWidth=(q/this.phaseElapsed*100).toFixed(3);this.barBlockingWidth=(t/this.phaseElapsed*100).toFixed(3);this.barSendingWidth=(s/this.phaseElapsed*100).toFixed(3);this.barWaitingWidth=
(r/this.phaseElapsed*100).toFixed(3);this.barReceivingWidth=(v/this.phaseElapsed*100).toFixed(3);if(d){p=b.parseISO8601(d.startedDateTime);q=d.pageTimings.onContentLoad;if(g.phase==this.phases[0]&&q>0)this.contentLoadBarOffset=((p+q-o.startTime)/this.phaseElapsed*100).toFixed(3);d=d.pageTimings.onLoad;if(g.phase==this.phases[0]&&d>0)this.windowLoadBarOffset=((p+d-o.startTime)/this.phaseElapsed*100).toFixed(3)}return o},updateTimeline:function(d){for(var g,o=this.firstRow;o;o=o.nextSibling){var p=
o.repObject;if(p)if(!b.hasClass(o,"netInfoRow")){g=this.calculateFileTimes(d,p,g);o.phase=p.phase;delete p.phase;p=b.getElementByClass(o,"netResolvingBar");var q=p.nextSibling,t=q.nextSibling,s=t.nextSibling,r=s.nextSibling,v=r.nextSibling,u=v.nextSibling,x=u.nextSibling;p.style.left=q.style.left=t.style.left=s.style.left=r.style.left=x.style.left=this.barOffset+"%";p.style.width=this.barResolvingWidth+"%";q.style.width=this.barConnectingWidth+"%";t.style.width=this.barBlockingWidth+"%";s.style.width=
this.barSendingWidth+"%";r.style.width=this.barWaitingWidth+"%";x.style.width=this.barReceivingWidth+"%";if(this.contentLoadBarOffset){v.style.left=this.contentLoadBarOffset+"%";v.style.display="block";this.contentLoadBarOffset=null}if(this.windowLoadBarOffset){u.style.left=this.windowLoadBarOffset+"%";u.style.display="block";this.windowLoadBarOffset=null}}}},updateSummaries:function(d){for(var g=this.phases,o=0,p=0,q=0,t=0,s=0;s<g.length;++s){var r=g[s];r.invalidPhase=false;r=this.summarizePhase(r);
o+=r.fileCount;p+=r.totalSize;q+=r.cachedSize;t+=r.totalTime}if(g=this.summaryRow){b.getElementByClass(g,"netCountLabel").firstChild.nodeValue=this.formatRequestCount(o);o=b.getElementByClass(g,"netTotalSizeLabel");o.setAttribute("totalSize",p);o.firstChild.nodeValue=b.formatSize(p);p=b.getElementByClass(g,"netCacheSizeLabel");p.setAttribute("collapsed",q==0);p.childNodes[1].firstChild.nodeValue=b.formatSize(q);q=b.getElementByClass(g,"netTotalTimeLabel");t=b.formatTime(t);if(d&&d.pageTimings.onLoad>
0)t+=" (onload: "+b.formatTime(d.pageTimings.onLoad)+")";q.innerHTML=t}},formatRequestCount:function(d){return d+" "+(d==1?h.request:h.requests)},summarizePhase:function(d){var g=0,o=0,p="all";if(p=="all")p=null;for(var q=0,t=0,s=0,r=0;r<d.files.length;r++){var v=d.files[r],u=b.parseISO8601(v.startedDateTime);if(!p||v.category==p){++q;var x=v.response.bodySize;x=x&&x!=-1?x:v.response.content.size;o+=x;if(v.response.status==304)g+=x;if(!t||u<t)t=u;v=u+v.time;if(v>s)s=v}}return{cachedSize:g,totalSize:o,
totalTime:s-t,fileCount:q}},showInfoTip:function(d,g){var o=b.getAncestorByClass(g,"netRow");if(o)if(b.getAncestorByClass(g,"netBar")){d.setAttribute("multiline",true);this.infoTipURL=g=o.repObject.startedDateTime+"-nettime";return this.populateTimeInfoTip(d,o)}else if(b.hasClass(g,"netSizeLabel")){this.infoTipURL=g=o.repObject.startedDateTime+"-netsize";return this.populateSizeInfoTip(d,o)}},populateTimeInfoTip:function(d,g){l.render(this.input,g,d);return true},populateSizeInfoTip:function(d,g){k.render(this.input,
g,d);return true},render:function(d,g){var o=m.getPageEntries(this.input,g);if(o.length){this.table=this.tableTag.replace({},d,this);this.summaryRow=this.summaryTag.insertRows({},this.table.firstChild)[0];this.fileTag.insertRows({files:o},this.table.firstChild.lastChild.previousSibling,this);this.updateLayout(this.table,g)}}});var f=function(d){this.files=[];this.addFile(d)};f.prototype={addFile:function(d){this.files.push(d);d.phase=this},getLastStartTime:function(){return this.files[this.files.length-
1].startedDateTime}};var l=domplate({tableTag:TABLE({"class":"timeInfoTip"},TBODY()),timingsTag:FOR("time","$timings",TR({"class":"timeInfoTipRow",$collapsed:"$time|hideBar"},TD({"class":"$time|getBarClass timeInfoTipBar",$loaded:"$time.loaded",$fromCache:"$time.fromCache"}),TD({"class":"timeInfoTipCell startTime"},"$time.start|formatStartTime"),TD({"class":"timeInfoTipCell elapsedTime"},"$time.elapsed|formatTime"),TD("$time|getLabel"))),startTimeTag:TR(TD(),TD("$startTime.time|formatStartTime"),
TD({colspan:2},"$startTime|getLabel")),separatorTag:TR(TD({colspan:4,height:"10px"})),eventsTag:FOR("event","$events",TR({"class":"timeInfoTipEventRow"},TD({"class":"timeInfoTipBar",align:"center"},DIV({"class":"$event|getBarClass timeInfoTipEventBar"})),TD("$event.start|formatStartTime"),TD({colspan:2},"$event|getLabel"))),hideBar:function(d){return!d.elapsed&&d.bar=="request.phase.Blocking"},getBarClass:function(d){return"net"+d.bar.substr(d.bar.lastIndexOf(".")+1)+"Bar"},formatTime:function(d){return b.formatTime(d)},
formatStartTime:function(d){var g=d>0,o=b.formatTime(Math.abs(d));if(!d)return o;return(g>0?"+":"-")+o},getLabel:function(d){return h[d.bar]},render:function(d,g,o){var p=g.repObject;var q=(d=m.getParentPage(d,p))?b.parseISO8601(d.startedDateTime):null,t=b.parseISO8601(p.startedDateTime);o=l.tableTag.replace({},o);var s={};s.time=t-g.phase.startTime;s.bar="request.Started";this.startTimeTag.insertRows({startTime:s},o.firstChild);this.separatorTag.insertRows({},o.firstChild);g=0;s=[];var r=p.timings.dns,
v=p.timings.connect,u=p.timings.blocked,x=p.timings.send,w=p.timings.wait,y=p.timings.receive;r>=0&&s.push({bar:"request.phase.Resolving",elapsed:r,start:g});if(v>=0)s.push({bar:"request.phase.Connecting",elapsed:v,start:g+=r<0?0:r});if(u>=0)s.push({bar:"request.phase.Blocking",elapsed:u,start:g+=v<0?0:v});if(x>=0)s.push({bar:"request.phase.Sending",elapsed:x,start:g+=u<0?0:u});if(w>=0)s.push({bar:"request.phase.Waiting",elapsed:w,start:g+=x<0?0:x});if(y>=0)s.push({bar:"request.phase.Receiving",elapsed:y,
start:g+(w<0?0:w),loaded:p.loaded,fromCache:p.fromCache});this.timingsTag.insertRows({timings:s},o.firstChild);p=[];d&&d.pageTimings.onContentLoad>0&&p.push({bar:"ContentLoad",start:q+d.pageTimings.onContentLoad-t});d&&d.pageTimings.onLoad>0&&p.push({bar:"WindowLoad",start:q+d.pageTimings.onLoad-t});if(p.length){this.separatorTag.insertRows({},o.firstChild);this.eventsTag.insertRows({events:p},o.firstChild);return true}}}),k=domplate({tag:DIV({"class":"sizeInfoTip"},"$file|getSize"),zippedTag:DIV(DIV({"class":"sizeInfoTip"},
"$file|getBodySize"),DIV({"class":"sizeInfoTip"},"$file|getContentSize")),getSize:function(d){d=d.response.bodySize;return b.formatString(h.tooltipSize,[b.formatSize(d),d.size<0?"?":b.formatNumber(d)])},getBodySize:function(d){d=d.response.bodySize;return b.formatString(h.tooltipZippedSize,[b.formatSize(d),d.size<0?"?":b.formatNumber(d)])},getContentSize:function(d){d=d.response.content.size;return b.formatString(h.tooltipUnzippedSize,[b.formatSize(d),d.size<0?"?":b.formatNumber(d)])},render:function(d,
g,o){d=g.repObject;if(d.response.bodySize==d.response.content.size)return this.tag.replace({file:d},o);return this.zippedTag.replace({file:d},o)}});return n}});
require.def("preview/jsonSchema",[],function(){return{validate:function(n,b){return this._validate(n,b,false)},checkPropertyChange:function(n,b,h){return this._validate(n,b,h||"property")},_validate:function(n,b,h){function m(c,e,f,l){function k(q){a.push({property:f,message:q})}function d(q,t){if(q){if(typeof q=="string"&&q!="any"&&(q=="null"?t!==null:typeof t!=q)&&!(t instanceof Array&&q=="array")&&!(q=="integer"&&t%1===0))return[{property:f,message:typeof t+" value found, but a "+q+" is required"}];
if(q instanceof Array){for(var s=[],r=0;r<q.length;r++)if(!(s=d(q[r],t)).length)break;if(s.length)return s}else if(typeof q=="object"){s=a;a=[];m(t,q,f);q=a;a=s;return q}}return[]}var g;f+=f?typeof l=="number"?"["+l+"]":typeof l=="undefined"?"":"."+l:l;if((typeof e!="object"||e instanceof Array)&&(f||typeof e!="function")){if(typeof e=="function")c instanceof e||k("is not an instance of the class/constructor "+e.name);else e&&k("Invalid schema/property definition "+e);return null}h&&e.readonly&&k("is a readonly field, it can not be changed");
e["extends"]&&m(c,e["extends"],f,l);if(c===undefined)e.optional||k("is missing and it is not optional");else{a=a.concat(d(e.type,c));e.disallow&&!d(e.disallow,c).length&&k(" disallowed value was matched");if(c!==null){if(c instanceof Array){if(e.items)if(e.items instanceof Array){l=0;for(g=c.length;l<g;l++)a.concat(m(c[l],e.items[l],f,l))}else{l=0;for(g=c.length;l<g;l++)a.concat(m(c[l],e.items,f,l))}e.minItems&&c.length<e.minItems&&k("There must be a minimum of "+e.minItems+" in the array");e.maxItems&&
c.length>e.maxItems&&k("There must be a maximum of "+e.maxItems+" in the array")}else e.properties&&a.concat(j(c,e.properties,f,e.additionalProperties));e.pattern&&typeof c=="string"&&!c.match(e.pattern)&&k("does not match the regex pattern "+e.pattern);e.maxLength&&typeof c=="string"&&c.length>e.maxLength&&k("may only be "+e.maxLength+" characters long");e.minLength&&typeof c=="string"&&c.length<e.minLength&&k("must be at least "+e.minLength+" characters long");typeof e.minimum!==undefined&&typeof c==
typeof e.minimum&&e.minimum>c&&k("must have a minimum value of "+e.minimum);typeof e.maximum!==undefined&&typeof c==typeof e.maximum&&e.maximum<c&&k("must have a maximum value of "+e.maximum);if(e["enum"]){l=e["enum"];g=l.length;for(var o,p=0;p<g;p++)if(l[p]===c){o=1;break}o||k("does not have a value in the enumeration "+l.join(", "))}typeof e.maxDecimal=="number"&&c.toString().match(new RegExp("\\.[0-9]{"+(e.maxDecimal+1)+",}"))&&k("may only have "+e.maxDecimal+" digits of decimal places")}}return null}
function j(c,e,f,l){if(typeof e=="object"){if(typeof c!="object"||c instanceof Array)a.push({property:f,message:"an object is required"});for(var k in e)if(e.hasOwnProperty(k)&&!(k.charAt(0)=="_"&&k.charAt(1)=="_")){var d=c[k];m(d,e[k],f,k)}}for(k in c){c.hasOwnProperty(k)&&!(k.charAt(0)=="_"&&k.charAt(1)=="_")&&e&&!e[k]&&l===false&&a.push({property:f,message:typeof d+"The property "+k+" is not defined in the schema and the schema does not allow additional properties"});(d=e&&e[k]&&e[k].requires)&&
!(d in c)&&a.push({property:f,message:"the presence of the property "+k+" requires that "+d+" also be present"});d=c[k];e&&typeof e=="object"&&!(k in e)&&m(d,l,f,k);if(!h&&d&&d.$schema)a=a.concat(m(d,d.$schema,f,k))}return a}var a=[];if(b)m(n,b,"",h||"");!h&&n&&n.$schema&&m(n,n.$schema,"","");return{valid:!a.length,errors:a}}}});
require.def("preview/harModel",["core/lib","preview/jsonSchema","preview/ref","preview/harSchema","core/cookies","core/trace","jquery-plugins/jquery.json"],function(n,b,h,m,j,a){function c(){this.input=null}function e(){var f={};for(var l in this)if(l!="toJSON")f[l]=this[l];if(!this.text)return f;f.text=Array.map(this.text,function(k){var d=k.charCodeAt(0);if(d>=32&&d<127||d==10||d==13)return k.charAt(0);for(k=d.toString(16).toUpperCase();k.length<4;)k="0"+k;return"\\u"+k}).join("");return f}c.prototype=
{append:function(f){if(f){if(this.input)if(f.log.pages)for(var l=0;l<f.log.pages.length;l++)this.importPage(f.log.pages[l],f.log.entries);else{a.error("Import of additional data without a page is not yet supported.");return null}else this.input=f;return this.input}else a.error("HarModel.append; Trying to append null input!")},getPages:function(){if(!this.input)return[];return this.input.log.pages?this.input.log.pages:[]},getFirstPage:function(){var f=this.getPages();return f.length>0?f[0]:null},getPageEntries:function(f){return c.getPageEntries(this.input,
f)},getAllEntries:function(){return this.input?this.input.log.entries:[]},getParentPage:function(f){return c.getParentPage(this.input,f)},importPage:function(f,l){var k=this.getUniquePageID(f.id),d=f.id;f.id=k;this.input.log.pages.push(f);for(f=0;f<l.length;f++){var g=l[f];if(g.pageref==d){g.pageref=k;this.input.log.entries.push(g)}}},getUniquePageID:function(f){for(var l=this.input.log.pages,k={},d=0;d<l.length;d++)k[l[d].id]=true;if(!k[f])return f;for(l=1;;){d=f+l;if(!k[d])return d;l++}},toJSON:function(f){if(!f)f=
this.input;if(!f)return"";f=this.input.log.entries;for(var l=0;l<f.length;l++){var k=f[l];if(k.response.content.text)k.response.content.toJSON=e}return $.jSONToString(this.input,null,"\t").replace(/\\\\u/g,"\\u")},getSize:function(f){if(!f)f=this.input;if(!f)return 0;return dojo.toJson(f,true).length}};c.parse=function(f,l){var k=f;try{if(typeof f==="string")k=jQuery.toJSON(f)}catch(d){console.exception("HarModel.parse; EXCEPTION",d);throw{errors:[{message:"Failed to parse JSON",property:"JSON evaluation"}]};
}if(!l)return k;f=h.resolveJson(m);f=b.validate(k,f.logType);if(f.valid)return k;throw f;};c.getPageEntries=function(f,l){var k=[];f=f.log.entries;if(!f)return k;for(var d=0;d<f.length;d++){var g=f[d];!g.pageref&&!l&&k.push(g);l&&g.pageref==l.id&&k.push(g)}return k};c.getParentPage=function(f,l){f=f.log.pages;if(!f)return null;for(var k=0;k<f.length;k++)if(f[k].id==l.pageref)return f[k];return null};c.Loader={run:function(f,l){var k=n.getURLParameter("baseUrl");if(k&&k[k.length-1]!="/")k+="/";var d=
n.getURLParameters("path"),g=n.getURLParameter("callback"),o=n.getURLParameter("inputUrl"),p=[];for(var q in d)p.push(k?k+d[q]:d[q]);o&&p.push(o);if((k||o)&&p.length>0)return this.loadRemoteArchive(p,g,f,l);if(k=n.getURLParameter("path"))return this.loadLocalArchive(k,f,l)},loadExample:function(f){var l=document.location.href,k=l.indexOf("?");document.location=l.substr(0,k)+"?path="+f;j.setCookie("timeline",true);j.setCookie("stats",true)},loadLocalArchive:function(f,l,k){$.ajax({url:f,context:this,
success:function(d){l(d)},error:function(d,g){k(d,g)}});return true},loadRemoteArchive:function(f,l,k,d){if(!f.length)return false;var g=f.shift();l||(l="onInputData");$.ajax({url:g,context:this,dataType:"jsonp",jsonp:"callback",jsonpCallback:l,success:function(o){k(o);if(f.length){var p=this;setTimeout(function(){p.loadRemoteArchive(f,l,k,d)},300)}},error:function(o,p){d(o,p)}});return true}};return c});
require.def("preview/ref",["core/lib"],function(n){return{resolveJson:function(b,h){function m(p,q,t,s,r){var v,u;t=j in p?p[j]:t;if(t!==undefined)t=(a+t).replace(d,"$2$3");r=r||p;if(t!==undefined){if(c)p.__id=t;if(h.schemas&&!(p instanceof Array)&&(u=t.match(/^(.+\/)[^\.\[]*$/)))s=h.schemas[u[1]];if(e[t]&&p instanceof Array==e[t]instanceof Array){r=e[t];delete r.$ref;v=true}else if(u=s&&s.prototype){o.prototype=u;r=new o}e[t]=r;if(f)f[t]=h.time}s=s&&s.properties;var x=p.length;for(var w in p){if(w==
x)break;if(p.hasOwnProperty(w)){u=p[w];var y=s&&s[w];if(y&&y.format=="date-time"&&typeof u=="string")u=n.fromISOString(u);else if(typeof u=="object"&&u&&!(u instanceof Date))if(l=u.$ref){delete p[w];var z=l.replace(/(#)([^\.\[])/,"$1.$2").match(/(^([^\[]*\/)?[^#\.\[]*)#?([\.\[].*)?/);if(l=z[1]=="$"||z[1]=="this"||z[1]==""?b:e[(a+z[1]).replace(d,"$2$3")])z[3]&&z[3].replace(/(\[([^\]]+)\])|(\.?([^\.\[]+))/g,function(E,F,B,G,D){l=l&&l[B?B.replace(/[\"\'\\]/,""):D]});if(l)u=l;else if(q){u=m(u,false,u.$ref,
y);u._loadObject=h.loader}else{var C;C||k.push(r);C=true}}else q||(u=m(u,k==p,t&&g(t,w),y,r!=p&&typeof r[w]=="object"&&r[w]));p[w]=u;if(r!=p&&!r.__isDirty){y=r[w];r[w]=u;v&&u!==y&&!r._loadObject&&!(u instanceof Date&&y instanceof Date&&u.getTime()==y.getTime())&&!(typeof u=="function"&&typeof y=="function"&&u.toString()==y.toString())&&e.onUpdate&&e.onUpdate(r,w,y,u)}}}if(v)for(w in r){if(!r.__isDirty&&r.hasOwnProperty(w)&&!p.hasOwnProperty(w)&&w!="__id"&&w!="__clientId"&&!(r instanceof Array&&isNaN(w))){e.onUpdate&&
w!="_loadObject"&&w!="_idAttr"&&e.onUpdate(r,w,r[w],undefined);for(delete r[w];r instanceof Array&&r.length&&r[r.length-1]===undefined;)r.length--}}else e.onLoad&&e.onLoad(r);return r}h=h||{};var j=h.idAttribute||"id",a=h.idPrefix||"",c=h.assignAbsoluteIds,e=h.index||{},f=h.timeStamps,l,k=[],d=/^(.*\/)?(\w+:\/\/)|[^\/\.]+\/\.\.\/|^.*\/(\/)/,g=this._addProp,o=function(){};if(b&&typeof b=="object"){b=m(b,false,h.defaultId);m(k,false)}return b},_addProp:function(b,h){return b+(b.match(/#/)?b.length==
1?"":".":"#")+h}}});
require.def("preview/harSchema",[],function(){function n(){}var b=/^(\d{4})(-)?(\d\d)(-)?(\d\d)(T)?(\d\d)(:)?(\d\d)(:)?(\d\d)(\.\d+)?(Z|([+-])(\d\d)(:)?(\d\d))/,h={pageType:{id:"pageType",description:"Exported web page",optional:true,properties:{startedDateTime:{type:"string",format:"date-time",pattern:b},id:{type:"string",unique:true},title:{type:"string"},pageTimings:{$ref:"pageTimingsType"},comment:{type:"string",optional:true}}}};b={entryType:{id:"entryType",description:"Request and Response related info",optional:true,
properties:{pageref:{type:"string",optional:true},startedDateTime:{type:"string",format:"date-time",pattern:b},time:{type:"integer",min:0},request:{$ref:"requestType"},response:{$ref:"responseType"},cache:{$ref:"cacheType"},timings:{$ref:"timingsType"},serverIPAddress:{type:"string",optional:true},connection:{type:"string",optional:true},comment:{type:"string",optional:true}}}};n.prototype={registerType:function(){var j=function(a,c){for(name in c)if(c.hasOwnProperty(name)&&name!="prototype")a[name]=
c[name]};for(i=0;i<arguments.length;i+=1)j(this,arguments[i])}};var m=new n;m.registerType({logType:{id:"logType",description:"HTTP Archive structure.",type:"object",properties:{log:{type:"object",properties:{version:{type:"string"},creator:{$ref:"creatorType"},browser:{$ref:"browserType"},pages:{type:"array",optional:true,items:{$ref:"pageType"}},entries:{type:"array",items:{$ref:"entryType"}},comment:{type:"string",optional:true}}}}}},{creatorType:{id:"creatorType",description:"Name and version info of the log creator app.",
type:"object",properties:{name:{type:"string"},version:{type:"string"},comment:{type:"string",optional:true}}}},{browserType:{id:"browserType",description:"Name and version info of used browser.",type:"object",optional:true,properties:{name:{type:"string"},version:{type:"string"},comment:{type:"string",optional:true}}}},h,{pageTimingsType:{id:"pageTimingsType",description:"Timing info about page load",properties:{onContentLoad:{type:"number",optional:true,min:-1},onLoad:{type:"number",optional:true,
min:-1},comment:{type:"string",optional:true}}}},b,{requestType:{id:"requestType",description:"Monitored request",properties:{method:{type:"string"},url:{type:"string"},httpVersion:{type:"string"},cookies:{type:"array",items:{$ref:"cookieType"}},headers:{type:"array",items:{$ref:"recordType"}},queryString:{type:"array",items:{$ref:"recordType"}},postData:{$ref:"postDataType"},headersSize:{type:"integer"},bodySize:{type:"integer"},comment:{type:"string",optional:true}}}},{recordType:{id:"recordType",
description:"Helper name-value pair structure.",properties:{name:{type:"string"},value:{type:"string"},comment:{type:"string",optional:true}}}},{responseType:{id:"responseType",description:"Monitored Response.",properties:{status:{type:"integer"},statusText:{type:"string"},httpVersion:{type:"string"},cookies:{type:"array",items:{$ref:"cookieType"}},headers:{type:"array",items:{$ref:"recordType"}},content:{$ref:"contentType"},redirectURL:{type:"string"},headersSize:{type:"integer"},bodySize:{type:"integer"},
comment:{type:"string",optional:true}}}},{postDataType:{id:"postDataType",description:"Posted data info.",optional:true,properties:{mimeType:{type:"string"},text:{type:"string",optional:true},params:{type:"array",optional:true,properties:{name:{type:"string"},value:{type:"string",optional:true},fileName:{type:"string",optional:true},contentType:{type:"string",optional:true},comment:{type:"string",optional:true}}},comment:{type:"string",optional:true}}}},{contentType:{id:"contentType",description:"Response content",
properties:{size:{type:"integer"},compression:{type:"integer",optional:true},mimeType:{type:"string"},text:{type:"string",optional:true},encoding:{type:"string",optional:true},comment:{type:"string",optional:true}}}},{cacheType:{id:"cacheType",description:"Info about a response coming from the cache.",properties:{beforeRequest:{$ref:"cacheEntryType"},afterRequest:{$ref:"cacheEntryType"},comment:{type:"string",optional:true}}}},{cacheEntryType:{id:"cacheEntryType",optional:true,description:"Info about cache entry.",
properties:{expires:{type:"string",optional:"true"},lastAccess:{type:"string"},eTag:{type:"string"},hitCount:{type:"integer"},comment:{type:"string",optional:true}}}},{timingsType:{id:"timingsType",description:"Info about request-response timing.",properties:{dns:{type:"integer",min:-1},connect:{type:"integer",min:-1},blocked:{type:"integer",min:-1},send:{type:"integer",min:-1},wait:{type:"integer",min:-1},receive:{type:"integer",min:-1},ssl:{type:"integer",optional:true,min:-1},comment:{type:"string",
optional:true}}}});return m});
require.def("core/cookies",["core/lib"],function(n){return{getCookie:function(b){for(var h=document.cookie.split(";"),m=0;m<h.length;m++){var j=h[m].split("=");if(n.trim(j[0])==b)return j[1].length?unescape(n.trim(j[1])):null}},setCookie:function(b,h,m,j,a,c){var e=new Date;e.setTime(e.getTime());if(m)m=m*1E3*60*60*24;e=new Date(e.getTime()+m);document.cookie=b+"="+escape(h)+(m?";expires="+e.toGMTString():"")+(j?";path="+j:"")+(a?";domain="+a:"")+(c?";secure":"")},removeCookie:function(b,h,m){if(this.getCookie(b))document.cookie=
b+"="+(h?";path="+h:"")+(m?";domain="+m:"")+";expires=Thu, 01-Jan-1970 00:00:01 GMT"}}});require.def("i18n!nls/requestBody",{root:{RequestHeaders:"Request Headers",ResponseHeaders:"Response Headers",RequestCookies:"Request Cookies",ResponseCookies:"Response Cookies",URLParameters:"Params",Headers:"Headers",Post:"Post",Put:"Put",Cookies:"Cookies",Response:"Response",Cache:"Cache",HTML:"HTML"}});
require.def("preview/requestBody",["domplate/domplate","i18n!nls/requestBody","core/lib","domplate/tabView","syntax-highlighter/shCore"],function(n,b,h,m,j){with(n){n=function(){};n.prototype=domplate({render:function(d,g){var o=new m("requestBody");o.appendTab(new a(g));g.request.queryString&&g.request.queryString.length&&o.appendTab(new e(g));g.request.postData&&o.appendTab(new f(g,g.request.method));g.response.content.size>0&&o.appendTab(new c(g));this.showCache(g)&&o.appendTab(new l(g));this.showHtml(g)&&
o.appendTab(new k(g));d=o.render(d);o.selectTabByName("Headers");return d},showCache:function(d){if(!d.cache)return false;if(!d.cache.afterRequest)return false;if(d.category=="image")return false;return true},showHtml:function(d){return d.response.content.mimeType=="text/html"||d.mimeType=="application/xhtml+xml"}});var a=function(d){this.file=d};a.prototype=domplate(m.Tab.prototype,{id:"Headers",label:b.Headers,bodyTag:TABLE({"class":"netInfoHeadersText netInfoText netInfoHeadersTable",cellpadding:0,
cellspacing:0},TBODY(TR({"class":"netInfoResponseHeadersTitle"},TD({colspan:2},DIV({"class":"netInfoHeadersGroup"},b.ResponseHeaders))),TR({"class":"netInfoRequestHeadersTitle"},TD({colspan:2},DIV({"class":"netInfoHeadersGroup"},b.RequestHeaders))))),headerDataTag:FOR("param","$headers",TR(TD({"class":"netInfoParamName"},"$param.name"),TD({"class":"netInfoParamValue"},PRE("$param|getParamValue")))),getParamValue:function(d){return h.wrapText(d.value,true)},onUpdateBody:function(d,g){this.file.response.headers&&
this.insertHeaderRows(g,this.file.response.headers,"Headers","ResponseHeaders");this.file.request.headers&&this.insertHeaderRows(g,this.file.request.headers,"Headers","RequestHeaders")},insertHeaderRows:function(d,g,o,p){o=h.getElementByClass(d,"netInfo"+o+"Table");p=h.getElementByClass(o,"netInfo"+p+"Title");if(g.length){this.headerDataTag.insertRows({headers:g},p?p:d);h.removeClass(p,"collapsed")}else h.setClass(p,"collapsed")}});var c=function(d){this.file=d};c.prototype=domplate(m.Tab.prototype,
{id:"Response",label:b.Response,bodyTag:DIV({"class":"netInfoResponseText netInfoText"},PRE({"class":"javascript:nocontrols:nogutter:",name:"code"})),onUpdateBody:function(d,g){d=h.getElementByClass(g,"netInfoResponseText");if(this.file.category=="image"){h.clearNode(d);g=g.ownerDocument.createElement("img");g.src=this.file.href;d.appendChild(g,d)}else{h.clearNode(d.firstChild);g=this.file.response.content.text;var o=this.file.response.content.mimeType;if(o=="application/javascript"||o=="text/javascript"||
o=="application/x-javascript"||o=="text/ecmascript"||o=="application/ecmascript"){d.firstChild.innerHTML=g;j.SyntaxHighlighter.HighlightAll(d.firstChild)}else h.insertWrappedText(g,d.firstChild)}}});var e=function(d){this.file=d};e.prototype=domplate(a.prototype,{id:"Params",label:b.URLParameters,bodyTag:TABLE({"class":"netInfoParamsText netInfoText netInfoParamsTable",cellpadding:0,cellspacing:0},TBODY()),onUpdateBody:function(d,g){this.file.request.queryString&&this.insertHeaderRows(h.getElementByClass(g,
"netInfoParamsText"),this.file.request.queryString,"Params")}});var f=function(d,g){g=g.charAt(0).toUpperCase()+g.slice(1).toLowerCase();this.file=d;this.id=g;this.label=b[g]};f.prototype=domplate(a.prototype,{bodyTag:DIV({"class":"netInfo$tab.id\\Text netInfoText"},TABLE({"class":"netInfo$tab.id\\Table",cellpadding:0,cellspacing:0},TBODY())),onUpdateBody:function(d,g){if(d=this.file.request.postData){g=h.getElementByClass(g,"netInfo"+this.id+"Text");d.mimeType=="application/x-www-form-urlencoded"?
this.insertHeaderRows(g,d.params,this.id):h.insertWrappedText(d.text,g)}}});(function(d){this.file=d}).prototype=domplate(a.prototype,{id:"Cookies",label:b.Cookies,bodyTag:DIV({"class":"netInfoCookiesText netInfoText"},TABLE({"class":"netInfoCookiesTable",cellpadding:0,cellspacing:0},TBODY(TR({"class":"netInfoResponseCookiesTitle"},TD({colspan:2},DIV({"class":"netInfoCookiesGroup"},b.ResponseCookies))),TR({"class":"netInfoRequestCookiesTitle"},TD({colspan:2},DIV({"class":"netInfoCookiesGroup"},b.RequestCookies)))))),
onUpdateBody:function(d,g){if(file.response.cookies){d=h.getElementByClass(g,"netInfoParamsText");this.insertHeaderRows(d,file.response.cookies,"Cookies","ResponseCookies")}if(file.request.cookies){d=h.getElementByClass(g,"netInfoParamsText");this.insertHeaderRows(d,file.request.cookies,"Cookies","RequestCookies")}}});var l=function(d){this.file=d};l.prototype=domplate(a.prototype,{id:"Cache",label:b.Cache,bodyTag:DIV({"class":"netInfoCacheText netInfoText"},TABLE({"class":"netInfoCacheTable",cellpadding:0,
cellspacing:0},TBODY())),onUpdateBody:function(d,g){if(this.file.cache&&this.file.cache.afterRequest){d=this.file.cache.afterRequest;var o=[];for(var p in d)o.push({name:p,value:d[p]});this.insertHeaderRows(g,o,"Cache")}}});var k=function(d){this.file=d};k.prototype=domplate(a.prototype,{id:"HTML",label:b.HTML,bodyTag:DIV({"class":"netInfoHtmlText netInfoText"},IFRAME({"class":"netInfoHtmlPreview"})),onUpdateBody:function(d,g){h.getElementByClass(g,"netInfoHtmlPreview").contentWindow.document.body.innerHTML=
this.file.response.content.text}});return n}});
require.def("domplate/tabView",["domplate/domplate","core/lib","core/trace"],function(n,b,h){with(n){var m=domplate({tag:TABLE({"class":"tabView",cellpadding:0,cellspacing:0,_repObject:"$tabView"},TBODY(TR({"class":"tabViewRow"},TD({"class":"tabViewCol",valign:"top"},TAG("$tabList",{tabView:"$tabView"}))))),tabList:DIV({"class":"tabViewBody",onclick:"$onClickTab"},DIV({"class":"$tabView.id\\Bar tabBar"}),DIV({"class":"$tabView.id\\Bodies tabBodies"})),tabHeaderTag:A({"class":"$tab.id\\Tab tab",view:"$tab.id",
_repObject:"$tab"},"$tab.label"),tabBodyTag:DIV({"class":"tab$tab.id\\Body tabBody",_repObject:"$tab"}),hideTab:function(){return false},onClickTab:function(j){j=$.event.fix(j||window.event);this.getTabView(j.target).onClickTab(j)},getTabView:function(j){return b.getAncestorByClass(j,"tabView").repObject}});n=function(j){this.id=j;this.tabs=[];this.listeners=[]};n.prototype={appendTab:function(j){this.tabs.push(j);j.tabView=this;return j},getTab:function(j){return(j=b.getElementByClass(this.element,
j+"Tab"))?j.repObject:null},selectTabByName:function(j){(j=b.getElementByClass(this.element,j+"Tab"))&&this.selectTab(j)},addListener:function(j){this.listeners.push(j)},removeListener:function(j){b.remove(this.listeners,j)},onClickTab:function(j){(j=b.getAncestorByClass(j.target,"tab"))&&this.selectTab(j)},selectTab:function(j){if(b.hasClass(j,"tab"))if(!b.hasClass(j,"selected")){var a=j.getAttribute("view");if(a){var c=b.getAncestorByClass(j,"tabViewBody");if(c.selectedTab){c.selectedTab.removeAttribute("selected");
c.selectedBody.removeAttribute("selected");b.removeClass(c.selectedTab,"selected");b.removeClass(c.selectedBody,"selected")}var e=b.getElementByClass(c,"tab"+a+"Body");e||h.error("TabView.selectTab; Missing tab body",j);c.selectedTab=j;c.selectedBody=e;c.selectedTab.setAttribute("selected","true");c.selectedBody.setAttribute("selected","true");b.setClass(c.selectedBody,"selected");b.setClass(c.selectedTab,"selected");this.updateTabBody(c,a)}}},updateTabBody:function(j){j=j.selectedTab.repObject;if(!j._body._updated){j._body._updated=
true;j.bodyTag&&j.bodyTag.replace({tab:j},j._body);j&&j.onUpdateBody&&j.onUpdateBody(this,j._body);for(var a=0;a<this.listeners.length;a++){var c=this.listeners[a];c.onUpdateBody&&c.onUpdateBody(this,j._body)}}},render:function(j){this.element=m.tag.replace({tabView:this},j,m);b.setClass(this.element,this.id);for(var a in this.tabs){var c=this.tabs[a],e=c.tabHeaderTag?c.tabHeaderTag:m.tabHeaderTag,f=c.tabBodyTag?c.tabBodyTag:m.tabBodyTag;try{c._header=e.append({tab:c},b.$(j,"tabBar"));c._body=f.append({tab:c},
b.$(j,"tabBodies"))}catch(l){h.exception("TabView.appendTab; Exception ",l)}}return this.element}};n.Tab=function(){};n.Tab.prototype={invalidate:function(){this._updated=false},select:function(){this.tabView.selectTabByName(this.id)}};return n}});
require.def("syntax-highlighter/shCore",[],function(){var n={sh:{Toolbar:{},Utils:{},RegexLib:{},Brushes:{},Strings:{AboutDialog:'<html><head><title>About...</title></head><body class="dp-about"><table cellspacing="0"><tr><td class="copy"><p class="title">dp.SyntaxHighlighter</div><div class="para">Version: {V}</p><p><a href="http://www.dreamprojections.com/syntaxhighlighter/?ref=about" target="_blank">http://www.dreamprojections.com/syntaxhighlighter</a></p>&copy;2004-2007 Alex Gorbatchev.</td></tr><tr><td class="footer"><input type="button" class="close" value="OK" onClick="window.close()"/></td></tr></table></body></html>'},ClipboardSwf:null,
Version:"1.5.1"}};n.SyntaxHighlighter=n.sh;n.sh.Toolbar.Commands={ExpandSource:{label:"+ expand source",check:function(b){return b.collapse},func:function(b,h){b.parentNode.removeChild(b);h.div.className=h.div.className.replace("collapsed","")}},ViewSource:{label:"view plain",func:function(b,h){b=n.sh.Utils.FixForBlogger(h.originalCode).replace(/</g,"&lt;");h=window.open("","_blank","width=750, height=400, location=0, resizable=1, menubar=0, scrollbars=0");h.document.write('<textarea style="width:99%;height:99%">'+
b+"</textarea>");h.document.close()}},CopyToClipboard:{label:"copy to clipboard",check:function(){return window.clipboardData!=null||n.sh.ClipboardSwf!=null},func:function(b,h){b=n.sh.Utils.FixForBlogger(h.originalCode).replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&amp;/g,"&");if(window.clipboardData)window.clipboardData.setData("text",b);else if(n.sh.ClipboardSwf!=null){var m=h.flashCopier;if(m==null){m=document.createElement("div");h.flashCopier=m;h.div.appendChild(m)}m.innerHTML='<embed src="'+
n.sh.ClipboardSwf+'" FlashVars="clipboard='+encodeURIComponent(b)+'" width="0" height="0" type="application/x-shockwave-flash"></embed>'}alert("The code is in your clipboard now")}},PrintSource:{label:"print",func:function(b,h){b=document.createElement("IFRAME");var m=null;b.style.cssText="position:absolute;width:0px;height:0px;left:-500px;top:-500px;";document.body.appendChild(b);m=b.contentWindow.document;n.sh.Utils.CopyStyles(m,window.document);m.write('<div class="'+h.div.className.replace("collapsed",
"")+' printing">'+h.div.innerHTML+"</div>");m.close();b.contentWindow.focus();b.contentWindow.print();alert("Printing...");document.body.removeChild(b)}},About:{label:"?",func:function(){var b=window.open("","_blank","dialog,width=300,height=150,scrollbars=0"),h=b.document;n.sh.Utils.CopyStyles(h,window.document);h.write(n.sh.Strings.AboutDialog.replace("{V}",n.sh.Version));h.close();b.focus()}}};n.sh.Toolbar.Create=function(b){var h=document.createElement("DIV");h.className="tools";for(var m in n.sh.Toolbar.Commands){var j=
n.sh.Toolbar.Commands[m];j.check!=null&&!j.check(b)||(h.innerHTML+='<a href="#" onclick="dp.sh.Toolbar.Command(\''+m+"',this);return false;\">"+j.label+"</a>")}return h};n.sh.Toolbar.Command=function(b,h){for(var m=h;m!=null&&m.className.indexOf("dp-highlighter")==-1;)m=m.parentNode;m!=null&&n.sh.Toolbar.Commands[b].func(h,m.highlighter)};n.sh.Utils.CopyStyles=function(b,h){h=h.getElementsByTagName("link");for(var m=0;m<h.length;m++)h[m].rel.toLowerCase()=="stylesheet"&&b.write('<link type="text/css" rel="stylesheet" href="'+
h[m].href+'"></link>')};n.sh.Utils.FixForBlogger=function(b){return n.sh.isBloggerMode==true?b.replace(/<br\s*\/?>|&lt;br\s*\/?&gt;/gi,"\n"):b};n.sh.RegexLib={MultiLineCComments:new RegExp("/\\*[\\s\\S]*?\\*/","gm"),SingleLineCComments:new RegExp("//.*$","gm"),SingleLinePerlComments:new RegExp("#.*$","gm"),DoubleQuotedString:new RegExp('"(?:\\.|(\\\\\\")|[^\\""\\n])*"',"g"),SingleQuotedString:new RegExp("'(?:\\.|(\\\\\\')|[^\\''\\n])*'","g")};n.sh.Match=function(b,h,m){this.value=b;this.index=h;this.length=
b.length;this.css=m};n.sh.Highlighter=function(){this.noGutter=false;this.addControls=true;this.collapse=false;this.tabsToSpaces=true;this.wrapColumn=80;this.showColumns=true};n.sh.Highlighter.SortCallback=function(b,h){if(b.index<h.index)return-1;else if(b.index>h.index)return 1;else if(b.length<h.length)return-1;else if(b.length>h.length)return 1;return 0};n.sh.Highlighter.prototype.CreateElement=function(b){b=document.createElement(b);b.highlighter=this;return b};n.sh.Highlighter.prototype.GetMatches=
function(b,h){for(var m=null;(m=b.exec(this.code))!=null;)this.matches[this.matches.length]=new n.sh.Match(m[0],m.index,h)};n.sh.Highlighter.prototype.AddBit=function(b,h){if(!(b==null||b.length==0)){var m=this.CreateElement("SPAN");b=b.replace(/ /g,"&nbsp;");b=b.replace(/</g,"&lt;");b=b.replace(/\n/gm,"&nbsp;<br>");if(h!=null)if(/br/gi.test(b)){b=b.split("&nbsp;<br>");for(var j=0;j<b.length;j++){m=this.CreateElement("SPAN");m.className=h;m.innerHTML=b[j];this.div.appendChild(m);j+1<b.length&&this.div.appendChild(this.CreateElement("BR"))}}else{m.className=
h;m.innerHTML=b;this.div.appendChild(m)}else{m.innerHTML=b;this.div.appendChild(m)}}};n.sh.Highlighter.prototype.IsInside=function(b){if(b==null||b.length==0)return false;for(var h=0;h<this.matches.length;h++){var m=this.matches[h];if(m!=null)if(b.index>m.index&&b.index<m.index+m.length)return true}return false};n.sh.Highlighter.prototype.ProcessRegexList=function(){for(var b=0;b<this.regexList.length;b++)this.GetMatches(this.regexList[b].regex,this.regexList[b].css)};n.sh.Highlighter.prototype.ProcessSmartTabs=
function(b){function h(e,f,l){var k=e.substr(0,f);e=e.substr(f+1,e.length);f="";for(var d=0;d<l;d++)f+=" ";return k+f+e}function m(e,f){if(e.indexOf(a)==-1)return e;for(var l=0;(l=e.indexOf(a))!=-1;)e=h(e,l,f-l%f);return e}b=b.split("\n");for(var j="",a="\t",c=0;c<b.length;c++)j+=m(b[c],4)+"\n";return j};n.sh.Highlighter.prototype.SwitchToList=function(){var b=this.div.innerHTML.replace(/<(br)\/?>/gi,"\n").split("\n");this.addControls==true&&this.bar.appendChild(n.sh.Toolbar.Create(this));if(this.showColumns){for(var h=
this.CreateElement("div"),m=this.CreateElement("div"),j=1;j<=150;)if(j%10==0){h.innerHTML+=j;j+=(j+"").length}else{h.innerHTML+="&middot;";j++}m.className="columns";m.appendChild(h);this.bar.appendChild(m)}j=0;for(h=this.firstLine;j<b.length-1;j++,h++){m=this.CreateElement("LI");var a=this.CreateElement("SPAN");m.className=j%2==0?"alt":"";a.innerHTML=b[j]+"&nbsp;";m.appendChild(a);this.ol.appendChild(m)}this.div.innerHTML=""};n.sh.Highlighter.prototype.Highlight=function(b){function h(f){return f.replace(/^\s*(.*?)[\s\n]*$/g,
"$1")}function m(f){return f.replace(/\n*$/,"").replace(/^\n*/,"")}function j(f){f=n.sh.Utils.FixForBlogger(f).split("\n");for(var l=new RegExp("^\\s*","g"),k=1E3,d=0;d<f.length&&k>0;d++)if(h(f[d]).length!=0){var g=l.exec(f[d]);if(g!=null&&g.length>0)k=Math.min(g[0].length,k)}if(k>0)for(d=0;d<f.length;d++)f[d]=f[d].substr(k);return f.join("\n")}function a(f,l,k){return f.substr(l,k-l)}var c=0;if(b==null)b="";this.originalCode=b;this.code=m(j(b));this.div=this.CreateElement("DIV");this.bar=this.CreateElement("DIV");
this.ol=this.CreateElement("OL");this.matches=[];this.div.className="dp-highlighter";this.div.highlighter=this;this.bar.className="bar";this.ol.start=this.firstLine;if(this.CssClass!=null)this.ol.className=this.CssClass;if(this.collapse)this.div.className+=" collapsed";if(this.noGutter)this.div.className+=" nogutter";if(this.tabsToSpaces==true)this.code=this.ProcessSmartTabs(this.code);this.ProcessRegexList();if(this.matches.length==0)this.AddBit(this.code,null);else{this.matches=this.matches.sort(n.sh.Highlighter.SortCallback);
for(b=0;b<this.matches.length;b++)if(this.IsInside(this.matches[b]))this.matches[b]=null;for(b=0;b<this.matches.length;b++){var e=this.matches[b];if(!(e==null||e.length==0)){this.AddBit(a(this.code,c,e.index),null);this.AddBit(e.value,e.css);c=e.index+e.length}}this.AddBit(this.code.substr(c),null)}this.SwitchToList();this.div.appendChild(this.bar);this.div.appendChild(this.ol)};n.sh.Highlighter.prototype.GetKeywords=function(b){return"\\b"+b.replace(/ /g,"\\b|\\b")+"\\b"};n.sh.BloggerMode=function(){n.sh.isBloggerMode=
true};n.sh.HighlightAll=function(b,h,m,j,a,c){function e(){for(var v=arguments,u=0;u<v.length;u++)if(v[u]!=null){if(typeof v[u]=="string"&&v[u]!="")return v[u]+"";if(typeof v[u]=="object"&&v[u].value!="")return v[u].value+""}return null}function f(v,u){for(var x=0;x<u.length;x++)if(u[x]==v)return true;return false}function l(v,u,x){v=new RegExp("^"+v+"\\[(\\w+)\\]$","gi");for(var w=null,y=0;y<u.length;y++)if((w=v.exec(u[y]))!=null)return w[1];return x}function k(v,u,x){x=document.getElementsByTagName(x);
for(var w=0;w<x.length;w++)x[w].getAttribute("name")==u&&v.push(x[w])}var d=[],g=null,o={};if(typeof b=="string"){k(d,b,"pre");k(d,b,"textarea")}else d.push(b);if(d.length!=0){for(var p in n.sh.Brushes){g=n.sh.Brushes[p].Aliases;if(g!=null)for(b=0;b<g.length;b++)o[g[b]]=p}for(b=0;b<d.length;b++){p=d[b];var q=e(p.attributes["class"],p.className,p.attributes.language,p.language);g="";if(q!=null){q=q.split(":");g=q[0].toLowerCase();if(o[g]!=null){g=new n.sh.Brushes[o[g]];p.style.display="none";g.noGutter=
h==null?f("nogutter",q):!h;g.addControls=m==null?!f("nocontrols",q):m;g.collapse=j==null?f("collapse",q):j;g.showColumns=c==null?f("showcolumns",q):c;var t=document.getElementsByTagName("head")[0];if(g.Style&&t){var s=document.createElement("style");s.setAttribute("type","text/css");if(s.styleSheet)s.styleSheet.cssText=g.Style;else{var r=document.createTextNode(g.Style);s.appendChild(r)}t.appendChild(s)}g.firstLine=a==null?parseInt(l("firstline",q,1)):a;g.Highlight(p.innerHTML);g.source=p;p.parentNode.insertBefore(g.div,
p)}}}}};n.sh.Brushes.JScript=function(){this.regexList=[{regex:n.sh.RegexLib.SingleLineCComments,css:"comment"},{regex:n.sh.RegexLib.MultiLineCComments,css:"comment"},{regex:n.sh.RegexLib.DoubleQuotedString,css:"string"},{regex:n.sh.RegexLib.SingleQuotedString,css:"string"},{regex:new RegExp("^\\s*#.*","gm"),css:"preprocessor"},{regex:new RegExp(this.GetKeywords("abstract boolean break byte case catch char class const continue debugger default delete do double else enum export extends false final finally float for function goto if implements import in instanceof int interface long native new null package private protected public return short static super switch synchronized this throw throws transient true try typeof var void volatile while with"),
"gm"),css:"keyword"}];this.CssClass="dp-c"};n.sh.Brushes.JScript.prototype=new n.sh.Highlighter;n.sh.Brushes.JScript.Aliases=["js","jscript","javascript"];return n});
require.def("domplate/infoTip",["domplate/domplate","core/lib","core/trace"],function(n,b){with(n){n=b.extend({listeners:[],maxWidth:100,maxHeight:80,infoTipMargin:10,infoTipWindowPadding:25,tags:domplate({infoTipTag:DIV({"class":"infoTip"})}),initialize:function(){if(!$.browser.msie){var h=$("body");h.bind("mouseover",b.bind(this.onMouseMove,this));h.bind("mouseout",b.bind(this.onMouseOut,this));h.bind("mousemove",b.bind(this.onMouseMove,this));return this.infoTip=this.tags.infoTipTag.append({},
b.getBody(document))}},showInfoTip:function(h,m,j,a,c,e){var f=b.getOverflowParent(m);if(b.dispatch2(this.listeners,"showInfoTip",[h,m,j+(f?f.scrollLeft:0),a,c,e])){c=h.ownerDocument.documentElement;m=c.clientWidth;c=c.clientHeight;if(j+h.offsetWidth+this.infoTipMargin>m-this.infoTipWindowPadding){h.style.left="auto";h.style.right=m-j+this.infoTipMargin+"px"}else{h.style.left=j+this.infoTipMargin+"px";h.style.right="auto"}h.style.top=a+h.offsetHeight+this.infoTipMargin>c?Math.max(0,c-(h.offsetHeight+
this.infoTipMargin))+"px":a+this.infoTipMargin+"px";h.style.bottom="auto";h.setAttribute("active","true")}else this.hideInfoTip(h)},hideInfoTip:function(h){h&&h.removeAttribute("active")},onMouseOut:function(h){h.relatedTarget||this.hideInfoTip(this.infoTip)},onMouseMove:function(h){this.infoTip.setAttribute("multiline",false);this.showInfoTip(this.infoTip,h.target,h.clientX,h.clientY,h.rangeParent,h.rangeOffset)},populateTimingInfoTip:function(h,m){this.tags.colorTag.replace({rgbValue:m},h);return true},
addListener:function(h){this.listeners.push(h)},removeListener:function(h){b.remove(this.listeners,h)}});n.initialize();return n}});
require.def("domplate/popupMenu",["domplate/domplate","core/lib","core/trace"],function(n,b){with(n){var h={controllers:[],controllerContext:{label:"controller context"},initialize:function(c){this.controllers=[];this.controllerContext=c||this.controllerContext},shutdown:function(){this.removeControllers()},addController:function(){for(var c=0,e;e=arguments[c];c++){if(typeof e[0]=="string")e[0]=$$(e[0],this.controllerContext);var f=e[2];e[2]=b.bind(f,this);e[3]=f;this.controllers.push(e);b.addEventListener.apply(this,
e)}},removeController:function(){for(var c=0,e;e=arguments[c];c++)for(var f=0,l;l=this.controllers[f];f++)e[0]==l[0]&&e[1]==l[1]&&e[2]==l[3]&&b.removeEventListener.apply(this,l)},removeControllers:function(){for(var c=0,e;e=this.controllers[c];c++)b.removeEventListener.apply(this,e)}};n={"class":"$item.className",type:"$item.type",value:"$item.value",_command:"$item.command"};if(b.isIE6)n.href="javascript:void(0)";var m=domplate({tag:DIV({"class":"popupMenu popupMenuShadow"},DIV({"class":"popupMenuContent popupMenuShadowContent"},
FOR("item","$object.items|memberIterator",TAG("$item.tag",{item:"$item"})))),itemTag:A(n,"$item.label"),checkBoxTag:A(b.extend(n,{checked:"$item.checked"}),"$item.label"),radioButtonTag:A(b.extend(n,{selected:"$item.selected"}),"$item.label"),groupTag:A(b.extend(n,{child:"$item.child"}),"$item.label"),shortcutTag:A(n,"$item.label",SPAN({"class":"popupMenuShortcutKey"},"$item.key")),separatorTag:SPAN({"class":"popupMenuSeparator"}),memberIterator:function(c){for(var e=[],f=0,l=c.length;f<l;f++){var k=
c[f];if(typeof k=="string"&&k.indexOf("-")==0)e.push({tag:this.separatorTag});else{k=b.extend(k,{});k.type=k.type||"";k.value=k.value||"";var d=k.type;k.tag=this.itemTag;var g=k.className||"";g+="popupMenuOption ";if(d=="checkbox"){g+="popupMenuCheckBox ";k.tag=this.checkBoxTag}else if(d=="radio"){g+="popupMenuRadioButton ";k.tag=this.radioButtonTag}else if(d=="group"){g+="popupMenuGroup ";k.tag=this.groupTag}else if(d=="shortcut"){g+="popupMenuShortcut ";k.tag=this.shortcutTag}if(k.checked)g+="popupMenuChecked ";
else if(k.selected)g+="popupMenuRadioSelected ";if(k.disabled)g+="popupMenuDisabled ";k.className=g;k.label=k.label;e.push(k)}}return e}}),j=function(c){if(!c.element){if(c.getItems)c.items=c.getItems();var e=b.getBody(document);c.element=m.tag.append({object:c},e,m)}b.append(this,c);if(typeof this.element=="string"){this.id=this.element;this.element=$(this.id)}else if(this.id)this.element.id=this.id;this.elementStyle=this.element.style;this.isVisible=false;this.handleMouseDown=b.bind(this.handleMouseDown,
this);this.handleMouseOver=b.bind(this.handleMouseOver,this);this.handleMouseOut=b.bind(this.handleMouseOut,this);this.handleWindowMouseDown=b.bind(this.handleWindowMouseDown,this)},a={};j.prototype=b.extend(h,{initialize:function(){h.initialize.call(this);this.addController([this.element,"mousedown",this.handleMouseDown],[this.element,"mouseover",this.handleMouseOver])},destroy:function(){this.hide();if(this.parentMenu)this.parentMenu.childMenu=null;this.element.parentNode.removeChild(this.element);
this.parentTarget=this.parentMenu=this.elementStyle=this.element=null},shutdown:function(){h.shutdown.call(this)},showPopup:function(c){var e=b.isIE6?1:-4;c=b.getElementBox(c);var f={top:0,left:0};this.show(c.left+e-f.left,c.top+c.height-5-f.top)},show:function(c,e){this.initialize();if(!this.isVisible){c=c||0;e=e||0;if(this.parentMenu){var f=this.parentMenu.childMenu;f&&f!=this&&f.destroy();this.parentMenu.childMenu=this}else b.addEventListener(document,"mousedown",this.handleWindowMouseDown);this.elementStyle.display=
"block";this.elementStyle.visibility="hidden";f=b.getWindowSize();c=Math.min(c,f.width-this.element.clientWidth-10);c=Math.max(c,0);e=Math.min(e,f.height-this.element.clientHeight-10);e=Math.max(e,0);this.elementStyle.left=c+"px";this.elementStyle.top=e+"px";this.elementStyle.visibility="visible";this.isVisible=true;b.isFunction(this.onShow)&&this.onShow.apply(this,arguments)}},hide:function(){this.clearHideTimeout();this.clearShowChildTimeout();if(this.isVisible){this.elementStyle.display="none";
if(this.childMenu){this.childMenu.destroy();this.childMenu=null}this.parentTarget&&b.removeClass(this.parentTarget,"popupMenuGroupSelected");this.isVisible=false;this.shutdown();b.isFunction(this.onHide)&&this.onHide.apply(this,arguments)}},showChildMenu:function(c){var e=c.getAttribute("child"),f=this;c=c;this.showChildTimeout=window.setTimeout(function(){var l=b.getElementBox(c),k=a.hasOwnProperty(e)?a[e]:{element:$(e)};(new j(b.extend(k,{parentMenu:f,parentTarget:c}))).show(l.left+l.width+(b.isIE6?
-1:-6),l.top-6);b.setClass(c,"popupMenuGroupSelected")},350)},clearHideTimeout:function(){if(this.hideTimeout){window.clearTimeout(this.hideTimeout);delete this.hideTimeout}},clearShowChildTimeout:function(){if(this.showChildTimeout){window.clearTimeout(this.showChildTimeout);this.showChildTimeout=null}},handleMouseDown:function(c){b.cancelEvent(c,true);for(var e=this;e.parentMenu;)e=e.parentMenu;c=c.target||c.srcElement;c=b.getAncestorByClass(c,"popupMenuOption");if(!c||b.hasClass(c,"popupMenuGroup"))return false;
if(c&&!b.hasClass(c,"popupMenuDisabled")){var f=c.getAttribute("type");if(f=="checkbox"){c.getAttribute("checked");var l=c.getAttribute("value"),k=b.hasClass(c,"popupMenuChecked");if(k){b.removeClass(c,"popupMenuChecked");c.setAttribute("checked","")}else{b.setClass(c,"popupMenuChecked");c.setAttribute("checked","true")}b.isFunction(this.onCheck)&&this.onCheck.call(this,c,l,!k)}if(f=="radiobutton"){f=b.getElementsByClass(c.parentNode,"popupMenuRadioSelected");l=c.getAttribute("group");k=0;for(var d=
f.length;k<d;k++){radio=f[k];if(radio.getAttribute("group")==l){b.removeClass(radio,"popupMenuRadioSelected");radio.setAttribute("selected","")}}b.setClass(c,"popupMenuRadioSelected");c.setAttribute("selected","true")}f=null;l=c.command;if(b.isFunction(l))f=l;else if(typeof l=="string")f=this[l];l=true;if(f)l=f.call(this,c)!==false;l&&e.hide()}return false},handleWindowMouseDown:function(c){c=c.target||c.srcElement;c=b.getAncestorByClass(c,"popupMenu");if(!c){b.removeEventListener(document,"mousedown",
this.handleWindowMouseDown);this.destroy()}},handleMouseOver:function(c){this.clearHideTimeout();this.clearShowChildTimeout();c=c.target||c.srcElement;if(c=b.getAncestorByClass(c,"popupMenuOption")){var e=this.childMenu;if(e){b.removeClass(e.parentTarget,"popupMenuGroupSelected");if(e.parentTarget!=c&&e.isVisible){e.clearHideTimeout();e.hideTimeout=window.setTimeout(function(){e.destroy()},300)}}b.hasClass(c,"popupMenuGroup")&&this.showChildMenu(c)}}});b.append(j,{register:function(c){a[c.id]=c},
check:function(c){b.setClass(c,"popupMenuChecked");c.setAttribute("checked","true")},uncheck:function(c){b.removeClass(c,"popupMenuChecked");c.setAttribute("checked","")},disable:function(c){b.setClass(c,"popupMenuDisabled")},enable:function(c){b.removeClass(c,"popupMenuDisabled")}});return j}});
(function(n){if(!b)var b={};(function(){function h(d){return d<10?"0"+d:d}function m(d){c.lastIndex=0;return c.test(d)?'"'+d.replace(c,function(g){var o=l[g];return typeof o==="string"?o:"\\u"+("0000"+g.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+d+'"'}function j(d,g){var o,p,q=e,t,s=g[d];if(s&&typeof s==="object"&&typeof s.toJSON==="function")s=s.toJSON(d);if(typeof k==="function")s=k.call(g,d,s);switch(typeof s){case "string":return m(s);case "number":return isFinite(s)?String(s):"null";case "boolean":case "null":return String(s);
case "object":if(!s)return"null";e+=f;t=[];if(Object.prototype.toString.apply(s)==="[object Array]"){p=s.length;for(d=0;d<p;d+=1)t[d]=j(d,s)||"null";g=t.length===0?"[]":e?"[\n"+e+t.join(",\n"+e)+"\n"+q+"]":"["+t.join(",")+"]";e=q;return g}if(k&&typeof k==="object"){p=k.length;for(d=0;d<p;d+=1){o=k[d];if(typeof o==="string")if(g=j(o,s))t.push(m(o)+(e?": ":":")+g)}}else for(o in s)if(Object.hasOwnProperty.call(s,o))if(g=j(o,s))t.push(m(o)+(e?": ":":")+g);g=t.length===0?"{}":e?"{\n"+e+t.join(",\n"+e)+
"\n"+q+"}":"{"+t.join(",")+"}";e=q;return g}}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(){return this.getUTCFullYear()+"-"+h(this.getUTCMonth()+1)+"-"+h(this.getUTCDate())+"T"+h(this.getUTCHours())+":"+h(this.getUTCMinutes())+":"+h(this.getUTCSeconds())+"Z"};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()}}var a=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
c=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,e,f,l={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},k;if(typeof b.stringify!=="function")b.stringify=function(d,g,o){var p;f=e="";if(typeof o==="number")for(p=0;p<o;p+=1)f+=" ";else if(typeof o==="string")f=o;if((k=g)&&typeof g!=="function"&&(typeof g!=="object"||typeof g.length!=="number"))throw new Error("JSON.stringify");return j("",
{"":d})};if(typeof b.parse!=="function")b.parse=function(d,g){function o(p,q){var t,s,r=p[q];if(r&&typeof r==="object")for(t in r)if(Object.hasOwnProperty.call(r,t)){s=o(r,t);if(s!==undefined)r[t]=s;else delete r[t]}return g.call(p,q,r)}a.lastIndex=0;if(a.test(d))d=d.replace(a,function(p){return"\\u"+("0000"+p.charCodeAt(0).toString(16)).slice(-4)});if(/^[\],:{}\s]*$/.test(d.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){d=eval("("+d+")");return typeof g==="function"?o({"":d},""):d}throw new SyntaxError("JSON.parse");}})();n.toJSON=function(h,m){if(typeof m=="undefined")m=null;return b.parse(h,m)};n.jSONToString=function(h,m,j){if(typeof m=="undefined")m=null;if(typeof j=="undefined")j=null;return b.stringify(h,m,j)}})(jQuery);require.def("jquery-plugins/jquery.json",function(){});require.resume();