/*
 RequireJS Copyright (c) 2004-2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/requirejs for details
 RequireJS i18n Copyright (c) 2004-2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/requirejs for details
 RequireJS text Copyright (c) 2004-2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/requirejs for details
 RequireJS jsonp Copyright (c) 2004-2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/requirejs for details
 RequireJS order Copyright (c) 2004-2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/requirejs for details

 jQuery JavaScript Library v1.4.2
 http://jquery.com/

 Copyright 2010, John Resig
 Dual licensed under the MIT or GPL Version 2 licenses.
 http://jquery.org/license

 Includes Sizzle.js
 http://sizzlejs.com/
 Copyright 2010, The Dojo Foundation
 Released under the MIT, BSD, and GPL Licenses.

 Date: Sat Feb 13 22:33:48 2010 -0500
*/
var require;
(function(){function K(l){return y.call(l)==="[object Function]"}function A(l,o,w){var t=k.plugins.defined[l];if(t)t[w.name].apply(null,w.args);else{t=k.plugins.waiting[l]||(k.plugins.waiting[l]=[]);t.push(w);o.defined.require(["require/"+l])}}function Z(l,o){var w=k.plugins.callbacks[l]=[];k.plugins[l]=function(){for(var t=0,F;F=w[t];t++)if(F.apply(null,arguments)===true&&o)return true;return false}}function B(l){return function(o){l.exports=o}}var s={},k,D,E=[],G,Q,R,P,W,S={},O,ja=/^(complete|loaded)$/,c,
aa=!!(typeof window!=="undefined"&&navigator&&document),ia=!aa&&typeof importScripts!=="undefined",y=Object.prototype.toString,ka,x,na;if(typeof require!=="undefined")if(K(require))return;else S=require;x=require=function(l,o,w,t){var F;if(typeof l==="string"&&!K(o))return require.get(l,o);if(!require.isArray(l)){F=l;if(require.isArray(o)){l=o;o=w;w=t}else l=[]}return c(null,l,o,F,w)};x.onError=function(l){throw l;};x.def=function(l,o,w,t){if(!x.isArray(o)){t=w;w=o;o=[]}return c(l,o,w,null,t)};c=
function(l,o,w,t,F){var C=k.contexts[F],$,V,T;F=F?F:t&&t.context?t.context:k.ctxName;C=k.contexts[F];if(l){T=l.indexOf("!");if(T!==-1){$=l.substring(0,T);l=l.substring(T+1,l.length)}if(C&&(C.defined[l]||C.waiting[l]))return x}if(!C){C={contextName:F,config:{waitSeconds:7,baseUrl:k.baseUrl||"./",paths:{}},waiting:[],specified:{require:true,exports:true,module:true},loaded:{require:true},urlFetched:{},defined:{},modifiers:{}};C.defined.require=x;k.plugins.newContext&&k.plugins.newContext(C);C=k.contexts[F]=
C}if(t){if(t.baseUrl)if(t.baseUrl.charAt(t.baseUrl.length-1)!=="/")t.baseUrl+="/";T=C.config.paths;x.mixin(C.config,t,true);if(t.paths){for(V in t.paths)V in s||(T[V]=t.paths[V]);C.config.paths=T}if(t.priority){x(t.priority);C.config.priorityWait=t.priority}if(t.deps||t.callback)x(t.deps||[],t.callback);t.ready&&x.ready(t.ready);if(!o)return x}if(o){t=o;o=[];for(V=0;V<t.length;V++)o[V]=x.splitPrefix(t[V],l)}t=C.waiting.push({name:l,deps:o,callback:w});if(l){C.waiting[l]=t-1;C.specified[l]=true}if(l&&
w&&!x.isFunction(w))C.defined[l]=w;$&&A($,C,{name:"require",args:[l,o,w,C]});if(k.paused||C.config.priorityWait)(k.paused||(k.paused=[])).push([$,l,o,C]);else{x.checkDeps($,l,o,C);x.checkLoaded(F)}if(l)C.loaded[l]=true;return x};x.mixin=function(l,o,w){for(var t in o)if(!(t in s)&&(!(t in l)||w))l[t]=o[t];return x};x.version="0.13.0";k=x.s={ctxName:"_",contexts:{},plugins:{defined:{},callbacks:{},waiting:{}},skipAsync:{},isBrowser:aa,isPageLoaded:!aa,readyCalls:[],doc:aa?document:null};x.isBrowser=
k.isBrowser;if(aa){k.head=document.getElementsByTagName("head")[0];if(na=document.getElementsByTagName("base")[0])k.head=na.parentNode}x.plugin=function(l){var o,w,t,F=l.prefix,C=k.plugins.callbacks,$=k.plugins.waiting[F],V;o=k.plugins.defined;t=k.contexts;if(o[F])return x;o[F]=l;V=["newContext","isWaiting","orderDeps"];for(o=0;w=V[o];o++){k.plugins[w]||Z(w,w==="isWaiting");C[w].push(l[w])}if(l.newContext)for(w in t)if(!(w in s)){o=t[w];l.newContext(o)}if($){for(o=0;t=$[o];o++)l[t.name]&&l[t.name].apply(null,
t.args);delete k.plugins.waiting[F]}return x};x.pause=function(){if(!k.paused)k.paused=[]};x.resume=function(){var l,o,w;if(!k.contexts[k.ctxName].config.priorityWait){if(k.paused){w=k.paused;delete k.paused;for(l=0;o=w[l];l++)x.checkDeps.apply(x,o)}x.checkLoaded(k.ctxName)}};x.checkDeps=function(l,o,w,t){if(l)A(l,t,{name:"checkDeps",args:[o,w,t]});else for(l=0;o=w[l];l++)if(!t.specified[o.fullName]){t.specified[o.fullName]=true;t.startTime=(new Date).getTime();o.prefix?A(o.prefix,t,{name:"load",
args:[o.name,t.contextName]}):x.load(o.name,t.contextName)}};x.isArray=function(l){return y.call(l)==="[object Array]"};x.isFunction=K;x.get=function(l,o){if(l==="exports"||l==="module")return x.onError(new Error("require of "+l+" is not allowed."));o=o||k.ctxName;var w=k.contexts[o].defined[l];if(w===undefined)return x.onError(new Error("require: module name '"+l+"' has not been loaded yet for context: "+o));return w};x.load=function(l,o){var w=k.contexts[o],t=w.urlFetched;w=w.loaded;k.isDone=false;
w[l]||(w[l]=false);w=x.nameToUrl(l,null,o);if(!t[w]){x.attach(w,o,l);t[w]=true}};x.jsExtRegExp=/\.js$/;x.normalizeName=function(l,o){if(l.charAt(0)==="."){o=o.split("/");o=o.slice(0,o.length-1);l=o.concat(l.split("/"));for(D=0;o=l[D];D++)if(o==="."){l.splice(D,1);D-=1}else if(o===".."){l.splice(D-1,2);D-=2}l=l.join("/")}return l};x.splitPrefix=function(l,o){var w=l.indexOf("!"),t=null;if(w!==-1){t=l.substring(0,w);l=l.substring(w+1,l.length)}if(o)l=x.normalizeName(l,o);return{prefix:t,name:l,fullName:t?
t+"!"+l:l}};x.nameToUrl=function(l,o,w){var t,F,C;w=k.contexts[w].config;if(l.indexOf(":")!==-1||l.charAt(0)==="/"||x.jsExtRegExp.test(l))return l+(o?o:"");else if(l.charAt(0)===".")return x.onError(new Error("require.nameToUrl does not handle relative module names (ones that start with '.' or '..')"));else{t=w.paths;l=l.split("/");for(F=l.length;F>0;F--){C=l.slice(0,F).join("/");if(t[C]){l.splice(0,F,t[C]);break}}o=l.join("/")+(o||".js");return(o.charAt(0)==="/"||o.match(/^\w+:/)?"":w.baseUrl)+o}};
x.checkLoaded=function(l){var o=k.contexts[l||k.ctxName],w=o.config.waitSeconds*1E3,t=w&&o.startTime+w<(new Date).getTime(),F,C;w="";var $=false,V=false,T,ea,ga=k.plugins.isWaiting,Y=k.plugins.orderDeps,fa={};if(!o.isCheckLoaded){if(o.config.priorityWait){C=true;for(F=0;ea=o.config.priorityWait[F];F++)if(!o.loaded[ea]){C=false;break}if(C){delete o.config.priorityWait;x.resume()}else return}o.isCheckLoaded=true;C=o.waiting;F=o.loaded;for(T in F)if(!(T in s)){$=true;if(!F[T])if(t)w+=T+" ";else{V=true;
break}}if(!$&&!C.length&&(!ga||!ga(o)))o.isCheckLoaded=false;else{if(t&&w){o=new Error("require.js load timeout for modules: "+w);o.requireType="timeout";o.requireModules=w;return x.onError(o)}if(V){o.isCheckLoaded=false;if(aa||ia)setTimeout(function(){x.checkLoaded(l)},50)}else{o.waiting=[];o.loaded={};Y&&Y(o);for(F=0;w=C[F];F++)x.exec(w,fa,C,o);o.isCheckLoaded=false;if(o.waiting.length||ga&&ga(o))x.checkLoaded(l);else if(!E.length){k.ctxName="_";k.isDone=true;x.callReady&&x.callReady()}}}}};x.exec=
function(l,o,w,t){if(l){var F=l.name,C=l.callback;C=l.deps;var $,V,T=t.defined,ea,ga=[],Y,fa,ha=false;if(F){if(o[F]||F in T)return T[F];o[F]=true}if(C)for($=0;V=C[$];$++){Y=V.name;if(Y==="exports"){Y=T[F]={};ha=true}else if(Y==="module"){fa=Y={id:F,uri:F?x.nameToUrl(F,null,t.contextName):undefined};fa.setExports=B(fa)}else Y=Y in T?T[Y]:o[Y]?undefined:x.exec(w[w[Y]],o,w,t);ga.push(Y)}if((C=l.callback)&&x.isFunction(C)){ea=x.execCb(F,C,ga);if(F)if(ha&&(!fa||!("exports"in fa)))ea=T[F];else if(fa&&"exports"in
fa)ea=T[F]=Y.exports;else{if(F in T)return x.onError(new Error(F+" has already been defined"));T[F]=ea}}return ea}};x.execCb=function(l,o,w){return o.apply(null,w)};x.onScriptLoad=function(l){var o=l.currentTarget||l.srcElement,w;if(l.type==="load"||ja.test(o.readyState)){l=o.getAttribute("data-requirecontext");w=o.getAttribute("data-requiremodule");k.contexts[l].loaded[w]=true;x.checkLoaded(l);o.removeEventListener?o.removeEventListener("load",x.onScriptLoad,false):o.detachEvent("onreadystatechange",
x.onScriptLoad)}};x.attach=function(l,o,w,t,F){var C;if(aa){t=t||x.onScriptLoad;C=document.createElement("script");C.type=F||"text/javascript";C.charset="utf-8";if(!k.skipAsync[l])C.async=true;C.setAttribute("data-requirecontext",o);C.setAttribute("data-requiremodule",w);C.addEventListener?C.addEventListener("load",t,false):C.attachEvent("onreadystatechange",t);C.src=l;return na?k.head.insertBefore(C,na):k.head.appendChild(C)}else if(ia){o=k.contexts[o].loaded;o[w]=false;importScripts(l);o[w]=true}return null};
k.baseUrl=S.baseUrl;if(aa&&(!k.baseUrl||!k.head)){G=document.getElementsByTagName("script");R=S.baseUrlMatch?S.baseUrlMatch:/(requireplugins-|require-)?jquery[\-\d\.]*(min)?\.js(\W|$)/i;for(D=G.length-1;D>-1&&(Q=G[D]);D--){if(!k.head)k.head=Q.parentNode;if(!S.deps)if(P=Q.getAttribute("data-main"))S.deps=[P];if((P=Q.src)&&!k.baseUrl)if(W=P.match(R)){k.baseUrl=P.substring(0,W.index);break}}}x.pageLoaded=function(){if(!k.isPageLoaded){k.isPageLoaded=true;ka&&clearInterval(ka);if(O)document.readyState=
"complete";x.callReady()}};x.callReady=function(){var l=k.readyCalls,o,w;if(k.isPageLoaded&&k.isDone&&l.length){k.readyCalls=[];for(o=0;w=l[o];o++)w()}};x.ready=function(l){k.isPageLoaded&&k.isDone?l():k.readyCalls.push(l);return x};if(aa){if(document.addEventListener){document.addEventListener("DOMContentLoaded",x.pageLoaded,false);window.addEventListener("load",x.pageLoaded,false);if(!document.readyState){O=true;document.readyState="loading"}}else if(window.attachEvent){window.attachEvent("onload",
x.pageLoaded);if(self===self.top)ka=setInterval(function(){try{if(document.body){document.documentElement.doScroll("left");x.pageLoaded()}}catch(l){}},30)}document.readyState==="complete"&&x.pageLoaded()}x(S)})();
(function(){function K(s,k){k=k.nlsWaiting;return k[s]||(k[s]=k[k.push({_name:s})-1])}function A(s,k,D,E){var G,Q,R,P,W,S,O="root";Q=D.split("-");R=[];P=K(s,E);for(G=Q.length;G>-1;G--){W=G?Q.slice(0,G).join("-"):"root";if(S=k[W]){if(D===E.config.locale&&!P._match)P._match=W;if(O==="root")O=W;P[W]=W;if(S===true){S=s.split("/");S.splice(-1,0,W);S=S.join("/");!E.specified[S]&&!(S in E.loaded)&&!E.defined[S]&&R.push(S)}}}if(O!==D)if(E.defined[O])E.defined[D]=E.defined[O];else P[D]=O;R.length&&E.defined.require(R)}
var Z=/(^.*(^|\/)nls(\/|$))([^\/]*)\/?([^\/]*)/,B={};require.plugin({prefix:"i18n",require:function(s,k,D,E){var G,Q=E.defined[s];G=Z.exec(s);if(G[5]){s=G[1]+G[5];k=K(s,E);k[G[4]]=G[4];k=E.nls[s];if(!k){E.defined.require([s]);k=E.nls[s]={}}k[G[4]]=D}else{if(k=E.nls[s])require.mixin(k,Q);else k=E.nls[s]=Q;E.nlsRootLoaded[s]=true;if(G=E.nlsToLoad[s]){delete E.nlsToLoad[s];for(D=0;D<G.length;D++)A(s,k,G[D],E)}A(s,k,E.config.locale,E)}},newContext:function(s){require.mixin(s,{nlsWaiting:[],nls:{},nlsRootLoaded:{},
nlsToLoad:{}});if(!s.config.locale)s.config.locale=typeof navigator==="undefined"?"root":(navigator.language||navigator.userLanguage||"root").toLowerCase()},load:function(s,k){var D=require.s.contexts[k],E=Z.exec(s),G=E[4];if(E[5]){s=E[1]+E[5];k=D.nls[s];if(D.nlsRootLoaded[s]&&k)A(s,k,G,D);else{(D.nlsToLoad[s]||(D.nlsToLoad[s]=[])).push(G);D.defined.require([s])}}else D.nlsRootLoaded[s]||require.load(s,k)},checkDeps:function(){},isWaiting:function(s){return!!s.nlsWaiting.length},orderDeps:function(s){var k,
D,E,G,Q,R,P,W,S,O,ja,c,aa=s.nlsWaiting,ia;s.nlsWaiting=[];s.nlsToLoad={};for(k=0;G=aa[k];k++){E=G._name;Q=s.nls[E];ja=null;R=E.split("/");S=R.slice(0,R.length-1).join("/");P=R[R.length-1];for(O in G)if(O!=="_name"&&!(O in B))if(O==="_match")ja=G[O];else if(G[O]!==O)(ia||(ia={}))[O]=G[O];else{W={};R=O.split("-");for(D=R.length;D>0;D--){c=R.slice(0,D).join("-");c!=="root"&&Q[c]&&require.mixin(W,Q[c])}Q.root&&require.mixin(W,Q.root);s.defined[S+"/"+O+"/"+P]=W}s.defined[E]=s.defined[S+"/"+ja+"/"+P];if(ia)for(O in ia)O in
B||(s.defined[S+"/"+O+"/"+P]=s.defined[S+"/"+ia[O]+"/"+P])}}})})();
(function(){var K=["Msxml2.XMLHTTP","Microsoft.XMLHTTP","Msxml2.XMLHTTP.4.0"],A=/^\s*<\?xml(\s)+version=[\'\"](\d)*.(\d)*[\'\"](\s)*\?>/im,Z=/<body[^>]*>\s*([\s\S]+)\s*<\/body>/im;if(!require.textStrip)require.textStrip=function(B){if(B){B=B.replace(A,"");var s=B.match(Z);if(s)B=s[1]}else B="";return B};if(!require.getXhr)require.getXhr=function(){var B,s,k;if(typeof XMLHttpRequest!=="undefined")return new XMLHttpRequest;else for(s=0;s<3;s++){k=K[s];try{B=new ActiveXObject(k)}catch(D){}if(B){K=[k];
break}}if(!B)throw new Error("require.getXhr(): XMLHttpRequest not available");return B};if(!require.fetchText)require.fetchText=function(B,s){var k=require.getXhr();k.open("GET",B,true);k.onreadystatechange=function(){k.readyState===4&&s(k.responseText)};k.send(null)};require.plugin({prefix:"text",require:function(){},newContext:function(B){require.mixin(B,{text:{},textWaiting:[]})},load:function(B,s){var k=false,D=null,E,G=B.indexOf("."),Q=B.substring(0,G),R=B.substring(G+1,B.length),P=require.s.contexts[s],
W=P.textWaiting;G=R.indexOf("!");if(G!==-1){k=R.substring(G+1,R.length);R=R.substring(0,G);G=k.indexOf("!");if(G!==-1&&k.substring(0,G)==="strip"){D=k.substring(G+1,k.length);k="strip"}else if(k!=="strip"){D=k;k=null}}E=Q+"!"+R;G=k?E+"!"+k:E;if(D!==null&&!P.text[E])P.defined[B]=P.text[E]=D;else if(!P.text[E]&&!P.textWaiting[E]&&!P.textWaiting[G]){W[G]||(W[G]=W[W.push({name:B,key:E,fullKey:G,strip:!!k})-1]);k=require.nameToUrl(Q,"."+R,s);P.loaded[B]=false;require.fetchText(k,function(S){P.text[E]=
S;P.loaded[B]=true;require.checkLoaded(s)})}},checkDeps:function(){},isWaiting:function(B){return!!B.textWaiting.length},orderDeps:function(B){var s,k,D,E=B.textWaiting;B.textWaiting=[];for(s=0;k=E[s];s++){D=B.text[k.key];B.defined[k.name]=k.strip?require.textStrip(D):D}}})})();
(function(){var K=0;require._jsonp={};require.plugin({prefix:"jsonp",require:function(){},newContext:function(A){require.mixin(A,{jsonpWaiting:[]})},load:function(A,Z){var B=A.indexOf("?"),s=A.substring(0,B);B=A.substring(B+1,A.length);var k=require.s.contexts[Z],D={name:A},E="f"+K++,G=require.s.head,Q=G.ownerDocument.createElement("script");require._jsonp[E]=function(R){D.value=R;k.loaded[A]=true;require.checkLoaded(Z);setTimeout(function(){G.removeChild(Q);delete require._jsonp[E]},15)};k.jsonpWaiting.push(D);
s=require.nameToUrl(s,"?",Z);s+=(s.indexOf("?")===-1?"?":"")+B.replace("?","require._jsonp."+E);k.loaded[A]=false;Q.type="text/javascript";Q.charset="utf-8";Q.src=s;Q.async=true;G.appendChild(Q)},checkDeps:function(){},isWaiting:function(A){return!!A.jsonpWaiting.length},orderDeps:function(A){var Z,B,s=A.jsonpWaiting;A.jsonpWaiting=[];for(Z=0;B=s[Z];Z++)A.defined[B.name]=B.value}})})();
(function(){function K(B){var s=B.currentTarget||B.srcElement,k,D,E,G;if(B.type==="load"||Z.test(s.readyState)){D=s.getAttribute("data-requirecontext");k=s.getAttribute("data-requiremodule");B=require.s.contexts[D];E=B.orderWaiting;G=B.orderCached;G[k]=true;for(k=0;G[E[k]];k++);k>0&&require(E.splice(0,k),D);if(!E.length)B.orderCached={};setTimeout(function(){s.parentNode.removeChild(s)},15)}}var A=window.opera&&Object.prototype.toString.call(window.opera)==="[object Opera]"||"MozAppearance"in document.documentElement.style,
Z=/^(complete|loaded)$/;require.plugin({prefix:"order",require:function(){},newContext:function(B){require.mixin(B,{orderWaiting:[],orderCached:{}})},load:function(B,s){var k=require.s.contexts[s],D=require.nameToUrl(B,null,s);require.s.skipAsync[D]=true;if(A)require([B],s);else{k.orderWaiting.push(B);k.loaded[B]=false;require.attach(D,s,B,K,"script/cache")}},checkDeps:function(){},isWaiting:function(B){return!!B.orderWaiting.length},orderDeps:function(){}})})();
(function(K,A){function Z(){if(!c.isReady){try{y.documentElement.doScroll("left")}catch(a){setTimeout(Z,1);return}c.ready()}}function B(a,b){b.src?c.ajax({url:b.src,async:false,dataType:"script"}):c.globalEval(b.text||b.textContent||b.innerHTML||"");b.parentNode&&b.parentNode.removeChild(b)}function s(a,b,d,f,e,i){var j=a.length;if(typeof b==="object"){for(var r in b)s(a,r,b[r],f,e,d);return a}if(d!==A){f=!i&&f&&c.isFunction(d);for(r=0;r<j;r++)e(a[r],b,f?d.call(a[r],r,e(a[r],b)):d,i);return a}return j?
e(a[0],b):A}function k(){return(new Date).getTime()}function D(){return false}function E(){return true}function G(a,b,d){d[0].type=a;return c.event.handle.apply(b,d)}function Q(a){var b,d=[],f=[],e=arguments,i,j,r,m,q,z;j=c.data(this,"events");if(!(a.liveFired===this||!j||!j.live||a.button&&a.type==="click")){a.liveFired=this;var I=j.live.slice(0);for(m=0;m<I.length;m++){j=I[m];j.origType.replace(qa,"")===a.type?f.push(j.selector):I.splice(m--,1)}i=c(a.target).closest(f,a.currentTarget);q=0;for(z=
i.length;q<z;q++)for(m=0;m<I.length;m++){j=I[m];if(i[q].selector===j.selector){r=i[q].elem;f=null;if(j.preType==="mouseenter"||j.preType==="mouseleave")f=c(a.relatedTarget).closest(j.selector)[0];if(!f||f!==r)d.push({elem:r,handleObj:j})}}q=0;for(z=d.length;q<z;q++){i=d[q];a.currentTarget=i.elem;a.data=i.handleObj.data;a.handleObj=i.handleObj;if(i.handleObj.origHandler.apply(i.elem,e)===false){b=false;break}}return b}}function R(a,b){return"live."+(a&&a!=="*"?a+".":"")+b.replace(/\./g,"`").replace(/ /g,
"&")}function P(a){return!a||!a.parentNode||a.parentNode.nodeType===11}function W(a,b){var d=0;b.each(function(){if(this.nodeName===(a[d]&&a[d].nodeName)){var f=c.data(a[d++]),e=c.data(this,f);if(f=f&&f.events){delete e.handle;e.events={};for(var i in f)for(var j in f[i])c.event.add(this,i,f[i][j],f[i][j].data)}}})}function S(a,b,d){var f,e,i;b=b&&b[0]?b[0].ownerDocument||b[0]:y;if(a.length===1&&typeof a[0]==="string"&&a[0].length<512&&b===y&&!Fa.test(a[0])&&(c.support.checkClone||!Ga.test(a[0]))){e=
true;if(i=c.fragments[a[0]])if(i!==1)f=i}if(!f){f=b.createDocumentFragment();c.clean(a,b,f,d)}if(e)c.fragments[a[0]]=i?f:1;return{fragment:f,cacheable:e}}function O(a,b){var d={};c.each(Ha.concat.apply([],Ha.slice(0,b)),function(){d[this]=a});return d}function ja(a){return"scrollTo"in a&&a.document?a:a.nodeType===9?a.defaultView||a.parentWindow:false}var c=function(a,b){return new c.fn.init(a,b)},aa=K.jQuery,ia=K.$,y=K.document,ka,x=/^[^<]*(<[\w\W]+>)[^>]*$|^#([\w-]+)$/,na=/^.[^:#\[\.,]*$/,l=/\S/,
o=/^(\s|\u00A0)+|(\s|\u00A0)+$/g,w=/^<(\w+)\s*\/?>(?:<\/\1>)?$/,t=navigator.userAgent,F=false,C=[],$=!!(typeof require!=="undefined"&&require.def),V,T=Object.prototype.toString,ea=Object.prototype.hasOwnProperty,ga=Array.prototype.push,Y=Array.prototype.slice,fa=Array.prototype.indexOf;c.fn=c.prototype={init:function(a,b){var d,f;if(!a)return this;if(a.nodeType){this.context=this[0]=a;this.length=1;return this}if(a==="body"&&!b){this.context=y;this[0]=y.body;this.selector="body";this.length=1;return this}if(typeof a===
"string")if((d=x.exec(a))&&(d[1]||!b))if(d[1]){f=b?b.ownerDocument||b:y;if(a=w.exec(a))if(c.isPlainObject(b)){a=[y.createElement(a[1])];c.fn.attr.call(a,b,true)}else a=[f.createElement(a[1])];else{a=S([d[1]],[f]);a=(a.cacheable?a.fragment.cloneNode(true):a.fragment).childNodes}return c.merge(this,a)}else{if(b=y.getElementById(d[2])){if(b.id!==d[2])return ka.find(a);this.length=1;this[0]=b}this.context=y;this.selector=a;return this}else if(!b&&/^\w+$/.test(a)){this.selector=a;this.context=y;a=y.getElementsByTagName(a);
return c.merge(this,a)}else return!b||b.jquery?(b||ka).find(a):c(b).find(a);else if(c.isFunction(a))return ka.ready(a);if(a.selector!==A){this.selector=a.selector;this.context=a.context}return c.makeArray(a,this)},selector:"",jquery:"1.4.2",length:0,size:function(){return this.length},toArray:function(){return Y.call(this,0)},get:function(a){return a==null?this.toArray():a<0?this.slice(a)[0]:this[a]},pushStack:function(a,b,d){var f=c();c.isArray(a)?ga.apply(f,a):c.merge(f,a);f.prevObject=this;f.context=
this.context;if(b==="find")f.selector=this.selector+(this.selector?" ":"")+d;else if(b)f.selector=this.selector+"."+b+"("+d+")";return f},each:function(a,b){return c.each(this,a,b)},ready:function(a){c.bindReady();if(c.isReady&&(!$||require.s.isDone))a.call(y,c);else{C||(C=[]);C.push(a)}return this},eq:function(a){return a===-1?this.slice(a):this.slice(a,+a+1)},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},slice:function(){return this.pushStack(Y.apply(this,arguments),"slice",
Y.call(arguments).join(","))},map:function(a){return this.pushStack(c.map(this,function(b,d){return a.call(b,d,b)}))},end:function(){return this.prevObject||c(null)},push:ga,sort:[].sort,splice:[].splice};c.fn.init.prototype=c.fn;c.extend=c.fn.extend=function(){var a=arguments[0]||{},b=1,d=arguments.length,f=false,e,i,j,r;if(typeof a==="boolean"){f=a;a=arguments[1]||{};b=2}if(typeof a!=="object"&&!c.isFunction(a))a={};if(d===b){a=this;--b}for(;b<d;b++)if((e=arguments[b])!=null)for(i in e){j=a[i];
r=e[i];if(a!==r)if(f&&r&&(c.isPlainObject(r)||c.isArray(r))){j=j&&(c.isPlainObject(j)||c.isArray(j))?j:c.isArray(r)?[]:{};a[i]=c.extend(f,j,r)}else if(r!==A)a[i]=r}return a};c.extend({noConflict:function(a){K.$=ia;if(a)K.jQuery=aa;return c},isReady:false,ready:function(){if(!c.isReady){if(!y.body)return setTimeout(c.ready,13);c.isReady=true;c.callReady()}},callReady:function(){if(c.isReady&&(!$||require.s.isDone)){if(C){for(var a,b=0;a=C[b++];)a.call(y,c);C=null}c.fn.triggerHandler&&c(y).triggerHandler("ready")}},
bindReady:function(){if(!F){F=true;if(y.readyState==="complete")return c.ready();if(y.addEventListener){y.addEventListener("DOMContentLoaded",V,false);K.addEventListener("load",c.ready,false)}else if(y.attachEvent){y.attachEvent("onreadystatechange",V);K.attachEvent("onload",c.ready);var a=false;try{a=K.frameElement==null}catch(b){}y.documentElement.doScroll&&a&&Z()}}},isFunction:function(a){return T.call(a)==="[object Function]"},isArray:function(a){return T.call(a)==="[object Array]"},isPlainObject:function(a){if(!a||
T.call(a)!=="[object Object]"||a.nodeType||a.setInterval)return false;if(a.constructor&&!ea.call(a,"constructor")&&!ea.call(a.constructor.prototype,"isPrototypeOf"))return false;var b;for(b in a);return b===A||ea.call(a,b)},isEmptyObject:function(a){for(var b in a)return false;return true},error:function(a){throw a;},parseJSON:function(a){if(typeof a!=="string"||!a)return null;a=c.trim(a);if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return K.JSON&&K.JSON.parse?K.JSON.parse(a):(new Function("return "+a))();else c.error("Invalid JSON: "+a)},noop:function(){},globalEval:function(a){if(a&&l.test(a)){var b=y.getElementsByTagName("head")[0]||y.documentElement,d=y.createElement("script");d.type="text/javascript";if(c.support.scriptEval)d.appendChild(y.createTextNode(a));else d.text=a;b.insertBefore(d,b.firstChild);b.removeChild(d)}},nodeName:function(a,b){return a.nodeName&&a.nodeName.toUpperCase()===
b.toUpperCase()},each:function(a,b,d){var f,e=0,i=a.length,j=i===A||c.isFunction(a);if(d)if(j)for(f in a){if(b.apply(a[f],d)===false)break}else for(;e<i;){if(b.apply(a[e++],d)===false)break}else if(j)for(f in a){if(b.call(a[f],f,a[f])===false)break}else for(d=a[0];e<i&&b.call(d,e,d)!==false;d=a[++e]);return a},trim:function(a){return(a||"").replace(o,"")},makeArray:function(a,b){b=b||[];if(a!=null)a.length==null||typeof a==="string"||c.isFunction(a)||typeof a!=="function"&&a.setInterval?ga.call(b,
a):c.merge(b,a);return b},inArray:function(a,b){if(b.indexOf)return b.indexOf(a);for(var d=0,f=b.length;d<f;d++)if(b[d]===a)return d;return-1},merge:function(a,b){var d=a.length,f=0;if(typeof b.length==="number")for(var e=b.length;f<e;f++)a[d++]=b[f];else for(;b[f]!==A;)a[d++]=b[f++];a.length=d;return a},grep:function(a,b,d){for(var f=[],e=0,i=a.length;e<i;e++)!d!==!b(a[e],e)&&f.push(a[e]);return f},map:function(a,b,d){for(var f=[],e,i=0,j=a.length;i<j;i++){e=b(a[i],i,d);if(e!=null)f[f.length]=e}return f.concat.apply([],
f)},guid:1,proxy:function(a,b,d){if(arguments.length===2)if(typeof b==="string"){d=a;a=d[b];b=A}else if(b&&!c.isFunction(b)){d=b;b=A}if(!b&&a)b=function(){return a.apply(d||this,arguments)};if(a)b.guid=a.guid=a.guid||b.guid||c.guid++;return b},uaMatch:function(a){a=a.toLowerCase();a=/(webkit)[ \/]([\w.]+)/.exec(a)||/(opera)(?:.*version)?[ \/]([\w.]+)/.exec(a)||/(msie) ([\w.]+)/.exec(a)||!/compatible/.test(a)&&/(mozilla)(?:.*? rv:([\w.]+))?/.exec(a)||[];return{browser:a[1]||"",version:a[2]||"0"}},
browser:{}});t=c.uaMatch(t);if(t.browser){c.browser[t.browser]=true;c.browser.version=t.version}if(c.browser.webkit)c.browser.safari=true;if(fa)c.inArray=function(a,b){return fa.call(b,a)};ka=c(y);if(y.addEventListener)V=function(){y.removeEventListener("DOMContentLoaded",V,false);c.ready()};else if(y.attachEvent)V=function(){if(y.readyState==="complete"){y.detachEvent("onreadystatechange",V);c.ready()}};(function(){c.support={};var a=y.documentElement,b=y.createElement("script"),d=y.createElement("div"),
f="script"+k();d.style.display="none";d.innerHTML="   <link/><table></table><a href='/a' style='color:red;float:left;opacity:.55;'>a</a><input type='checkbox'/>";var e=d.getElementsByTagName("*"),i=d.getElementsByTagName("a")[0];if(!(!e||!e.length||!i)){c.support={leadingWhitespace:d.firstChild.nodeType===3,tbody:!d.getElementsByTagName("tbody").length,htmlSerialize:!!d.getElementsByTagName("link").length,style:/red/.test(i.getAttribute("style")),hrefNormalized:i.getAttribute("href")==="/a",opacity:/^0.55$/.test(i.style.opacity),
cssFloat:!!i.style.cssFloat,checkOn:d.getElementsByTagName("input")[0].value==="on",optSelected:y.createElement("select").appendChild(y.createElement("option")).selected,parentNode:d.removeChild(d.appendChild(y.createElement("div"))).parentNode===null,deleteExpando:true,checkClone:false,scriptEval:false,noCloneEvent:true,boxModel:null};b.type="text/javascript";try{b.appendChild(y.createTextNode("window."+f+"=1;"))}catch(j){}a.insertBefore(b,a.firstChild);if(K[f]){c.support.scriptEval=true;delete K[f]}try{delete b.test}catch(r){c.support.deleteExpando=
false}a.removeChild(b);if(d.attachEvent&&d.fireEvent){d.attachEvent("onclick",function m(){c.support.noCloneEvent=false;d.detachEvent("onclick",m)});d.cloneNode(true).fireEvent("onclick")}d=y.createElement("div");d.innerHTML="<input type='radio' name='radiotest' checked='checked'/>";a=y.createDocumentFragment();a.appendChild(d.firstChild);c.support.checkClone=a.cloneNode(true).cloneNode(true).lastChild.checked;c(function(){var m=y.createElement("div");m.style.width=m.style.paddingLeft="1px";y.body.appendChild(m);
c.boxModel=c.support.boxModel=m.offsetWidth===2;y.body.removeChild(m).style.display="none"});a=function(m){var q=y.createElement("div");m="on"+m;var z=m in q;if(!z){q.setAttribute(m,"return;");z=typeof q[m]==="function"}return z};c.support.submitBubbles=a("submit");c.support.changeBubbles=a("change");a=b=d=e=i=null}})();c.props={"for":"htmlFor","class":"className",readonly:"readOnly",maxlength:"maxLength",cellspacing:"cellSpacing",rowspan:"rowSpan",colspan:"colSpan",tabindex:"tabIndex",usemap:"useMap",
frameborder:"frameBorder"};var ha="jQuery"+k(),$a=0,Ia={};c.extend({cache:{},expando:ha,noData:{embed:true,object:true,applet:true},data:function(a,b,d){if(!(a.nodeName&&c.noData[a.nodeName.toLowerCase()])){a=a==K?Ia:a;var f=a[ha],e=c.cache;if(!f&&typeof b==="string"&&d===A)return null;f||(f=++$a);if(typeof b==="object"){a[ha]=f;e[f]=c.extend(true,{},b)}else if(!e[f]){a[ha]=f;e[f]={}}a=e[f];if(d!==A)a[b]=d;return typeof b==="string"?a[b]:a}},removeData:function(a,b){if(!(a.nodeName&&c.noData[a.nodeName.toLowerCase()])){a=
a==K?Ia:a;var d=a[ha],f=c.cache,e=f[d];if(b){if(e){delete e[b];c.isEmptyObject(e)&&c.removeData(a)}}else{if(c.support.deleteExpando)delete a[c.expando];else a.removeAttribute&&a.removeAttribute(c.expando);delete f[d]}}}});c.fn.extend({data:function(a,b){if(typeof a==="undefined"&&this.length)return c.data(this[0]);else if(typeof a==="object")return this.each(function(){c.data(this,a)});var d=a.split(".");d[1]=d[1]?"."+d[1]:"";if(b===A){var f=this.triggerHandler("getData"+d[1]+"!",[d[0]]);if(f===A&&
this.length)f=c.data(this[0],a);return f===A&&d[1]?this.data(d[0]):f}else return this.trigger("setData"+d[1]+"!",[d[0],b]).each(function(){c.data(this,a,b)})},removeData:function(a){return this.each(function(){c.removeData(this,a)})}});c.extend({queue:function(a,b,d){if(a){b=(b||"fx")+"queue";var f=c.data(a,b);if(!d)return f||[];if(!f||c.isArray(d))f=c.data(a,b,c.makeArray(d));else f.push(d);return f}},dequeue:function(a,b){b=b||"fx";var d=c.queue(a,b),f=d.shift();if(f==="inprogress")f=d.shift();
if(f){b==="fx"&&d.unshift("inprogress");f.call(a,function(){c.dequeue(a,b)})}}});c.fn.extend({queue:function(a,b){if(typeof a!=="string"){b=a;a="fx"}if(b===A)return c.queue(this[0],a);return this.each(function(){var d=c.queue(this,a,b);a==="fx"&&d[0]!=="inprogress"&&c.dequeue(this,a)})},dequeue:function(a){return this.each(function(){c.dequeue(this,a)})},delay:function(a,b){a=c.fx?c.fx.speeds[a]||a:a;b=b||"fx";return this.queue(b,function(){var d=this;setTimeout(function(){c.dequeue(d,b)},a)})},clearQueue:function(a){return this.queue(a||
"fx",[])}});var Ja=/[\n\t]/g,va=/\s+/,ab=/\r/g,bb=/href|src|style/,cb=/(button|input)/i,db=/(button|input|object|select|textarea)/i,eb=/^(a|area)$/i,Ka=/radio|checkbox/;c.fn.extend({attr:function(a,b){return s(this,a,b,true,c.attr)},removeAttr:function(a){return this.each(function(){c.attr(this,a,"");this.nodeType===1&&this.removeAttribute(a)})},addClass:function(a){if(c.isFunction(a))return this.each(function(q){var z=c(this);z.addClass(a.call(this,q,z.attr("class")))});if(a&&typeof a==="string")for(var b=
(a||"").split(va),d=0,f=this.length;d<f;d++){var e=this[d];if(e.nodeType===1)if(e.className){for(var i=" "+e.className+" ",j=e.className,r=0,m=b.length;r<m;r++)if(i.indexOf(" "+b[r]+" ")<0)j+=" "+b[r];e.className=c.trim(j)}else e.className=a}return this},removeClass:function(a){if(c.isFunction(a))return this.each(function(m){var q=c(this);q.removeClass(a.call(this,m,q.attr("class")))});if(a&&typeof a==="string"||a===A)for(var b=(a||"").split(va),d=0,f=this.length;d<f;d++){var e=this[d];if(e.nodeType===
1&&e.className)if(a){for(var i=(" "+e.className+" ").replace(Ja," "),j=0,r=b.length;j<r;j++)i=i.replace(" "+b[j]+" "," ");e.className=c.trim(i)}else e.className=""}return this},toggleClass:function(a,b){var d=typeof a,f=typeof b==="boolean";if(c.isFunction(a))return this.each(function(e){var i=c(this);i.toggleClass(a.call(this,e,i.attr("class"),b),b)});return this.each(function(){if(d==="string")for(var e,i=0,j=c(this),r=b,m=a.split(va);e=m[i++];){r=f?r:!j.hasClass(e);j[r?"addClass":"removeClass"](e)}else if(d===
"undefined"||d==="boolean"){this.className&&c.data(this,"__className__",this.className);this.className=this.className||a===false?"":c.data(this,"__className__")||""}})},hasClass:function(a){a=" "+a+" ";for(var b=0,d=this.length;b<d;b++)if((" "+this[b].className+" ").replace(Ja," ").indexOf(a)>-1)return true;return false},val:function(a){if(a===A){var b=this[0];if(b){if(c.nodeName(b,"option"))return(b.attributes.value||{}).specified?b.value:b.text;if(c.nodeName(b,"select")){var d=b.selectedIndex,f=
[],e=b.options;b=b.type==="select-one";if(d<0)return null;var i=b?d:0;for(d=b?d+1:e.length;i<d;i++){var j=e[i];if(j.selected){a=c(j).val();if(b)return a;f.push(a)}}return f}if(Ka.test(b.type)&&!c.support.checkOn)return b.getAttribute("value")===null?"on":b.value;return(b.value||"").replace(ab,"")}return A}var r=c.isFunction(a);return this.each(function(m){var q=c(this),z=a;if(this.nodeType===1){if(r)z=a.call(this,m,q.val());if(typeof z==="number")z+="";if(c.isArray(z)&&Ka.test(this.type))this.checked=
c.inArray(q.val(),z)>=0;else if(c.nodeName(this,"select")){var I=c.makeArray(z);c("option",this).each(function(){this.selected=c.inArray(c(this).val(),I)>=0});if(!I.length)this.selectedIndex=-1}else this.value=z}})}});c.extend({attrFn:{val:true,css:true,html:true,text:true,data:true,width:true,height:true,offset:true},attr:function(a,b,d,f){if(!a||a.nodeType===3||a.nodeType===8)return A;if(f&&b in c.attrFn)return c(a)[b](d);f=a.nodeType!==1||!c.isXMLDoc(a);var e=d!==A;b=f&&c.props[b]||b;if(a.nodeType===
1){var i=bb.test(b);if(b in a&&f&&!i){if(e){b==="type"&&cb.test(a.nodeName)&&a.parentNode&&c.error("type property can't be changed");a[b]=d}if(c.nodeName(a,"form")&&a.getAttributeNode(b))return a.getAttributeNode(b).nodeValue;if(b==="tabIndex")return(b=a.getAttributeNode("tabIndex"))&&b.specified?b.value:db.test(a.nodeName)||eb.test(a.nodeName)&&a.href?0:A;return a[b]}if(!c.support.style&&f&&b==="style"){if(e)a.style.cssText=""+d;return a.style.cssText}e&&a.setAttribute(b,""+d);a=!c.support.hrefNormalized&&
f&&i?a.getAttribute(b,2):a.getAttribute(b);return a===null?A:a}return c.style(a,b,d)}});var qa=/\.(.*)$/,fb=function(a){return a.replace(/[^\w\s\.\|`]/g,function(b){return"\\"+b})};c.event={add:function(a,b,d,f){if(!(a.nodeType===3||a.nodeType===8)){if(a.setInterval&&a!==K&&!a.frameElement)a=K;var e,i;if(d.handler){e=d;d=e.handler}if(!d.guid)d.guid=c.guid++;if(i=c.data(a)){var j=i.events=i.events||{},r=i.handle;if(!r)i.handle=r=function(){return typeof c!=="undefined"&&!c.event.triggered?c.event.handle.apply(r.elem,
arguments):A};r.elem=a;b=b.split(" ");for(var m,q=0,z;m=b[q++];){i=e?c.extend({},e):{handler:d,data:f};if(m.indexOf(".")>-1){z=m.split(".");m=z.shift();i.namespace=z.slice(0).sort().join(".")}else{z=[];i.namespace=""}i.type=m;i.guid=d.guid;var I=j[m],N=c.event.special[m]||{};if(!I){I=j[m]=[];if(!N.setup||N.setup.call(a,f,z,r)===false)if(a.addEventListener)a.addEventListener(m,r,false);else a.attachEvent&&a.attachEvent("on"+m,r)}if(N.add){N.add.call(a,i);if(!i.handler.guid)i.handler.guid=d.guid}I.push(i);
c.event.global[m]=true}a=null}}},global:{},remove:function(a,b,d,f){if(!(a.nodeType===3||a.nodeType===8)){var e,i=0,j,r,m,q,z,I,N=c.data(a),X=N&&N.events;if(N&&X){if(b&&b.type){d=b.handler;b=b.type}if(!b||typeof b==="string"&&b.charAt(0)==="."){b=b||"";for(e in X)c.event.remove(a,e+b)}else{for(b=b.split(" ");e=b[i++];){q=e;j=e.indexOf(".")<0;r=[];if(!j){r=e.split(".");e=r.shift();m=new RegExp("(^|\\.)"+c.map(r.slice(0).sort(),fb).join("\\.(?:.*\\.)?")+"(\\.|$)")}if(z=X[e])if(d){q=c.event.special[e]||
{};for(U=f||0;U<z.length;U++){I=z[U];if(d.guid===I.guid){if(j||m.test(I.namespace)){f==null&&z.splice(U--,1);q.remove&&q.remove.call(a,I)}if(f!=null)break}}if(z.length===0||f!=null&&z.length===1){if(!q.teardown||q.teardown.call(a,r)===false)La(a,e,N.handle);delete X[e]}}else for(var U=0;U<z.length;U++){I=z[U];if(j||m.test(I.namespace)){c.event.remove(a,q,I.handler,U);z.splice(U--,1)}}}if(c.isEmptyObject(X)){if(b=N.handle)b.elem=null;delete N.events;delete N.handle;c.isEmptyObject(N)&&c.removeData(a)}}}}},
trigger:function(a,b,d,f){var e=a.type||a;if(!f){a=typeof a==="object"?a[ha]?a:c.extend(c.Event(e),a):c.Event(e);if(e.indexOf("!")>=0){a.type=e=e.slice(0,-1);a.exclusive=true}if(!d){a.stopPropagation();c.event.global[e]&&c.each(c.cache,function(){this.events&&this.events[e]&&c.event.trigger(a,b,this.handle.elem)})}if(!d||d.nodeType===3||d.nodeType===8)return A;a.result=A;a.target=d;b=c.makeArray(b);b.unshift(a)}a.currentTarget=d;(f=c.data(d,"handle"))&&f.apply(d,b);f=d.parentNode||d.ownerDocument;
try{if(!(d&&d.nodeName&&c.noData[d.nodeName.toLowerCase()]))if(d["on"+e]&&d["on"+e].apply(d,b)===false)a.result=false}catch(i){}if(!a.isPropagationStopped()&&f)c.event.trigger(a,b,f,true);else if(!a.isDefaultPrevented()){f=a.target;var j,r=c.nodeName(f,"a")&&e==="click",m=c.event.special[e]||{};if((!m._default||m._default.call(d,a)===false)&&!r&&!(f&&f.nodeName&&c.noData[f.nodeName.toLowerCase()])){try{if(f[e]){if(j=f["on"+e])f["on"+e]=null;c.event.triggered=true;f[e]()}}catch(q){}if(j)f["on"+e]=
j;c.event.triggered=false}}},handle:function(a){var b,d,f,e;a=arguments[0]=c.event.fix(a||K.event);a.currentTarget=this;b=a.type.indexOf(".")<0&&!a.exclusive;if(!b){d=a.type.split(".");a.type=d.shift();f=new RegExp("(^|\\.)"+d.slice(0).sort().join("\\.(?:.*\\.)?")+"(\\.|$)")}e=c.data(this,"events");d=e[a.type];if(e&&d){d=d.slice(0);e=0;for(var i=d.length;e<i;e++){var j=d[e];if(b||f.test(j.namespace)){a.handler=j.handler;a.data=j.data;a.handleObj=j;j=j.handler.apply(this,arguments);if(j!==A){a.result=
j;if(j===false){a.preventDefault();a.stopPropagation()}}if(a.isImmediatePropagationStopped())break}}}return a.result},props:"altKey attrChange attrName bubbles button cancelable charCode clientX clientY ctrlKey currentTarget data detail eventPhase fromElement handler keyCode layerX layerY metaKey newValue offsetX offsetY originalTarget pageX pageY prevValue relatedNode relatedTarget screenX screenY shiftKey srcElement target toElement view wheelDelta which".split(" "),fix:function(a){if(a[ha])return a;
var b=a;a=c.Event(b);for(var d=this.props.length,f;d;){f=this.props[--d];a[f]=b[f]}if(!a.target)a.target=a.srcElement||y;if(a.target.nodeType===3)a.target=a.target.parentNode;if(!a.relatedTarget&&a.fromElement)a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;if(a.pageX==null&&a.clientX!=null){b=y.documentElement;d=y.body;a.pageX=a.clientX+(b&&b.scrollLeft||d&&d.scrollLeft||0)-(b&&b.clientLeft||d&&d.clientLeft||0);a.pageY=a.clientY+(b&&b.scrollTop||d&&d.scrollTop||0)-(b&&b.clientTop||
d&&d.clientTop||0)}if(!a.which&&(a.charCode||a.charCode===0?a.charCode:a.keyCode))a.which=a.charCode||a.keyCode;if(!a.metaKey&&a.ctrlKey)a.metaKey=a.ctrlKey;if(!a.which&&a.button!==A)a.which=a.button&1?1:a.button&2?3:a.button&4?2:0;return a},guid:1E8,proxy:c.proxy,special:{ready:{setup:c.bindReady,teardown:c.noop},live:{add:function(a){c.event.add(this,a.origType,c.extend({},a,{handler:Q}))},remove:function(a){var b=true,d=a.origType.replace(qa,"");c.each(c.data(this,"events").live||[],function(){if(d===
this.origType.replace(qa,""))return b=false});b&&c.event.remove(this,a.origType,Q)}},beforeunload:{setup:function(a,b,d){if(this.setInterval)this.onbeforeunload=d;return false},teardown:function(a,b){if(this.onbeforeunload===b)this.onbeforeunload=null}}}};var La=y.removeEventListener?function(a,b,d){a.removeEventListener(b,d,false)}:function(a,b,d){a.detachEvent("on"+b,d)};c.Event=function(a){if(!this.preventDefault)return new c.Event(a);if(a&&a.type){this.originalEvent=a;this.type=a.type}else this.type=
a;this.timeStamp=k();this[ha]=true};c.Event.prototype={preventDefault:function(){this.isDefaultPrevented=E;var a=this.originalEvent;if(a){a.preventDefault&&a.preventDefault();a.returnValue=false}},stopPropagation:function(){this.isPropagationStopped=E;var a=this.originalEvent;if(a){a.stopPropagation&&a.stopPropagation();a.cancelBubble=true}},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=E;this.stopPropagation()},isDefaultPrevented:D,isPropagationStopped:D,isImmediatePropagationStopped:D};
var Ma=function(a){var b=a.relatedTarget;try{for(;b&&b!==this;)b=b.parentNode;if(b!==this){a.type=a.data;c.event.handle.apply(this,arguments)}}catch(d){}},Na=function(a){a.type=a.data;c.event.handle.apply(this,arguments)};c.each({mouseenter:"mouseover",mouseleave:"mouseout"},function(a,b){c.event.special[a]={setup:function(d){c.event.add(this,b,d&&d.selector?Na:Ma,a)},teardown:function(d){c.event.remove(this,b,d&&d.selector?Na:Ma)}}});if(!c.support.submitBubbles)c.event.special.submit={setup:function(){if(this.nodeName.toLowerCase()!==
"form"){c.event.add(this,"click.specialSubmit",function(a){var b=a.target,d=b.type;if((d==="submit"||d==="image")&&c(b).closest("form").length)return G("submit",this,arguments)});c.event.add(this,"keypress.specialSubmit",function(a){var b=a.target,d=b.type;if((d==="text"||d==="password")&&c(b).closest("form").length&&a.keyCode===13)return G("submit",this,arguments)})}else return false},teardown:function(){c.event.remove(this,".specialSubmit")}};if(!c.support.changeBubbles){var wa=/textarea|input|select/i,
xa,Oa=function(a){var b=a.type,d=a.value;if(b==="radio"||b==="checkbox")d=a.checked;else if(b==="select-multiple")d=a.selectedIndex>-1?c.map(a.options,function(f){return f.selected}).join("-"):"";else if(a.nodeName.toLowerCase()==="select")d=a.selectedIndex;return d},ya=function(a,b){var d=a.target,f,e;if(!(!wa.test(d.nodeName)||d.readOnly)){f=c.data(d,"_change_data");e=Oa(d);if(a.type!=="focusout"||d.type!=="radio")c.data(d,"_change_data",e);if(!(f===A||e===f))if(f!=null||e){a.type="change";return c.event.trigger(a,
b,d)}}};c.event.special.change={filters:{focusout:ya,click:function(a){var b=a.target,d=b.type;if(d==="radio"||d==="checkbox"||b.nodeName.toLowerCase()==="select")return ya.call(this,a)},keydown:function(a){var b=a.target,d=b.type;if(a.keyCode===13&&b.nodeName.toLowerCase()!=="textarea"||a.keyCode===32&&(d==="checkbox"||d==="radio")||d==="select-multiple")return ya.call(this,a)},beforeactivate:function(a){a=a.target;c.data(a,"_change_data",Oa(a))}},setup:function(){if(this.type==="file")return false;
for(var a in xa)c.event.add(this,a+".specialChange",xa[a]);return wa.test(this.nodeName)},teardown:function(){c.event.remove(this,".specialChange");return wa.test(this.nodeName)}};xa=c.event.special.change.filters}y.addEventListener&&c.each({focus:"focusin",blur:"focusout"},function(a,b){function d(f){f=c.event.fix(f);f.type=b;return c.event.handle.call(this,f)}c.event.special[b]={setup:function(){this.addEventListener(a,d,true)},teardown:function(){this.removeEventListener(a,d,true)}}});c.each(["bind",
"one"],function(a,b){c.fn[b]=function(d,f,e){if(typeof d==="object"){for(var i in d)this[b](i,f,d[i],e);return this}if(c.isFunction(f)){e=f;f=A}var j=b==="one"?c.proxy(e,function(m){c(this).unbind(m,j);return e.apply(this,arguments)}):e;if(d==="unload"&&b!=="one")this.one(d,f,e);else{i=0;for(var r=this.length;i<r;i++)c.event.add(this[i],d,j,f)}return this}});c.fn.extend({unbind:function(a,b){if(typeof a==="object"&&!a.preventDefault)for(var d in a)this.unbind(d,a[d]);else{d=0;for(var f=this.length;d<
f;d++)c.event.remove(this[d],a,b)}return this},delegate:function(a,b,d,f){return this.live(b,d,f,a)},undelegate:function(a,b,d){return arguments.length===0?this.unbind("live"):this.die(b,null,d,a)},trigger:function(a,b){return this.each(function(){c.event.trigger(a,b,this)})},triggerHandler:function(a,b){if(this[0]){a=c.Event(a);a.preventDefault();a.stopPropagation();c.event.trigger(a,b,this[0]);return a.result}},toggle:function(a){for(var b=arguments,d=1;d<b.length;)c.proxy(a,b[d++]);return this.click(c.proxy(a,
function(f){var e=(c.data(this,"lastToggle"+a.guid)||0)%d;c.data(this,"lastToggle"+a.guid,e+1);f.preventDefault();return b[e].apply(this,arguments)||false}))},hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});var Pa={focus:"focusin",blur:"focusout",mouseenter:"mouseover",mouseleave:"mouseout"};c.each(["live","die"],function(a,b){c.fn[b]=function(d,f,e,i){var j,r=0,m,q,z=i||this.selector,I=i?this:c(this.context);if(c.isFunction(f)){e=f;f=A}for(d=(d||"").split(" ");(j=d[r++])!=null;){i=
qa.exec(j);m="";if(i){m=i[0];j=j.replace(qa,"")}if(j==="hover")d.push("mouseenter"+m,"mouseleave"+m);else{q=j;if(j==="focus"||j==="blur"){d.push(Pa[j]+m);j+=m}else j=(Pa[j]||j)+m;b==="live"?I.each(function(){c.event.add(this,R(j,z),{data:f,selector:z,handler:e,origType:j,origHandler:e,preType:q})}):I.unbind(R(j,z),e)}}return this}});c.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error".split(" "),
function(a,b){c.fn[b]=function(d){return d?this.bind(b,d):this.trigger(b)};if(c.attrFn)c.attrFn[b]=true});K.attachEvent&&!K.addEventListener&&K.attachEvent("onunload",function(){for(var a in c.cache)if(c.cache[a].handle)try{c.event.remove(c.cache[a].handle.elem)}catch(b){}});(function(){function a(g){for(var h="",n,p=0;g[p];p++){n=g[p];if(n.nodeType===3||n.nodeType===4)h+=n.nodeValue;else if(n.nodeType!==8)h+=a(n.childNodes)}return h}function b(g,h,n,p,v,u){v=0;for(var J=p.length;v<J;v++){var H=p[v];
if(H){H=H[g];for(var M=false;H;){if(H.sizcache===n){M=p[H.sizset];break}if(H.nodeType===1&&!u){H.sizcache=n;H.sizset=v}if(H.nodeName.toLowerCase()===h){M=H;break}H=H[g]}p[v]=M}}}function d(g,h,n,p,v,u){v=0;for(var J=p.length;v<J;v++){var H=p[v];if(H){H=H[g];for(var M=false;H;){if(H.sizcache===n){M=p[H.sizset];break}if(H.nodeType===1){if(!u){H.sizcache=n;H.sizset=v}if(typeof h!=="string"){if(H===h){M=true;break}}else if(m.filter(h,[H]).length>0){M=H;break}}H=H[g]}p[v]=M}}}var f=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^[\]]*\]|['"][^'"]*['"]|[^[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,
e=0,i=Object.prototype.toString,j=false,r=true;[0,0].sort(function(){r=false;return 0});var m=function(g,h,n,p){n=n||[];var v=h=h||y;if(h.nodeType!==1&&h.nodeType!==9)return[];if(!g||typeof g!=="string")return n;for(var u=[],J,H,M,ra,la=true,oa=L(h),ma=g;(f.exec(""),J=f.exec(ma))!==null;){ma=J[3];u.push(J[1]);if(J[2]){ra=J[3];break}}if(u.length>1&&z.exec(g))if(u.length===2&&q.relative[u[0]])H=za(u[0]+u[1],h);else for(H=q.relative[u[0]]?[h]:m(u.shift(),h);u.length;){g=u.shift();if(q.relative[g])g+=
u.shift();H=za(g,H)}else{if(!p&&u.length>1&&h.nodeType===9&&!oa&&q.match.ID.test(u[0])&&!q.match.ID.test(u[u.length-1])){J=m.find(u.shift(),h,oa);h=J.expr?m.filter(J.expr,J.set)[0]:J.set[0]}if(h){J=p?{expr:u.pop(),set:N(p)}:m.find(u.pop(),u.length===1&&(u[0]==="~"||u[0]==="+")&&h.parentNode?h.parentNode:h,oa);H=J.expr?m.filter(J.expr,J.set):J.set;if(u.length>0)M=N(H);else la=false;for(;u.length;){var ba=u.pop();J=ba;if(q.relative[ba])J=u.pop();else ba="";if(J==null)J=h;q.relative[ba](M,J,oa)}}else M=
[]}M||(M=H);M||m.error(ba||g);if(i.call(M)==="[object Array]")if(la)if(h&&h.nodeType===1)for(g=0;M[g]!=null;g++){if(M[g]&&(M[g]===true||M[g].nodeType===1&&ca(h,M[g])))n.push(H[g])}else for(g=0;M[g]!=null;g++)M[g]&&M[g].nodeType===1&&n.push(H[g]);else n.push.apply(n,M);else N(M,n);if(ra){m(ra,v,n,p);m.uniqueSort(n)}return n};m.uniqueSort=function(g){if(U){j=r;g.sort(U);if(j)for(var h=1;h<g.length;h++)g[h]===g[h-1]&&g.splice(h--,1)}return g};m.matches=function(g,h){return m(g,null,null,h)};m.find=function(g,
h,n){var p,v;if(!g)return[];for(var u=0,J=q.order.length;u<J;u++){var H=q.order[u];if(v=q.leftMatch[H].exec(g)){var M=v[1];v.splice(1,1);if(M.substr(M.length-1)!=="\\"){v[1]=(v[1]||"").replace(/\\/g,"");p=q.find[H](v,h,n);if(p!=null){g=g.replace(q.match[H],"");break}}}}p||(p=h.getElementsByTagName("*"));return{set:p,expr:g}};m.filter=function(g,h,n,p){for(var v=g,u=[],J=h,H,M,ra=h&&h[0]&&L(h[0]);g&&h.length;){for(var la in q.filter)if((H=q.leftMatch[la].exec(g))!=null&&H[2]){var oa=q.filter[la],ma,
ba;ba=H[1];M=false;H.splice(1,1);if(ba.substr(ba.length-1)!=="\\"){if(J===u)u=[];if(q.preFilter[la])if(H=q.preFilter[la](H,J,n,u,p,ra)){if(H===true)continue}else M=ma=true;if(H)for(var sa=0;(ba=J[sa])!=null;sa++)if(ba){ma=oa(ba,H,sa,J);var Qa=p^!!ma;if(n&&ma!=null)if(Qa)M=true;else J[sa]=false;else if(Qa){u.push(ba);M=true}}if(ma!==A){n||(J=u);g=g.replace(q.match[la],"");if(!M)return[];break}}}if(g===v)if(M==null)m.error(g);else break;v=g}return J};m.error=function(g){throw"Syntax error, unrecognized expression: "+
g;};var q=m.selectors={order:["ID","NAME","TAG"],match:{ID:/#((?:[\w\u00c0-\uFFFF-]|\\.)+)/,CLASS:/\.((?:[\w\u00c0-\uFFFF-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u00c0-\uFFFF-]|\\.)+)['"]*\]/,ATTR:/\[\s*((?:[\w\u00c0-\uFFFF-]|\\.)+)\s*(?:(\S?=)\s*(['"]*)(.*?)\3|)\s*\]/,TAG:/^((?:[\w\u00c0-\uFFFF\*-]|\\.)+)/,CHILD:/:(only|nth|last|first)-child(?:\((even|odd|[\dn+-]*)\))?/,POS:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^-]|$)/,PSEUDO:/:((?:[\w\u00c0-\uFFFF-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},
leftMatch:{},attrMap:{"class":"className","for":"htmlFor"},attrHandle:{href:function(g){return g.getAttribute("href")}},relative:{"+":function(g,h){var n=typeof h==="string",p=n&&!/\W/.test(h);n=n&&!p;if(p)h=h.toLowerCase();p=0;for(var v=g.length,u;p<v;p++)if(u=g[p]){for(;(u=u.previousSibling)&&u.nodeType!==1;);g[p]=n||u&&u.nodeName.toLowerCase()===h?u||false:u===h}n&&m.filter(h,g,true)},">":function(g,h){var n=typeof h==="string";if(n&&!/\W/.test(h)){h=h.toLowerCase();for(var p=0,v=g.length;p<v;p++){var u=
g[p];if(u){n=u.parentNode;g[p]=n.nodeName.toLowerCase()===h?n:false}}}else{p=0;for(v=g.length;p<v;p++)if(u=g[p])g[p]=n?u.parentNode:u.parentNode===h;n&&m.filter(h,g,true)}},"":function(g,h,n){var p=e++,v=d;if(typeof h==="string"&&!/\W/.test(h)){var u=h=h.toLowerCase();v=b}v("parentNode",h,p,g,u,n)},"~":function(g,h,n){var p=e++,v=d;if(typeof h==="string"&&!/\W/.test(h)){var u=h=h.toLowerCase();v=b}v("previousSibling",h,p,g,u,n)}},find:{ID:function(g,h,n){if(typeof h.getElementById!=="undefined"&&
!n)return(g=h.getElementById(g[1]))?[g]:[]},NAME:function(g,h){if(typeof h.getElementsByName!=="undefined"){var n=[];h=h.getElementsByName(g[1]);for(var p=0,v=h.length;p<v;p++)h[p].getAttribute("name")===g[1]&&n.push(h[p]);return n.length===0?null:n}},TAG:function(g,h){return h.getElementsByTagName(g[1])}},preFilter:{CLASS:function(g,h,n,p,v,u){g=" "+g[1].replace(/\\/g,"")+" ";if(u)return g;u=0;for(var J;(J=h[u])!=null;u++)if(J)if(v^(J.className&&(" "+J.className+" ").replace(/[\t\n]/g," ").indexOf(g)>=
0))n||p.push(J);else if(n)h[u]=false;return false},ID:function(g){return g[1].replace(/\\/g,"")},TAG:function(g){return g[1].toLowerCase()},CHILD:function(g){if(g[1]==="nth"){var h=/(-?)(\d*)n((?:\+|-)?\d*)/.exec(g[2]==="even"&&"2n"||g[2]==="odd"&&"2n+1"||!/\D/.test(g[2])&&"0n+"+g[2]||g[2]);g[2]=h[1]+(h[2]||1)-0;g[3]=h[3]-0}g[0]=e++;return g},ATTR:function(g,h,n,p,v,u){h=g[1].replace(/\\/g,"");if(!u&&q.attrMap[h])g[1]=q.attrMap[h];if(g[2]==="~=")g[4]=" "+g[4]+" ";return g},PSEUDO:function(g,h,n,p,
v){if(g[1]==="not")if((f.exec(g[3])||"").length>1||/^\w/.test(g[3]))g[3]=m(g[3],null,null,h);else{g=m.filter(g[3],h,n,true^v);n||p.push.apply(p,g);return false}else if(q.match.POS.test(g[0])||q.match.CHILD.test(g[0]))return true;return g},POS:function(g){g.unshift(true);return g}},filters:{enabled:function(g){return g.disabled===false&&g.type!=="hidden"},disabled:function(g){return g.disabled===true},checked:function(g){return g.checked===true},selected:function(g){return g.selected===true},parent:function(g){return!!g.firstChild},
empty:function(g){return!g.firstChild},has:function(g,h,n){return!!m(n[3],g).length},header:function(g){return/h\d/i.test(g.nodeName)},text:function(g){return"text"===g.type},radio:function(g){return"radio"===g.type},checkbox:function(g){return"checkbox"===g.type},file:function(g){return"file"===g.type},password:function(g){return"password"===g.type},submit:function(g){return"submit"===g.type},image:function(g){return"image"===g.type},reset:function(g){return"reset"===g.type},button:function(g){return"button"===
g.type||g.nodeName.toLowerCase()==="button"},input:function(g){return/input|select|textarea|button/i.test(g.nodeName)}},setFilters:{first:function(g,h){return h===0},last:function(g,h,n,p){return h===p.length-1},even:function(g,h){return h%2===0},odd:function(g,h){return h%2===1},lt:function(g,h,n){return h<n[3]-0},gt:function(g,h,n){return h>n[3]-0},nth:function(g,h,n){return n[3]-0===h},eq:function(g,h,n){return n[3]-0===h}},filter:{PSEUDO:function(g,h,n,p){var v=h[1],u=q.filters[v];if(u)return u(g,
n,h,p);else if(v==="contains")return(g.textContent||g.innerText||a([g])||"").indexOf(h[3])>=0;else if(v==="not"){h=h[3];n=0;for(p=h.length;n<p;n++)if(h[n]===g)return false;return true}else m.error("Syntax error, unrecognized expression: "+v)},CHILD:function(g,h){var n=h[1],p=g;switch(n){case "only":case "first":for(;p=p.previousSibling;)if(p.nodeType===1)return false;if(n==="first")return true;p=g;case "last":for(;p=p.nextSibling;)if(p.nodeType===1)return false;return true;case "nth":n=h[2];var v=
h[3];if(n===1&&v===0)return true;h=h[0];var u=g.parentNode;if(u&&(u.sizcache!==h||!g.nodeIndex)){var J=0;for(p=u.firstChild;p;p=p.nextSibling)if(p.nodeType===1)p.nodeIndex=++J;u.sizcache=h}g=g.nodeIndex-v;return n===0?g===0:g%n===0&&g/n>=0}},ID:function(g,h){return g.nodeType===1&&g.getAttribute("id")===h},TAG:function(g,h){return h==="*"&&g.nodeType===1||g.nodeName.toLowerCase()===h},CLASS:function(g,h){return(" "+(g.className||g.getAttribute("class"))+" ").indexOf(h)>-1},ATTR:function(g,h){var n=
h[1];g=q.attrHandle[n]?q.attrHandle[n](g):g[n]!=null?g[n]:g.getAttribute(n);n=g+"";var p=h[2];h=h[4];return g==null?p==="!=":p==="="?n===h:p==="*="?n.indexOf(h)>=0:p==="~="?(" "+n+" ").indexOf(h)>=0:!h?n&&g!==false:p==="!="?n!==h:p==="^="?n.indexOf(h)===0:p==="$="?n.substr(n.length-h.length)===h:p==="|="?n===h||n.substr(0,h.length+1)===h+"-":false},POS:function(g,h,n,p){var v=q.setFilters[h[2]];if(v)return v(g,n,h,p)}}},z=q.match.POS;for(var I in q.match){q.match[I]=new RegExp(q.match[I].source+/(?![^\[]*\])(?![^\(]*\))/.source);
q.leftMatch[I]=new RegExp(/(^(?:.|\r|\n)*?)/.source+q.match[I].source.replace(/\\(\d+)/g,function(g,h){return"\\"+(h-0+1)}))}var N=function(g,h){g=Array.prototype.slice.call(g,0);if(h){h.push.apply(h,g);return h}return g};try{Array.prototype.slice.call(y.documentElement.childNodes,0)}catch(X){N=function(g,h){h=h||[];if(i.call(g)==="[object Array]")Array.prototype.push.apply(h,g);else if(typeof g.length==="number")for(var n=0,p=g.length;n<p;n++)h.push(g[n]);else for(n=0;g[n];n++)h.push(g[n]);return h}}var U;
if(y.documentElement.compareDocumentPosition)U=function(g,h){if(!g.compareDocumentPosition||!h.compareDocumentPosition){if(g==h)j=true;return g.compareDocumentPosition?-1:1}g=g.compareDocumentPosition(h)&4?-1:g===h?0:1;if(g===0)j=true;return g};else if("sourceIndex"in y.documentElement)U=function(g,h){if(!g.sourceIndex||!h.sourceIndex){if(g==h)j=true;return g.sourceIndex?-1:1}g=g.sourceIndex-h.sourceIndex;if(g===0)j=true;return g};else if(y.createRange)U=function(g,h){if(!g.ownerDocument||!h.ownerDocument){if(g==
h)j=true;return g.ownerDocument?-1:1}var n=g.ownerDocument.createRange(),p=h.ownerDocument.createRange();n.setStart(g,0);n.setEnd(g,0);p.setStart(h,0);p.setEnd(h,0);g=n.compareBoundaryPoints(Range.START_TO_END,p);if(g===0)j=true;return g};(function(){var g=y.createElement("div"),h="script"+(new Date).getTime();g.innerHTML="<a name='"+h+"'/>";var n=y.documentElement;n.insertBefore(g,n.firstChild);if(y.getElementById(h)){q.find.ID=function(p,v,u){if(typeof v.getElementById!=="undefined"&&!u)return(v=
v.getElementById(p[1]))?v.id===p[1]||typeof v.getAttributeNode!=="undefined"&&v.getAttributeNode("id").nodeValue===p[1]?[v]:A:[]};q.filter.ID=function(p,v){var u=typeof p.getAttributeNode!=="undefined"&&p.getAttributeNode("id");return p.nodeType===1&&u&&u.nodeValue===v}}n.removeChild(g);n=g=null})();(function(){var g=y.createElement("div");g.appendChild(y.createComment(""));if(g.getElementsByTagName("*").length>0)q.find.TAG=function(h,n){n=n.getElementsByTagName(h[1]);if(h[1]==="*"){h=[];for(var p=
0;n[p];p++)n[p].nodeType===1&&h.push(n[p]);n=h}return n};g.innerHTML="<a href='#'></a>";if(g.firstChild&&typeof g.firstChild.getAttribute!=="undefined"&&g.firstChild.getAttribute("href")!=="#")q.attrHandle.href=function(h){return h.getAttribute("href",2)};g=null})();y.querySelectorAll&&function(){var g=m,h=y.createElement("div");h.innerHTML="<p class='TEST'></p>";if(!(h.querySelectorAll&&h.querySelectorAll(".TEST").length===0)){m=function(p,v,u,J){v=v||y;if(!J&&v.nodeType===9&&!L(v))try{return N(v.querySelectorAll(p),
u)}catch(H){}return g(p,v,u,J)};for(var n in g)m[n]=g[n];h=null}}();(function(){var g=y.createElement("div");g.innerHTML="<div class='test e'></div><div class='test'></div>";if(!(!g.getElementsByClassName||g.getElementsByClassName("e").length===0)){g.lastChild.className="e";if(g.getElementsByClassName("e").length!==1){q.order.splice(1,0,"CLASS");q.find.CLASS=function(h,n,p){if(typeof n.getElementsByClassName!=="undefined"&&!p)return n.getElementsByClassName(h[1])};g=null}}})();var ca=y.compareDocumentPosition?
function(g,h){return!!(g.compareDocumentPosition(h)&16)}:function(g,h){return g!==h&&(g.contains?g.contains(h):true)},L=function(g){return(g=(g?g.ownerDocument||g:0).documentElement)?g.nodeName!=="HTML":false},za=function(g,h){var n=[],p="",v;for(h=h.nodeType?[h]:h;v=q.match.PSEUDO.exec(g);){p+=v[0];g=g.replace(q.match.PSEUDO,"")}g=q.relative[g]?g+"*":g;v=0;for(var u=h.length;v<u;v++)m(g,h[v],n);return m.filter(p,n)};c.find=m;c.expr=m.selectors;c.expr[":"]=c.expr.filters;c.unique=m.uniqueSort;c.text=
a;c.isXMLDoc=L;c.contains=ca})();var gb=/Until$/,hb=/^(?:parents|prevUntil|prevAll)/,ib=/,/;Y=Array.prototype.slice;var Ra=function(a,b,d){if(c.isFunction(b))return c.grep(a,function(e,i){return!!b.call(e,i,e)===d});else if(b.nodeType)return c.grep(a,function(e){return e===b===d});else if(typeof b==="string"){var f=c.grep(a,function(e){return e.nodeType===1});if(na.test(b))return c.filter(b,f,!d);else b=c.filter(b,f)}return c.grep(a,function(e){return c.inArray(e,b)>=0===d})};c.fn.extend({find:function(a){for(var b=
this.pushStack("","find",a),d=0,f=0,e=this.length;f<e;f++){d=b.length;c.find(a,this[f],b);if(f>0)for(var i=d;i<b.length;i++)for(var j=0;j<d;j++)if(b[j]===b[i]){b.splice(i--,1);break}}return b},has:function(a){var b=c(a);return this.filter(function(){for(var d=0,f=b.length;d<f;d++)if(c.contains(this,b[d]))return true})},not:function(a){return this.pushStack(Ra(this,a,false),"not",a)},filter:function(a){return this.pushStack(Ra(this,a,true),"filter",a)},is:function(a){return!!a&&c.filter(a,this).length>
0},closest:function(a,b){if(c.isArray(a)){var d=[],f=this[0],e,i={},j;if(f&&a.length){e=0;for(var r=a.length;e<r;e++){j=a[e];i[j]||(i[j]=c.expr.match.POS.test(j)?c(j,b||this.context):j)}for(;f&&f.ownerDocument&&f!==b;){for(j in i){e=i[j];if(e.jquery?e.index(f)>-1:c(f).is(e)){d.push({selector:j,elem:f});delete i[j]}}f=f.parentNode}}return d}var m=c.expr.match.POS.test(a)?c(a,b||this.context):null;return this.map(function(q,z){for(;z&&z.ownerDocument&&z!==b;){if(m?m.index(z)>-1:c(z).is(a))return z;
z=z.parentNode}return null})},index:function(a){if(!a||typeof a==="string")return c.inArray(this[0],a?c(a):this.parent().children());return c.inArray(a.jquery?a[0]:a,this)},add:function(a,b){a=typeof a==="string"?c(a,b||this.context):c.makeArray(a);b=c.merge(this.get(),a);return this.pushStack(P(a[0])||P(b[0])?b:c.unique(b))},andSelf:function(){return this.add(this.prevObject)}});c.each({parent:function(a){return(a=a.parentNode)&&a.nodeType!==11?a:null},parents:function(a){return c.dir(a,"parentNode")},
parentsUntil:function(a,b,d){return c.dir(a,"parentNode",d)},next:function(a){return c.nth(a,2,"nextSibling")},prev:function(a){return c.nth(a,2,"previousSibling")},nextAll:function(a){return c.dir(a,"nextSibling")},prevAll:function(a){return c.dir(a,"previousSibling")},nextUntil:function(a,b,d){return c.dir(a,"nextSibling",d)},prevUntil:function(a,b,d){return c.dir(a,"previousSibling",d)},siblings:function(a){return c.sibling(a.parentNode.firstChild,a)},children:function(a){return c.sibling(a.firstChild)},
contents:function(a){return c.nodeName(a,"iframe")?a.contentDocument||a.contentWindow.document:c.makeArray(a.childNodes)}},function(a,b){c.fn[a]=function(d,f){var e=c.map(this,b,d);gb.test(a)||(f=d);if(f&&typeof f==="string")e=c.filter(f,e);e=this.length>1?c.unique(e):e;if((this.length>1||ib.test(f))&&hb.test(a))e=e.reverse();return this.pushStack(e,a,Y.call(arguments).join(","))}});c.extend({filter:function(a,b,d){if(d)a=":not("+a+")";return c.find.matches(a,b)},dir:function(a,b,d){var f=[];for(a=
a[b];a&&a.nodeType!==9&&(d===A||a.nodeType!==1||!c(a).is(d));){a.nodeType===1&&f.push(a);a=a[b]}return f},nth:function(a,b,d){b=b||1;for(var f=0;a;a=a[d])if(a.nodeType===1&&++f===b)break;return a},sibling:function(a,b){for(var d=[];a;a=a.nextSibling)a.nodeType===1&&a!==b&&d.push(a);return d}});var Sa=/ jQuery\d+="(?:\d+|null)"/g,ta=/^\s+/,Ta=/(<([\w:]+)[^>]*?)\/>/g,jb=/^(?:area|br|col|embed|hr|img|input|link|meta|param)$/i,Ua=/<([\w:]+)/,kb=/<tbody/i,lb=/<|&#?\w+;/,Fa=/<script|<object|<embed|<option|<style/i,
Ga=/checked\s*(?:[^=]|=\s*.checked.)/i,Va=function(a,b,d){return jb.test(d)?a:b+"></"+d+">"},da={option:[1,"<select multiple='multiple'>","</select>"],legend:[1,"<fieldset>","</fieldset>"],thead:[1,"<table>","</table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],col:[2,"<table><tbody></tbody><colgroup>","</colgroup></table>"],area:[1,"<map>","</map>"],_default:[0,"",""]};da.optgroup=da.option;da.tbody=da.tfoot=da.colgroup=da.caption=da.thead;da.th=
da.td;if(!c.support.htmlSerialize)da._default=[1,"div<div>","</div>"];c.fn.extend({text:function(a){if(c.isFunction(a))return this.each(function(b){var d=c(this);d.text(a.call(this,b,d.text()))});if(typeof a!=="object"&&a!==A)return this.empty().append((this[0]&&this[0].ownerDocument||y).createTextNode(a));return c.text(this)},wrapAll:function(a){if(c.isFunction(a))return this.each(function(d){c(this).wrapAll(a.call(this,d))});if(this[0]){var b=c(a,this[0].ownerDocument).eq(0).clone(true);this[0].parentNode&&
b.insertBefore(this[0]);b.map(function(){for(var d=this;d.firstChild&&d.firstChild.nodeType===1;)d=d.firstChild;return d}).append(this)}return this},wrapInner:function(a){if(c.isFunction(a))return this.each(function(b){c(this).wrapInner(a.call(this,b))});return this.each(function(){var b=c(this),d=b.contents();d.length?d.wrapAll(a):b.append(a)})},wrap:function(a){return this.each(function(){c(this).wrapAll(a)})},unwrap:function(){return this.parent().each(function(){c.nodeName(this,"body")||c(this).replaceWith(this.childNodes)}).end()},
append:function(){return this.domManip(arguments,true,function(a){this.nodeType===1&&this.appendChild(a)})},prepend:function(){return this.domManip(arguments,true,function(a){this.nodeType===1&&this.insertBefore(a,this.firstChild)})},before:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,false,function(b){this.parentNode.insertBefore(b,this)});else if(arguments.length){var a=c(arguments[0]);a.push.apply(a,this.toArray());return this.pushStack(a,"before",arguments)}},after:function(){if(this[0]&&
this[0].parentNode)return this.domManip(arguments,false,function(b){this.parentNode.insertBefore(b,this.nextSibling)});else if(arguments.length){var a=this.pushStack(this,"after",arguments);a.push.apply(a,c(arguments[0]).toArray());return a}},remove:function(a,b){for(var d=0,f;(f=this[d])!=null;d++)if(!a||c.filter(a,[f]).length){if(!b&&f.nodeType===1){c.cleanData(f.getElementsByTagName("*"));c.cleanData([f])}f.parentNode&&f.parentNode.removeChild(f)}return this},empty:function(){for(var a=0,b;(b=
this[a])!=null;a++)for(b.nodeType===1&&c.cleanData(b.getElementsByTagName("*"));b.firstChild;)b.removeChild(b.firstChild);return this},clone:function(a){var b=this.map(function(){if(!c.support.noCloneEvent&&!c.isXMLDoc(this)){var d=this.outerHTML,f=this.ownerDocument;if(!d){d=f.createElement("div");d.appendChild(this.cloneNode(true));d=d.innerHTML}return c.clean([d.replace(Sa,"").replace(/=([^="'>\s]+\/)>/g,'="$1">').replace(ta,"")],f)[0]}else return this.cloneNode(true)});if(a===true){W(this,b);
W(this.find("*"),b.find("*"))}return b},html:function(a){if(a===A)return this[0]&&this[0].nodeType===1?this[0].innerHTML.replace(Sa,""):null;else if(typeof a==="string"&&!Fa.test(a)&&(c.support.leadingWhitespace||!ta.test(a))&&!da[(Ua.exec(a)||["",""])[1].toLowerCase()]){a=a.replace(Ta,Va);try{for(var b=0,d=this.length;b<d;b++)if(this[b].nodeType===1){c.cleanData(this[b].getElementsByTagName("*"));this[b].innerHTML=a}}catch(f){this.empty().append(a)}}else c.isFunction(a)?this.each(function(e){var i=
c(this),j=i.html();i.empty().append(function(){return a.call(this,e,j)})}):this.empty().append(a);return this},replaceWith:function(a){if(this[0]&&this[0].parentNode){if(c.isFunction(a))return this.each(function(b){var d=c(this),f=d.html();d.replaceWith(a.call(this,b,f))});if(typeof a!=="string")a=c(a).detach();return this.each(function(){var b=this.nextSibling,d=this.parentNode;c(this).remove();b?c(b).before(a):c(d).append(a)})}else return this.pushStack(c(c.isFunction(a)?a():a),"replaceWith",a)},
detach:function(a){return this.remove(a,true)},domManip:function(a,b,d){function f(I){return c.nodeName(I,"table")?I.getElementsByTagName("tbody")[0]||I.appendChild(I.ownerDocument.createElement("tbody")):I}var e,i,j=a[0],r=[],m;if(!c.support.checkClone&&arguments.length===3&&typeof j==="string"&&Ga.test(j))return this.each(function(){c(this).domManip(a,b,d,true)});if(c.isFunction(j))return this.each(function(I){var N=c(this);a[0]=j.call(this,I,b?N.html():A);N.domManip(a,b,d)});if(this[0]){e=j&&j.parentNode;
e=c.support.parentNode&&e&&e.nodeType===11&&e.childNodes.length===this.length?{fragment:e}:S(a,this,r);m=e.fragment;if(i=m.childNodes.length===1?(m=m.firstChild):m.firstChild){b=b&&c.nodeName(i,"tr");for(var q=0,z=this.length;q<z;q++)d.call(b?f(this[q],i):this[q],q>0||e.cacheable||this.length>1?m.cloneNode(true):m)}r.length&&c.each(r,B)}return this}});c.fragments={};c.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){c.fn[a]=
function(d){var f=[];d=c(d);var e=this.length===1&&this[0].parentNode;if(e&&e.nodeType===11&&e.childNodes.length===1&&d.length===1){d[b](this[0]);return this}else{e=0;for(var i=d.length;e<i;e++){var j=(e>0?this.clone(true):this).get();c.fn[b].apply(c(d[e]),j);f=f.concat(j)}return this.pushStack(f,a,d.selector)}}});c.extend({clean:function(a,b,d,f){b=b||y;if(typeof b.createElement==="undefined")b=b.ownerDocument||b[0]&&b[0].ownerDocument||y;for(var e=[],i=0,j;(j=a[i])!=null;i++){if(typeof j==="number")j+=
"";if(j){if(typeof j==="string"&&!lb.test(j))j=b.createTextNode(j);else if(typeof j==="string"){j=j.replace(Ta,Va);var r=(Ua.exec(j)||["",""])[1].toLowerCase(),m=da[r]||da._default,q=m[0],z=b.createElement("div");for(z.innerHTML=m[1]+j+m[2];q--;)z=z.lastChild;if(!c.support.tbody){q=kb.test(j);r=r==="table"&&!q?z.firstChild&&z.firstChild.childNodes:m[1]==="<table>"&&!q?z.childNodes:[];for(m=r.length-1;m>=0;--m)c.nodeName(r[m],"tbody")&&!r[m].childNodes.length&&r[m].parentNode.removeChild(r[m])}!c.support.leadingWhitespace&&
ta.test(j)&&z.insertBefore(b.createTextNode(ta.exec(j)[0]),z.firstChild);j=z.childNodes}if(j.nodeType)e.push(j);else e=c.merge(e,j)}}if(d)for(i=0;e[i];i++)if(f&&c.nodeName(e[i],"script")&&(!e[i].type||e[i].type.toLowerCase()==="text/javascript"))f.push(e[i].parentNode?e[i].parentNode.removeChild(e[i]):e[i]);else{e[i].nodeType===1&&e.splice.apply(e,[i+1,0].concat(c.makeArray(e[i].getElementsByTagName("script"))));d.appendChild(e[i])}return e},cleanData:function(a){for(var b,d,f=c.cache,e=c.event.special,
i=c.support.deleteExpando,j=0,r;(r=a[j])!=null;j++)if(d=r[c.expando]){b=f[d];if(b.events)for(var m in b.events)e[m]?c.event.remove(r,m):La(r,m,b.handle);if(i)delete r[c.expando];else r.removeAttribute&&r.removeAttribute(c.expando);delete f[d]}}});var mb=/z-?index|font-?weight|opacity|zoom|line-?height/i,Wa=/alpha\([^)]*\)/,Xa=/opacity=([^)]*)/,Aa=/float/i,Ba=/-([a-z])/ig,nb=/([A-Z])/g,ob=/^-?\d+(?:px)?$/i,pb=/^-?\d/,qb={position:"absolute",visibility:"hidden",display:"block"},rb=["Left","Right"],
sb=["Top","Bottom"],tb=y.defaultView&&y.defaultView.getComputedStyle,Ya=c.support.cssFloat?"cssFloat":"styleFloat",Ca=function(a,b){return b.toUpperCase()};c.fn.css=function(a,b){return s(this,a,b,true,function(d,f,e){if(e===A)return c.curCSS(d,f);if(typeof e==="number"&&!mb.test(f))e+="px";c.style(d,f,e)})};c.extend({style:function(a,b,d){if(!a||a.nodeType===3||a.nodeType===8)return A;if((b==="width"||b==="height")&&parseFloat(d)<0)d=A;var f=a.style||a,e=d!==A;if(!c.support.opacity&&b==="opacity"){if(e){f.zoom=
1;b=parseInt(d,10)+""==="NaN"?"":"alpha(opacity="+d*100+")";a=f.filter||c.curCSS(a,"filter")||"";f.filter=Wa.test(a)?a.replace(Wa,b):b}return f.filter&&f.filter.indexOf("opacity=")>=0?parseFloat(Xa.exec(f.filter)[1])/100+"":""}if(Aa.test(b))b=Ya;b=b.replace(Ba,Ca);if(e)f[b]=d;return f[b]},css:function(a,b,d,f){if(b==="width"||b==="height"){var e,i=b==="width"?rb:sb;d=function(){e=b==="width"?a.offsetWidth:a.offsetHeight;f!=="border"&&c.each(i,function(){f||(e-=parseFloat(c.curCSS(a,"padding"+this,
true))||0);if(f==="margin")e+=parseFloat(c.curCSS(a,"margin"+this,true))||0;else e-=parseFloat(c.curCSS(a,"border"+this+"Width",true))||0})};a.offsetWidth!==0?d():c.swap(a,qb,d);return Math.max(0,Math.round(e))}return c.curCSS(a,b,d)},curCSS:function(a,b,d){var f,e=a.style;if(!c.support.opacity&&b==="opacity"&&a.currentStyle){f=Xa.test(a.currentStyle.filter||"")?parseFloat(RegExp.$1)/100+"":"";return f===""?"1":f}if(Aa.test(b))b=Ya;if(!d&&e&&e[b])f=e[b];else if(tb){if(Aa.test(b))b="float";b=b.replace(nb,
"-$1").toLowerCase();e=a.ownerDocument.defaultView;if(!e)return null;if(a=e.getComputedStyle(a,null))f=a.getPropertyValue(b);if(b==="opacity"&&f==="")f="1"}else if(a.currentStyle){d=b.replace(Ba,Ca);f=a.currentStyle[b]||a.currentStyle[d];if(!ob.test(f)&&pb.test(f)){b=e.left;var i=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;e.left=d==="fontSize"?"1em":f||0;f=e.pixelLeft+"px";e.left=b;a.runtimeStyle.left=i}}return f},swap:function(a,b,d){var f={};for(var e in b){f[e]=a.style[e];a.style[e]=
b[e]}d.call(a);for(e in b)a.style[e]=f[e]}});if(c.expr&&c.expr.filters){c.expr.filters.hidden=function(a){var b=a.offsetWidth,d=a.offsetHeight,f=a.nodeName.toLowerCase()==="tr";return b===0&&d===0&&!f?true:b>0&&d>0&&!f?false:c.curCSS(a,"display")==="none"};c.expr.filters.visible=function(a){return!c.expr.filters.hidden(a)}}var ub=k(),vb=/<script(.|\s)*?\/script>/gi,wb=/select|textarea/i,xb=/color|date|datetime|email|hidden|month|number|password|range|search|tel|text|time|url|week/i,pa=/=\?(&|$)/,
Da=/\?/,yb=/(\?|&)_=.*?(&|$)/,zb=/^(\w+:)?\/\/([^\/?#]+)/,Ab=/%20/g,Bb=c.fn.load;c.fn.extend({load:function(a,b,d){if(typeof a!=="string")return Bb.call(this,a);else if(!this.length)return this;var f=a.indexOf(" ");if(f>=0){var e=a.slice(f,a.length);a=a.slice(0,f)}f="GET";if(b)if(c.isFunction(b)){d=b;b=null}else if(typeof b==="object"){b=c.param(b,c.ajaxSettings.traditional);f="POST"}var i=this;c.ajax({url:a,type:f,dataType:"html",data:b,complete:function(j,r){if(r==="success"||r==="notmodified")i.html(e?
c("<div />").append(j.responseText.replace(vb,"")).find(e):j.responseText);d&&i.each(d,[j.responseText,r,j])}});return this},serialize:function(){return c.param(this.serializeArray())},serializeArray:function(){return this.map(function(){return this.elements?c.makeArray(this.elements):this}).filter(function(){return this.name&&!this.disabled&&(this.checked||wb.test(this.nodeName)||xb.test(this.type))}).map(function(a,b){a=c(this).val();return a==null?null:c.isArray(a)?c.map(a,function(d){return{name:b.name,
value:d}}):{name:b.name,value:a}}).get()}});c.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){c.fn[b]=function(d){return this.bind(b,d)}});c.extend({get:function(a,b,d,f){if(c.isFunction(b)){f=f||d;d=b;b=null}return c.ajax({type:"GET",url:a,data:b,success:d,dataType:f})},getScript:function(a,b){return c.get(a,null,b,"script")},getJSON:function(a,b,d){return c.get(a,b,d,"json")},post:function(a,b,d,f){if(c.isFunction(b)){f=f||d;d=b;b={}}return c.ajax({type:"POST",
url:a,data:b,success:d,dataType:f})},ajaxSetup:function(a){c.extend(c.ajaxSettings,a)},ajaxSettings:{url:location.href,global:true,type:"GET",contentType:"application/x-www-form-urlencoded",processData:true,async:true,xhr:K.XMLHttpRequest&&(K.location.protocol!=="file:"||!K.ActiveXObject)?function(){return new K.XMLHttpRequest}:function(){try{return new K.ActiveXObject("Microsoft.XMLHTTP")}catch(a){}},accepts:{xml:"application/xml, text/xml",html:"text/html",script:"text/javascript, application/javascript",
json:"application/json, text/javascript",text:"text/plain",_default:"*/*"}},lastModified:{},etag:{},ajax:function(a){function b(){e.success&&e.success.call(m,r,j,L);e.global&&f("ajaxSuccess",[L,e])}function d(){e.complete&&e.complete.call(m,L,j);e.global&&f("ajaxComplete",[L,e]);e.global&&!--c.active&&c.event.trigger("ajaxStop")}function f(v,u){(e.context?c(e.context):c.event).trigger(v,u)}var e=c.extend(true,{},c.ajaxSettings,a),i,j,r,m=a&&a.context||e,q=e.type.toUpperCase();if(e.data&&e.processData&&
typeof e.data!=="string")e.data=c.param(e.data,e.traditional);if(e.dataType==="jsonp"){if(q==="GET")pa.test(e.url)||(e.url+=(Da.test(e.url)?"&":"?")+(e.jsonp||"callback")+"=?");else if(!e.data||!pa.test(e.data))e.data=(e.data?e.data+"&":"")+(e.jsonp||"callback")+"=?";e.dataType="json"}if(e.dataType==="json"&&(e.data&&pa.test(e.data)||pa.test(e.url))){i=e.jsonpCallback||"jsonp"+ub++;if(e.data)e.data=(e.data+"").replace(pa,"="+i+"$1");e.url=e.url.replace(pa,"="+i+"$1");e.dataType="script";K[i]=K[i]||
function(v){r=v;b();d();K[i]=A;try{delete K[i]}catch(u){}N&&N.removeChild(X)}}if(e.dataType==="script"&&e.cache===null)e.cache=false;if(e.cache===false&&q==="GET"){var z=k(),I=e.url.replace(yb,"$1_="+z+"$2");e.url=I+(I===e.url?(Da.test(e.url)?"&":"?")+"_="+z:"")}if(e.data&&q==="GET")e.url+=(Da.test(e.url)?"&":"?")+e.data;e.global&&!c.active++&&c.event.trigger("ajaxStart");z=(z=zb.exec(e.url))&&(z[1]&&z[1]!==location.protocol||z[2]!==location.host);if(e.dataType==="script"&&q==="GET"&&z){var N=y.getElementsByTagName("head")[0]||
y.documentElement,X=y.createElement("script");X.src=e.url;if(e.scriptCharset)X.charset=e.scriptCharset;if(!i){var U=false;X.onload=X.onreadystatechange=function(){if(!U&&(!this.readyState||this.readyState==="loaded"||this.readyState==="complete")){U=true;b();d();X.onload=X.onreadystatechange=null;N&&X.parentNode&&N.removeChild(X)}}}N.insertBefore(X,N.firstChild);return A}var ca=false,L=e.xhr();if(L){e.username?L.open(q,e.url,e.async,e.username,e.password):L.open(q,e.url,e.async);try{if(e.data||a&&
a.contentType)L.setRequestHeader("Content-Type",e.contentType);if(e.ifModified){c.lastModified[e.url]&&L.setRequestHeader("If-Modified-Since",c.lastModified[e.url]);c.etag[e.url]&&L.setRequestHeader("If-None-Match",c.etag[e.url])}z||L.setRequestHeader("X-Requested-With","XMLHttpRequest");L.setRequestHeader("Accept",e.dataType&&e.accepts[e.dataType]?e.accepts[e.dataType]+", */*":e.accepts._default)}catch(za){}if(e.beforeSend&&e.beforeSend.call(m,L,e)===false){e.global&&!--c.active&&c.event.trigger("ajaxStop");
L.abort();return false}e.global&&f("ajaxSend",[L,e]);var g=L.onreadystatechange=function(v){if(!L||L.readyState===0||v==="abort"){ca||d();ca=true;if(L)L.onreadystatechange=c.noop}else if(!ca&&L&&(L.readyState===4||v==="timeout")){ca=true;L.onreadystatechange=c.noop;j=v==="timeout"?"timeout":!c.httpSuccess(L)?"error":e.ifModified&&c.httpNotModified(L,e.url)?"notmodified":"success";var u;if(j==="success")try{r=c.httpData(L,e.dataType,e)}catch(J){j="parsererror";u=J}if(j==="success"||j==="notmodified")i||
b();else c.handleError(e,L,j,u);d();v==="timeout"&&L.abort();if(e.async)L=null}};try{var h=L.abort;L.abort=function(){L&&h.call(L);g("abort")}}catch(n){}e.async&&e.timeout>0&&setTimeout(function(){L&&!ca&&g("timeout")},e.timeout);try{L.send(q==="POST"||q==="PUT"||q==="DELETE"?e.data:null)}catch(p){c.handleError(e,L,null,p);d()}e.async||g();return L}},handleError:function(a,b,d,f){if(a.error)a.error.call(a.context||a,b,d,f);if(a.global)(a.context?c(a.context):c.event).trigger("ajaxError",[b,a,f])},
active:0,httpSuccess:function(a){try{return!a.status&&location.protocol==="file:"||a.status>=200&&a.status<300||a.status===304||a.status===1223||a.status===0}catch(b){}return false},httpNotModified:function(a,b){var d=a.getResponseHeader("Last-Modified"),f=a.getResponseHeader("Etag");if(d)c.lastModified[b]=d;if(f)c.etag[b]=f;return a.status===304||a.status===0},httpData:function(a,b,d){var f=a.getResponseHeader("content-type")||"",e=b==="xml"||!b&&f.indexOf("xml")>=0;a=e?a.responseXML:a.responseText;
e&&a.documentElement.nodeName==="parsererror"&&c.error("parsererror");if(d&&d.dataFilter)a=d.dataFilter(a,b);if(typeof a==="string")if(b==="json"||!b&&f.indexOf("json")>=0)a=c.parseJSON(a);else if(b==="script"||!b&&f.indexOf("javascript")>=0)c.globalEval(a);return a},param:function(a,b){function d(j,r){if(c.isArray(r))c.each(r,function(m,q){b||/\[\]$/.test(j)?f(j,q):d(j+"["+(typeof q==="object"||c.isArray(q)?m:"")+"]",q)});else!b&&r!=null&&typeof r==="object"?c.each(r,function(m,q){d(j+"["+m+"]",
q)}):f(j,r)}function f(j,r){r=c.isFunction(r)?r():r;e[e.length]=encodeURIComponent(j)+"="+encodeURIComponent(r)}var e=[];if(b===A)b=c.ajaxSettings.traditional;if(c.isArray(a)||a.jquery)c.each(a,function(){f(this.name,this.value)});else for(var i in a)d(i,a[i]);return e.join("&").replace(Ab,"+")}});var Ea={},Cb=/toggle|show|hide/,Db=/^([+-]=)?([\d+-.]+)(.*)$/,ua,Ha=[["height","marginTop","marginBottom","paddingTop","paddingBottom"],["width","marginLeft","marginRight","paddingLeft","paddingRight"],
["opacity"]];c.fn.extend({show:function(a,b){if(a||a===0)return this.animate(O("show",3),a,b);else{a=0;for(b=this.length;a<b;a++){var d=c.data(this[a],"olddisplay");this[a].style.display=d||"";if(c.css(this[a],"display")==="none"){d=this[a].nodeName;var f;if(Ea[d])f=Ea[d];else{var e=c("<"+d+" />").appendTo("body");f=e.css("display");if(f==="none")f="block";e.remove();Ea[d]=f}c.data(this[a],"olddisplay",f)}}a=0;for(b=this.length;a<b;a++)this[a].style.display=c.data(this[a],"olddisplay")||"";return this}},
hide:function(a,b){if(a||a===0)return this.animate(O("hide",3),a,b);else{a=0;for(b=this.length;a<b;a++){var d=c.data(this[a],"olddisplay");!d&&d!=="none"&&c.data(this[a],"olddisplay",c.css(this[a],"display"))}a=0;for(b=this.length;a<b;a++)this[a].style.display="none";return this}},_toggle:c.fn.toggle,toggle:function(a,b){var d=typeof a==="boolean";if(c.isFunction(a)&&c.isFunction(b))this._toggle.apply(this,arguments);else a==null||d?this.each(function(){var f=d?a:c(this).is(":hidden");c(this)[f?"show":
"hide"]()}):this.animate(O("toggle",3),a,b);return this},fadeTo:function(a,b,d){return this.filter(":hidden").css("opacity",0).show().end().animate({opacity:b},a,d)},animate:function(a,b,d,f){var e=c.speed(b,d,f);if(c.isEmptyObject(a))return this.each(e.complete);return this[e.queue===false?"each":"queue"](function(){var i=c.extend({},e),j,r=this.nodeType===1&&c(this).is(":hidden"),m=this;for(j in a){var q=j.replace(Ba,Ca);if(j!==q){a[q]=a[j];delete a[j];j=q}if(a[j]==="hide"&&r||a[j]==="show"&&!r)return i.complete.call(this);
if((j==="height"||j==="width")&&this.style){i.display=c.css(this,"display");i.overflow=this.style.overflow}if(c.isArray(a[j])){(i.specialEasing=i.specialEasing||{})[j]=a[j][1];a[j]=a[j][0]}}if(i.overflow!=null)this.style.overflow="hidden";i.curAnim=c.extend({},a);c.each(a,function(z,I){var N=new c.fx(m,i,z);if(Cb.test(I))N[I==="toggle"?r?"show":"hide":I](a);else{var X=Db.exec(I),U=N.cur(true)||0;if(X){I=parseFloat(X[2]);var ca=X[3]||"px";if(ca!=="px"){m.style[z]=(I||1)+ca;U=(I||1)/N.cur(true)*U;m.style[z]=
U+ca}if(X[1])I=(X[1]==="-="?-1:1)*I+U;N.custom(U,I,ca)}else N.custom(U,I,"")}});return true})},stop:function(a,b){var d=c.timers;a&&this.queue([]);this.each(function(){for(var f=d.length-1;f>=0;f--)if(d[f].elem===this){b&&d[f](true);d.splice(f,1)}});b||this.dequeue();return this}});c.each({slideDown:O("show",1),slideUp:O("hide",1),slideToggle:O("toggle",1),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"}},function(a,b){c.fn[a]=function(d,f){return this.animate(b,d,f)}});c.extend({speed:function(a,
b,d){var f=a&&typeof a==="object"?a:{complete:d||!d&&b||c.isFunction(a)&&a,duration:a,easing:d&&b||b&&!c.isFunction(b)&&b};f.duration=c.fx.off?0:typeof f.duration==="number"?f.duration:c.fx.speeds[f.duration]||c.fx.speeds._default;f.old=f.complete;f.complete=function(){f.queue!==false&&c(this).dequeue();c.isFunction(f.old)&&f.old.call(this)};return f},easing:{linear:function(a,b,d,f){return d+f*a},swing:function(a,b,d,f){return(-Math.cos(a*Math.PI)/2+0.5)*f+d}},timers:[],fx:function(a,b,d){this.options=
b;this.elem=a;this.prop=d;if(!b.orig)b.orig={}}});c.fx.prototype={update:function(){this.options.step&&this.options.step.call(this.elem,this.now,this);(c.fx.step[this.prop]||c.fx.step._default)(this);if((this.prop==="height"||this.prop==="width")&&this.elem.style)this.elem.style.display="block"},cur:function(a){if(this.elem[this.prop]!=null&&(!this.elem.style||this.elem.style[this.prop]==null))return this.elem[this.prop];return(a=parseFloat(c.css(this.elem,this.prop,a)))&&a>-10000?a:parseFloat(c.curCSS(this.elem,
this.prop))||0},custom:function(a,b,d){function f(i){return e.step(i)}this.startTime=k();this.start=a;this.end=b;this.unit=d||this.unit||"px";this.now=this.start;this.pos=this.state=0;var e=this;f.elem=this.elem;if(f()&&c.timers.push(f)&&!ua)ua=setInterval(c.fx.tick,13)},show:function(){this.options.orig[this.prop]=c.style(this.elem,this.prop);this.options.show=true;this.custom(this.prop==="width"||this.prop==="height"?1:0,this.cur());c(this.elem).show()},hide:function(){this.options.orig[this.prop]=
c.style(this.elem,this.prop);this.options.hide=true;this.custom(this.cur(),0)},step:function(a){var b=k(),d=true;if(a||b>=this.options.duration+this.startTime){this.now=this.end;this.pos=this.state=1;this.update();this.options.curAnim[this.prop]=true;for(var f in this.options.curAnim)if(this.options.curAnim[f]!==true)d=false;if(d){if(this.options.display!=null){this.elem.style.overflow=this.options.overflow;a=c.data(this.elem,"olddisplay");this.elem.style.display=a?a:this.options.display;if(c.css(this.elem,
"display")==="none")this.elem.style.display="block"}this.options.hide&&c(this.elem).hide();if(this.options.hide||this.options.show)for(var e in this.options.curAnim)c.style(this.elem,e,this.options.orig[e]);this.options.complete.call(this.elem)}return false}else{e=b-this.startTime;this.state=e/this.options.duration;a=this.options.easing||(c.easing.swing?"swing":"linear");this.pos=c.easing[this.options.specialEasing&&this.options.specialEasing[this.prop]||a](this.state,e,0,1,this.options.duration);
this.now=this.start+(this.end-this.start)*this.pos;this.update()}return true}};c.extend(c.fx,{tick:function(){for(var a=c.timers,b=0;b<a.length;b++)a[b]()||a.splice(b--,1);a.length||c.fx.stop()},stop:function(){clearInterval(ua);ua=null},speeds:{slow:600,fast:200,_default:400},step:{opacity:function(a){c.style(a.elem,"opacity",a.now)},_default:function(a){if(a.elem.style&&a.elem.style[a.prop]!=null)a.elem.style[a.prop]=(a.prop==="width"||a.prop==="height"?Math.max(0,a.now):a.now)+a.unit;else a.elem[a.prop]=
a.now}}});if(c.expr&&c.expr.filters)c.expr.filters.animated=function(a){return c.grep(c.timers,function(b){return a===b.elem}).length};c.fn.offset="getBoundingClientRect"in y.documentElement?function(a){var b=this[0];if(a)return this.each(function(e){c.offset.setOffset(this,a,e)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);var d=b.getBoundingClientRect(),f=b.ownerDocument;b=f.body;f=f.documentElement;return{top:d.top+(self.pageYOffset||c.support.boxModel&&
f.scrollTop||b.scrollTop)-(f.clientTop||b.clientTop||0),left:d.left+(self.pageXOffset||c.support.boxModel&&f.scrollLeft||b.scrollLeft)-(f.clientLeft||b.clientLeft||0)}}:function(a){var b=this[0];if(a)return this.each(function(z){c.offset.setOffset(this,a,z)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);c.offset.initialize();var d=b.offsetParent,f=b,e=b.ownerDocument,i,j=e.documentElement,r=e.body;f=(e=e.defaultView)?e.getComputedStyle(b,null):b.currentStyle;
for(var m=b.offsetTop,q=b.offsetLeft;(b=b.parentNode)&&b!==r&&b!==j;){if(c.offset.supportsFixedPosition&&f.position==="fixed")break;i=e?e.getComputedStyle(b,null):b.currentStyle;m-=b.scrollTop;q-=b.scrollLeft;if(b===d){m+=b.offsetTop;q+=b.offsetLeft;if(c.offset.doesNotAddBorder&&!(c.offset.doesAddBorderForTableAndCells&&/^t(able|d|h)$/i.test(b.nodeName))){m+=parseFloat(i.borderTopWidth)||0;q+=parseFloat(i.borderLeftWidth)||0}f=d;d=b.offsetParent}if(c.offset.subtractsBorderForOverflowNotVisible&&i.overflow!==
"visible"){m+=parseFloat(i.borderTopWidth)||0;q+=parseFloat(i.borderLeftWidth)||0}f=i}if(f.position==="relative"||f.position==="static"){m+=r.offsetTop;q+=r.offsetLeft}if(c.offset.supportsFixedPosition&&f.position==="fixed"){m+=Math.max(j.scrollTop,r.scrollTop);q+=Math.max(j.scrollLeft,r.scrollLeft)}return{top:m,left:q}};c.offset={initialize:function(){var a=y.body,b=y.createElement("div"),d,f,e,i=parseFloat(c.curCSS(a,"marginTop",true))||0;c.extend(b.style,{position:"absolute",top:0,left:0,margin:0,
border:0,width:"1px",height:"1px",visibility:"hidden"});b.innerHTML="<div style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;'><div></div></div><table style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;' cellpadding='0' cellspacing='0'><tr><td></td></tr></table>";a.insertBefore(b,a.firstChild);d=b.firstChild;f=d.firstChild;e=d.nextSibling.firstChild.firstChild;this.doesNotAddBorder=f.offsetTop!==5;this.doesAddBorderForTableAndCells=
e.offsetTop===5;f.style.position="fixed";f.style.top="20px";this.supportsFixedPosition=f.offsetTop===20||f.offsetTop===15;f.style.position=f.style.top="";d.style.overflow="hidden";d.style.position="relative";this.subtractsBorderForOverflowNotVisible=f.offsetTop===-5;this.doesNotIncludeMarginInBodyOffset=a.offsetTop!==i;a.removeChild(b);c.offset.initialize=c.noop},bodyOffset:function(a){var b=a.offsetTop,d=a.offsetLeft;c.offset.initialize();if(c.offset.doesNotIncludeMarginInBodyOffset){b+=parseFloat(c.curCSS(a,
"marginTop",true))||0;d+=parseFloat(c.curCSS(a,"marginLeft",true))||0}return{top:b,left:d}},setOffset:function(a,b,d){if(/static/.test(c.curCSS(a,"position")))a.style.position="relative";var f=c(a),e=f.offset(),i=parseInt(c.curCSS(a,"top",true),10)||0,j=parseInt(c.curCSS(a,"left",true),10)||0;if(c.isFunction(b))b=b.call(a,d,e);d={top:b.top-e.top+i,left:b.left-e.left+j};"using"in b?b.using.call(a,d):f.css(d)}};c.fn.extend({position:function(){if(!this[0])return null;var a=this[0],b=this.offsetParent(),
d=this.offset(),f=/^body|html$/i.test(b[0].nodeName)?{top:0,left:0}:b.offset();d.top-=parseFloat(c.curCSS(a,"marginTop",true))||0;d.left-=parseFloat(c.curCSS(a,"marginLeft",true))||0;f.top+=parseFloat(c.curCSS(b[0],"borderTopWidth",true))||0;f.left+=parseFloat(c.curCSS(b[0],"borderLeftWidth",true))||0;return{top:d.top-f.top,left:d.left-f.left}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||y.body;a&&!/^body|html$/i.test(a.nodeName)&&c.css(a,"position")==="static";)a=
a.offsetParent;return a})}});c.each(["Left","Top"],function(a,b){var d="scroll"+b;c.fn[d]=function(f){var e=this[0],i;if(!e)return null;if(f!==A)return this.each(function(){if(i=ja(this))i.scrollTo(!a?f:c(i).scrollLeft(),a?f:c(i).scrollTop());else this[d]=f});else return(i=ja(e))?"pageXOffset"in i?i[a?"pageYOffset":"pageXOffset"]:c.support.boxModel&&i.document.documentElement[d]||i.document.body[d]:e[d]}});c.each(["Height","Width"],function(a,b){var d=b.toLowerCase();c.fn["inner"+b]=function(){return this[0]?
c.css(this[0],d,false,"padding"):null};c.fn["outer"+b]=function(f){return this[0]?c.css(this[0],d,false,f?"margin":"border"):null};c.fn[d]=function(f){var e=this[0];if(!e)return f==null?null:this;if(c.isFunction(f))return this.each(function(i){var j=c(this);j[d](f.call(this,i,j[d]()))});return"scrollTo"in e&&e.document?e.document.compatMode==="CSS1Compat"&&e.document.documentElement["client"+b]||e.document.body["client"+b]:e.nodeType===9?Math.max(e.documentElement["client"+b],e.body["scroll"+b],e.documentElement["scroll"+
b],e.body["offset"+b],e.documentElement["offset"+b]):f===A?c.css(e,d):this.css(d,typeof f==="string"?f:f+"px")}});K.jQuery=K.$=c;if($){var Za=require.callReady;require.callReady=function(){Za&&Za();c.callReady()};require.def("jquery",function(){return c});require.def("jQuery",function(){return c})}})(window);