require.def("tabs/pageStats",["domplate/domplate","core/lib","i18n!nls/pageStats","preview/harSchema","preview/harModel","core/cookies","domplate/infoTip","core/trace"],function(p,f,e,q,r,s,t){with(p){var h=function(){};h.prototype={data:[],title:"",getLabelTooltipText:function(a){return a.label+": "+f.formatSize(a.value)},cleanUp:function(){for(var a=0;a<this.data.length;a++){this.data[a].value=0;this.data[a].count=0}}};p=function(){};p.prototype=f.extend(h.prototype,{title:"Summary of request times.",
data:[{value:0,label:e.pieLabelDNS,color:"rgb(119, 192, 203)"},{value:0,label:e.pieLabelSSL,color:"rgb(168, 196, 173)"},{value:0,label:e.pieLabelConnect,color:"rgb(179, 222, 93)"},{value:0,label:e.pieLabelBlocked,color:"rgb(228, 214, 193)"},{value:0,label:e.pieLabelSend,color:"rgb(224, 171, 157)"},{value:0,label:e.pieLabelWait,color:"rgb(163, 150, 190)"},{value:0,label:e.pieLabelReceive,color:"rgb(194, 194, 194)"}],getLabelTooltipText:function(a){return a.label+": "+f.formatTime(a.value)}});q=function(){};
q.prototype=f.extend(h.prototype,{title:"Summary of content types.",data:[{value:0,label:e.pieLabelHTMLText,color:"rgb(174, 234, 218)"},{value:0,label:e.pieLabelJavaScript,color:"rgb(245, 230, 186)"},{value:0,label:e.pieLabelCSS,color:"rgb(212, 204, 219)"},{value:0,label:e.pieLabelImage,color:"rgb(220, 171, 181)"},{value:0,label:e.pieLabelFlash,color:"rgb(166, 156, 222)"},{value:0,label:e.pieLabelOthers,color:"rgb(229, 171, 255)"}],getLabelTooltipText:function(a){return a.count+"x "+a.label+": "+
f.formatSize(a.value)}});r=function(){};r.prototype=f.extend(h.prototype,{title:"Summary of sent and received bodies & headers.",data:[{value:0,label:e.pieLabelHeadersSent,color:"rgb(247, 179, 227)"},{value:0,label:e.pieLabelBodiesSent,color:"rgb(226, 160, 241)"},{value:0,label:e.pieLabelHeadersReceived,color:"rgb(166, 232, 166)"},{value:0,label:e.pieLabelBodiesReceived,color:"rgb(168, 196, 173)"}]});s=function(){};s.prototype=f.extend(h.prototype,{title:"Comparison of downloaded data from the server and browser cache.",
data:[{value:0,label:e.pieLabelDownloaded,color:"rgb(182, 182, 182)"},{value:0,label:e.pieLabelPartial,color:"rgb(218, 218, 218)"},{value:0,label:e.pieLabelFromCache,color:"rgb(239, 239, 239)"}],getLabelTooltipText:function(a){return a.count+"x "+a.label+": "+f.formatSize(a.value)}});var k=new p,i=new q,o=new r,l=new s,u={"text/javascript":1,"text/jscript":1,"application/javascript":1,"application/x-javascript":1,"text/js":1},v={"text/plain":1,"text/html":1},w={"text/css":1},x={"image/png":1,"image/jpeg":1},
y={"application/x-shockwave-flash":1};e=function(a,d){this.model=a;this.timeline=d;this.timeline.addListener(this)};e.prototype=domplate({element:null,tag:DIV({"class":"pageStatsBody",style:"height: auto; display: none"}),update:function(a){if(this.isVisible()){this.cleanUp();a.length||a.push(null);for(var d=0;d<a.length;d++){var b=a[d];b=b?this.model.getPageEntries(b):this.model.getAllEntries();for(var m=0;m<b.length;m++){var c=b[m];k.data[0].value+=c.timings.dns;k.data[1].value+=c.timings.ssl?c.timings.ssl:
-1;k.data[2].value+=c.timings.connect;k.data[3].value+=c.timings.blocked;k.data[4].value+=c.timings.send;k.data[5].value+=c.timings.wait;k.data[6].value+=c.timings.receive;if(c.timings.ssl>0)k.data[2].value-=c.timings.ssl;var n=c.response,g=n.bodySize>0?n.bodySize:0,j=n.content.mimeType;j=(j=j?j.match(/^([^;]+)/)[1]:null)?j:n.content.mimeType;if(v[j]){i.data[0].value+=g;i.data[0].count++}else if(u[j]){i.data[1].value+=g;i.data[1].count++}else if(w[j]){i.data[2].value+=g;i.data[2].count++}else if(x[j]){i.data[3].value+=
g;i.data[3].count++}else if(y[j]){i.data[4].value+=g;i.data[4].count++}else{i.data[5].value+=g;i.data[5].count++}o.data[0].value+=c.request.headersSize>0?c.request.headersSize:0;o.data[1].value+=c.request.bodySize>0?c.request.bodySize:0;o.data[2].value+=c.response.headersSize>0?c.response.headersSize:0;o.data[3].value+=g;if(c.response.status==206){l.data[1].value+=g;l.data[1].count++}else if(c.response.status==304){l.data[2].value+=g;l.data[2].count++}else if(g>0){l.data[0].value+=g;l.data[0].count++}}}h.draw(f.$(this.timingPie,
"pieGraph"),k);h.draw(f.$(this.contentPie,"pieGraph"),i);h.draw(f.$(this.trafficPie,"pieGraph"),o);h.draw(f.$(this.cachePie,"pieGraph"),l)}},cleanUp:function(){k.cleanUp();i.cleanUp();o.cleanUp();l.cleanUp()},showInfoTip:function(a,d,b,m){return h.showInfoTip(a,d,b,m)},onSelectionChange:function(a){this.update(a)},show:function(a){if(!this.isVisible()){t.addListener(this);f.setClass(this.element,"opened");if(!a||$.browser.msie)this.element.style.display="block";else $(this.element).slideDown();this.update(this.timeline.getSelection())}},
hide:function(a){if(this.isVisible()){t.removeListener(this);f.removeClass(this.element,"opened");if(!a||$.browser.msie)this.element.style.display="none";else $(this.element).slideUp()}},isVisible:function(){return f.hasClass(this.element,"opened")},toggle:function(a){this.isVisible()?this.hide(a):this.show(a)},render:function(a){this.element=this.tag.replace({},a);this.timingPie=h.render(k,this.element);this.contentPie=h.render(i,this.element);this.trafficPie=h.render(o,this.element);this.cachePie=
h.render(l,this.element);this.cachePie.style.borderRight=0;return this.element}});h=domplate({tag:TABLE({"class":"pagePieTable",cellpadding:0,cellspacing:0,_repObject:"$pie"},TBODY(TR(TD({"class":"pieBox",title:"$pie.title"}),TD(FOR("item","$pie.data",DIV({"class":"pieLabel",_repObject:"$item"},SPAN({"class":"box",style:"background-color: $item.color"},"&nbsp;"),SPAN({"class":"label"},"$item.label"))))))),render:function(a,d){a=this.tag.append({pie:a},d);d=f.$(a,"pieBox");var b=document.createElement("canvas");
b.setAttribute("class","pieGraph ");b.setAttribute("height","100");b.setAttribute("width","100");d.appendChild(b);typeof G_vmlCanvasManager!="undefined"&&G_vmlCanvasManager.initElement(b);return a},draw:function(a,d){if(a&&a.getContext){var b=a.getContext("2d"),m=Math.min(a.width,a.height)/2,c=[a.width/2,a.height/2];b.clearRect(0,0,a.width,a.height);a=0;d=d.data;var n=0;for(var g in d)n+=d[g].value;if(n)for(g=0;g<d.length;g++){var j=d[g].value/n;b.beginPath();b.moveTo(c[0],c[1]);b.arc(c[0],c[1],m,
Math.PI*(-0.5+2*a),Math.PI*(-0.5+2*(a+j)),false);b.lineTo(c[0],c[1]);b.closePath();b.fillStyle=d[g].color;b.fill();a+=j}else{b.beginPath();b.moveTo(c[0],c[1]);b.arc(c[0],c[1],m,0,Math.PI*2,false);b.closePath();b.fillStyle="rgb(229,236,238)";b.lineStyle="lightgray";b.fill()}}},showInfoTip:function(a,d){var b=f.getAncestorByClass(d,"pagePieTable");if(!b)return false;if(d=f.getAncestorByClass(d,"pieLabel")){z.render(b.repObject,d.repObject,a);return true}}});var z=domplate({tag:DIV({"class":"pieLabelInfoTip"},
"$text"),getText:function(a){return a.label+": "+formatTime(a.value)},render:function(a,d,b){this.tag.replace({text:a.getLabelTooltipText(d)},b)}});return e}});