var swfobject=function(){function W(){if(A.readyState=="complete"){A.parentNode.removeChild(A);D()}}function D(){if(!E){if(e.ie&&e.win){var a=q("span");try{var b=h.getElementsByTagName("body")[0].appendChild(a);b.parentNode.removeChild(b)}catch(c){return}}E=true;if(F){clearInterval(F);F=null}a=G.length;for(b=0;b<a;b++)G[b]()}}function H(a){if(E)a();else G[G.length]=a}function P(a){if(typeof m.addEventListener!=l)m.addEventListener("load",a,false);else if(typeof h.addEventListener!=l)h.addEventListener("load",
a,false);else if(typeof m.attachEvent!=l)I(m,"onload",a);else if(typeof m.onload=="function"){var b=m.onload;m.onload=function(){b();a()}}else m.onload=a}function X(){for(var a=r.length,b=0;b<a;b++){var c=r[b].id;if(e.pv[0]>0){var d=n(c);if(d){r[b].width=d.getAttribute("width")?d.getAttribute("width"):"0";r[b].height=d.getAttribute("height")?d.getAttribute("height"):"0";if(B(r[b].swfVersion)){e.webkit&&e.webkit<312&&Y(d);u(c,true)}else r[b].expressInstall&&!v&&B("6.0.65")&&(e.win||e.mac)?Q(r[b]):
Z(d)}}else u(c,true)}}function Y(a){var b=a.getElementsByTagName(s)[0];if(b){var c=q("embed"),d=b.attributes;if(d)for(var f=d.length,i=0;i<f;i++)d[i].nodeName=="DATA"?c.setAttribute("src",d[i].nodeValue):c.setAttribute(d[i].nodeName,d[i].nodeValue);if(b=b.childNodes){d=b.length;for(f=0;f<d;f++)b[f].nodeType==1&&b[f].nodeName=="PARAM"&&c.setAttribute(b[f].getAttribute("name"),b[f].getAttribute("value"))}a.parentNode.replaceChild(c,a)}}function Q(a){v=true;var b=n(a.id);if(b){if(a.altContentId){var c=
n(a.altContentId);if(c){w=c;J=a.altContentId}}else w=N(b);if(!/%$/.test(a.width)&&parseInt(a.width,10)<310)a.width="310";if(!/%$/.test(a.height)&&parseInt(a.height,10)<137)a.height="137";h.title=h.title.slice(0,47)+" - Flash Player Installation";c="MMredirectURL="+m.location+"&MMplayerType="+(e.ie&&e.win?"ActiveX":"PlugIn")+"&MMdoctitle="+h.title;var d=a.id;if(e.ie&&e.win&&b.readyState!=4){var f=q("div");d+="SWFObjectNew";f.setAttribute("id",d);b.parentNode.insertBefore(f,b);b.style.display="none";
I(m,"onload",function(){b.parentNode.removeChild(b)})}O({data:a.expressInstall,id:R,width:a.width,height:a.height},{flashvars:c},d)}}function Z(a){if(e.ie&&e.win&&a.readyState!=4){var b=q("div");a.parentNode.insertBefore(b,a);b.parentNode.replaceChild(N(a),b);a.style.display="none";I(m,"onload",function(){a.parentNode.removeChild(a)})}else a.parentNode.replaceChild(N(a),a)}function N(a){var b=q("div");if(e.win&&e.ie)b.innerHTML=a.innerHTML;else if(a=a.getElementsByTagName(s)[0])if(a=a.childNodes)for(var c=
a.length,d=0;d<c;d++)!(a[d].nodeType==1&&a[d].nodeName=="PARAM")&&a[d].nodeType!=8&&b.appendChild(a[d].cloneNode(true));return b}function O(a,b,c){var d,f=n(c);if(f){if(typeof a.id==l)a.id=c;if(e.ie&&e.win){var i="";for(var j in a)if(a[j]!=Object.prototype[j])if(j.toLowerCase()=="data")b.movie=a[j];else if(j.toLowerCase()=="styleclass")i+=' class="'+a[j]+'"';else if(j.toLowerCase()!="classid")i+=" "+j+'="'+a[j]+'"';j="";for(var g in b)if(b[g]!=Object.prototype[g])j+='<param name="'+g+'" value="'+
b[g]+'" />';f.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+i+">"+j+"</object>";K[K.length]=a.id;d=n(a.id)}else if(e.webkit&&e.webkit<312){g=q("embed");g.setAttribute("type",L);for(i in a)if(a[i]!=Object.prototype[i])if(i.toLowerCase()=="data")g.setAttribute("src",a[i]);else if(i.toLowerCase()=="styleclass")g.setAttribute("class",a[i]);else i.toLowerCase()!="classid"&&g.setAttribute(i,a[i]);for(var o in b)b[o]!=Object.prototype[o]&&o.toLowerCase()!="movie"&&g.setAttribute(o,
b[o]);f.parentNode.replaceChild(g,f);d=g}else{g=q(s);g.setAttribute("type",L);for(var k in a)if(a[k]!=Object.prototype[k])if(k.toLowerCase()=="styleclass")g.setAttribute("class",a[k]);else k.toLowerCase()!="classid"&&g.setAttribute(k,a[k]);for(var p in b)b[p]!=Object.prototype[p]&&p.toLowerCase()!="movie"&&$(g,p,b[p]);f.parentNode.replaceChild(g,f);d=g}}return d}function $(a,b,c){var d=q("param");d.setAttribute("name",b);d.setAttribute("value",c);a.appendChild(d)}function S(a){var b=n(a);if(b&&(b.nodeName==
"OBJECT"||b.nodeName=="EMBED"))if(e.ie&&e.win)b.readyState==4?T(a):m.attachEvent("onload",function(){T(a)});else b.parentNode.removeChild(b)}function T(a){if(a=n(a)){for(var b in a)if(typeof a[b]=="function")a[b]=null;a.parentNode.removeChild(a)}}function n(a){var b=null;try{b=h.getElementById(a)}catch(c){}return b}function q(a){return h.createElement(a)}function I(a,b,c){a.attachEvent(b,c);x[x.length]=[a,b,c]}function B(a){var b=e.pv;a=a.split(".");a[0]=parseInt(a[0],10);a[1]=parseInt(a[1],10)||
0;a[2]=parseInt(a[2],10)||0;return b[0]>a[0]||b[0]==a[0]&&b[1]>a[1]||b[0]==a[0]&&b[1]==a[1]&&b[2]>=a[2]?true:false}function U(a,b){if(!(e.ie&&e.mac)){var c=h.getElementsByTagName("head")[0],d=q("style");d.setAttribute("type","text/css");d.setAttribute("media","screen");!(e.ie&&e.win)&&typeof h.createTextNode!=l&&d.appendChild(h.createTextNode(a+" {"+b+"}"));c.appendChild(d);if(e.ie&&e.win&&typeof h.styleSheets!=l&&h.styleSheets.length>0){c=h.styleSheets[h.styleSheets.length-1];typeof c.addRule==s&&
c.addRule(a,b)}}}function u(a,b){b=b?"visible":"hidden";if(E&&n(a))n(a).style.visibility=b;else U("#"+a,"visibility:"+b)}function V(a){return/[\\\"<>\.;]/.exec(a)!=null?encodeURIComponent(a):a}var l="undefined",s="object",L="application/x-shockwave-flash",R="SWFObjectExprInst",m=window,h=document,t=navigator,G=[],r=[],K=[],x=[],A,F=null,w=null,J=null,E=false,v=false,e=function(){var a=typeof h.getElementById!=l&&typeof h.getElementsByTagName!=l&&typeof h.createElement!=l,b=[0,0,0],c=null;if(typeof t.plugins!=
l&&typeof t.plugins["Shockwave Flash"]==s){if((c=t.plugins["Shockwave Flash"].description)&&!(typeof t.mimeTypes!=l&&t.mimeTypes[L]&&!t.mimeTypes[L].enabledPlugin)){c=c.replace(/^.*\s+(\S+\s+\S+$)/,"$1");b[0]=parseInt(c.replace(/^(.*)\..*$/,"$1"),10);b[1]=parseInt(c.replace(/^.*\.(.*)\s.*$/,"$1"),10);b[2]=/r/.test(c)?parseInt(c.replace(/^.*r(.*)$/,"$1"),10):0}}else if(typeof m.ActiveXObject!=l){var d=null,f=false;try{d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(i){try{d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");
b=[6,0,21];d.AllowScriptAccess="always"}catch(j){if(b[0]==6)f=true}if(!f)try{d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(g){}}if(!f&&d)try{if(c=d.GetVariable("$version")){c=c.split(" ")[1].split(",");b=[parseInt(c[0],10),parseInt(c[1],10),parseInt(c[2],10)]}}catch(o){}}f=t.userAgent.toLowerCase();var k=t.platform.toLowerCase();c=/webkit/.test(f)?parseFloat(f.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):false;d=k?/win/.test(k):/win/.test(f);f=k?/mac/.test(k):/mac/.test(f);return{w3cdom:a,
pv:b,webkit:c,ie:false,win:d,mac:f}}();(function(){if(e.w3cdom){H(X);if(e.ie&&e.win)try{h.write("<script id=__ie_ondomload defer=true src=//:><\/script>");(A=n("__ie_ondomload"))&&I(A,"onreadystatechange",W)}catch(a){}if(e.webkit&&typeof h.readyState!=l)F=setInterval(function(){/loaded|complete/.test(h.readyState)&&D()},10);typeof h.addEventListener!=l&&h.addEventListener("DOMContentLoaded",D,null);P(D)}})();(function(){e.ie&&e.win&&window.attachEvent("onunload",function(){for(var a=x.length,b=0;b<
a;b++)x[b][0].detachEvent(x[b][1],x[b][2]);a=K.length;for(b=0;b<a;b++)S(K[b]);for(var c in e)e[c]=null;e=null;for(var d in swfobject)swfobject[d]=null;swfobject=null})})();return{registerObject:function(a,b,c){if(!(!e.w3cdom||!a||!b)){var d={};d.id=a;d.swfVersion=b;d.expressInstall=c?c:false;r[r.length]=d;u(a,false)}},getObjectById:function(a){var b=null;if(e.w3cdom)if(a=n(a)){var c=a.getElementsByTagName(s)[0];if(!c||c&&typeof a.SetVariable!=l)b=a;else if(typeof c.SetVariable!=l)b=c}return b},embedSWF:function(a,
b,c,d,f,i,j,g,o){if(!(!e.w3cdom||!a||!b||!c||!d||!f)){c+="";d+="";if(B(f)){u(b,false);var k={};if(o&&typeof o===s)for(var p in o)if(o[p]!=Object.prototype[p])k[p]=o[p];k.data=a;k.width=c;k.height=d;var C={};if(g&&typeof g===s)for(var M in g)if(g[M]!=Object.prototype[M])C[M]=g[M];if(j&&typeof j===s)for(var y in j)if(j[y]!=Object.prototype[y])if(typeof C.flashvars!=l)C.flashvars+="&"+y+"="+j[y];else C.flashvars=y+"="+j[y];H(function(){O(k,C,b);k.id==b&&u(b,true)})}else if(i&&!v&&B("6.0.65")&&(e.win||
e.mac)){v=true;u(b,false);H(function(){var z={};z.id=z.altContentId=b;z.width=c;z.height=d;z.expressInstall=i;Q(z)})}}},getFlashPlayerVersion:function(){return{major:e.pv[0],minor:e.pv[1],release:e.pv[2]}},hasFlashPlayerVersion:B,createSWF:function(a,b,c){if(e.w3cdom)return O(a,b,c)},removeSWF:function(a){e.w3cdom&&S(a)},createCSS:function(a,b){e.w3cdom&&U(a,b)},addDomLoadEvent:H,addLoadEvent:P,getQueryParamValue:function(a){var b=h.location.search||h.location.hash;if(a==null)return V(b);if(b){b=
b.substring(1).split("&");for(var c=0;c<b.length;c++)if(b[c].substring(0,b[c].indexOf("="))==a)return V(b[c].substring(b[c].indexOf("=")+1))}return""},expressInstallCallback:function(){if(v&&w){var a=n(R);if(a){a.parentNode.replaceChild(w,a);if(J){u(J,true);if(e.ie&&e.win)w.style.display="block"}J=w=null;v=false}}}}}();